module.exports = {
  DONATE: 'Donate',
  DONATE_DESC: 'We rely on donations to carry out our mission.',
  MESSAGE: 'Message',
  YOUR_HELPS: 'How to help',
  YOUR_HELPS_DESC: 'We rely on your helps to improve the subtitles for all languages, you can help us by the following ways',
  SUBASK_I18N_DESC: 'If you found any problem in your language you can help us to fix it in the following link',
  SUBASK_I18N: 'Subask in english',
  CONTRIBUTE: 'Edit subtitles, Confirm edits and Rate downloaded subtitles.',
  SEND_FEEDBACKS: 'Send us your feedbacks.',

  ALWAYS_RATE: 'The more feedback you give the more privileges you would have in Subask,',
  SEE_PROFILE: 'See your profile and privileges',
  AUTO_TRANS_MSG: 'Its added to a queue to become translated automatically, then you can fix the problems which has been made by auto translate.',
  UPLOAD_MSG: 'Thank you, Its added to a queue to investigate how we can use it.',
  NEEDS_LOGIN: 'You need to login',
  CHECK_EDIT: 'Please click here to check an edit',
  USER_PRIVILEGES: 'User Priviledges',
  RATED_SUBTITLES: 'Rated Subtitles',
  APPROVED_EDITS: 'Approved Edits',
  LIKED_QUOTES: 'Liked Quotes',
  REPUTATION: 'Reputation',
  SCORE: 'Score',
  PRIVILEGES: 'Privileges',
  BADGES: 'Badges',
  MOVIES: 'Movies',
  QUOTES: 'Quotes',
  LANGUAGES: 'Languages',
  EDIT_REQ: 'Needs 7 Download And Rate The Subtitles',
  QUOTES_REQ: 'Needs 15 Download And Rate The Subtitles',
  UPLOAD_REQ: 'Needs 35 Download And Rate The Subtitles',
  APPROVE_REQ: 'Needs 25 Download And Rate The Subtitles, 5 Edit',
  AUTOTRAN_REQ: 'Needs 5 Approve Edit, 10 Edit',
  NEWMOVIE_REQ: 'Needs 20 Approve Edit',
  TYPE_MOVIE: 'Enter Movie Name, Url or File',
  SUB_MISSED: 'The subtitle is not availabe',
  ADD_UR_SUB: 'Add your subtitle for this movie',
  CLICK_NXT_BTN: 'Or click on the following button to create',
  AUTO_TRANS: 'Automatically a new translation',
  NOTIFS: 'Notifications',
  USR_ACTS: 'User Activities',
  LOADING: 'Loading',
  ADD_TXT: 'Add Text',
  DIALOGS: 'Dialogs',
  H_I: 'Hearing Impaired',
  NO_H_I: 'Deaf texts has not created, click on edit to create',
  SUB_LISTS_DESC: 'Edited, recently added, translated and some other Lists of subtitles', 
  INCLUDE_H_I: 'Are you hearing impaired?',
  NOT_INCLUDED: 'Has not Added',
  INCLUDED: 'Has added',
  NO_MATCH: 'There is not any match with the search text',
  YOUR_SUB: 'Your suggested subtitle',
  TOP: 'Top',
  BOTTOM: 'Bottom',
  EDIT_TEXTS: 'Edit Texts',
  EDIT_BTN_TTL: 'To change the subtitle texts',
  SYNC: 'Synchronization',
  SYNC_TTL: 'To change the subtitle timing',
  H_I_TTL: 'Are intended for people who are hearing impaired',
  DUALITY: 'Dual Subtitles',
  DUALITY_TTL: 'Watch movies with two sets of subtitles using  bilingual subtitles',
  QUOTES_LIST_TTL: 'Movie quotes lists',
  MOVIE_LIST_TTL: 'Movie subtitles lists',
  FEEDBACK_MSG: 'We would love to hear your thoughts, concerns or problems with anything',
  ASK_NEW_MOVIE: 'Ask to add a new movie',
  ASK_MOVIE_DESC: 'Please find the movie in imdb and copy the link address into the following textbox',
  SUBMIT: 'Submit',
  NOT_VALID_IMDB_URL: 'The entered imdb url is not valid it should be like https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt',
  ADD_MOVIE_FILE: 'Click to add movie file here and make it easy to find the rightest subtitle',
  SYNC_BY_RT: "Select subtitles based on the movie's release type",
  SYNC_BY_RT_DESC: 'To get the desired subtitle, we suggest one of the above solutions. Otherwise you can sync the subtitle by selecting movie release type.',
  NEW_SYNC: 'Create a new timing for subtitle',
  NEW_SYNC_DESC: 'If you can not find the desired timing in release type list you can create a new subtitle timing as the following image',
  EDIT_ONLINE: 'Edit subtitles online',
  EDIT_ONLINE_DESC: 'You must have encountered unprofessional subtitles that are full of errors; this site provides easy editing each sentences in subtitles and you can help to improve subtitles.',
  EDITING: 'Editing subtitles',
  EDITING_DESC: 'Edits are made by users or automatically, but it needs users approval. You can find a list of subtitles that have been edited and need approval at the following link.',
  HOW_TO_FIND_SUBS_DESC: 'Finding the right subtitle for different quality movies may take your time or you may have a bad (poor translation) version. Here are some ways to access professional subtitles.',
  FIND_SUBS_WAYS: 'Three ways to find a subtitle:',
  BY_MOVIE_NAME_DESC: 'Type the movie name as the following image in the box then Select the movie to move to the subtitle download page.',
  BY_MOVIE_FILE_DESC: 'You see some suggested movies subtitle by using the + button or by dragging the movie file to the box.',
  HOME_H1: 'Find and sync subtitles',
  BRING_YOUR_SUB: 'This subtitle has not been added yet by users, if you have a good subtitle for this movie, drag it here to edit and sync and let other users access it',
  HOME_TTL: 'SubAsk - Search Subtitles', 
  HOME_KEYWORDS: 'Subtitles, Sync, Edit, Download', 
  HOME_DESC: 'Finds the right and synced subtitle for your movie, and lets you edit and improve them online ', 
  SEARCH_SUBTITLES: 'Search Subtitle',
  SUB_LISTS: 'Subtitles List',
  SUBTITLE_LANGS: 'Subtitle Languages For _MOV_',
  SUBTITLE_LANGS_DESC: 'List of translated languages for _MOV_ subtitle',
  SUBTITLE_LANGS_KEYWORDS: 'translations, _MOV_, languages',
  DEFAULT_LANGS: 'Your default language',
  AVAILABLE_LANGUAGES: 'Available Subtitle Languages',
  AVAILABLE_LANGUAGES_DESC: '_MOV_ movie subtitle in language',
  AVAILABLE_LANGUAGE_TTL: '_LANG_ subtitle of _MOV_',
  MISSED_LANGUAGES: 'Non-available Languages',
  MISSED_LANGUAGES_DESC: 'Create new subtitle for _MOV_ in language',
  FEEDBACK: 'Feedback',
  MOVIE_LANG_SUB: '_MOV_ _LANG_ Subtitle',
  DNLOAD_PAGE_DESC: 'Sync, Edit and Download _MOV_ _LANG_ Subtitle',
  MOVIE_QUOTES: '_MOV_\'s Famous Quotes',
  DNLOAD_BTN: 'Download _LANG_ subtitle',
  DOWNLOAD_PAGE_TTL: '_LANG_ subtitle for _MOV_ in _YEAR_',
  DIALOG_HINT: 'Change this dialog',
  OTHER_LANGS: 'Other Languages', 
  RELEASE_DATE: 'Date',
  MOVIE_SCORE: 'Rate',
  SEARCH_HINT: 'Search',
  THANKS: 'Thank You',
  RE_ADJUST: 'Select Another Time speed ',
  NEED_RE_ADJUST: 'Try the downloaded subtitle then if it\'s not synchronized or it gets unsync after a few minute,',
  RATE_SUB: 'Please rate the subtitle after watching the movie',
  NOT_ADDED: 'The subtitle not added',
  CHECK_EDIT: 'There is a new edition for this subtitle do you want to check it?',
  NAME: 'Name',
  OR: 'OR',
  SIGN_IN: 'Sign In',
  SIGN_IN_DESC: 'To login and make changes on subtitles',
  SIGN_UP: 'Sign Up',
  SIGN_UP_DESC: 'To create an account on SubAsk, Please sign up',
  SIGN_IN_KEYWORDS: 'SubAsk login',
  SIGN_UP_KEYWORDS: 'SubAsk signup',
  USERNAME_HAS_TAKEN: 'Username has been taken before',
  WRONG_PASS: 'Username or password is incorrect',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  SIGN_OUT: 'Sign Out',
  ABOUT: 'About',
  NAV_QUOTES: 'Quotes',
  NAV_SUBTITLES: 'Subtitles',
  FIND_SUBTITLES: 'Find subtitles',
  FOOTER_DESC :'A place to sync, edit and improve subtitles quality.',
  CONTACT_US: 'Contact Us',
  CONTACT_US_DESC: 'You can use the links below to share your comments and follow us on social media',
  SUB_LISTS_TTL: 'SubAsk subtitles lists', 
  SUB_LISTS_KEYWORDS: 'Subtitles, List, Contribute',
  EDITED_SUBS: 'Edited subtitles',
  EDITED_SUBS_DESC: 'These subtitles need to be verified or edited',
  NOT_TRANSLATED_SUBS: 'Not translated subtitles',
  NOT_TRANSLATED_SUBS_DESC: 'These subtitles should be translated in your language ',
  NOT_ADDED_MOVIES: 'Non-available Movies',
  NOT_ADDED_MOVIES_DESC: 'list of Movies without any subtitles',
  DEFECTED_SUBS: 'Defected Subtitles',
  DEFECTED_SUBS_DESC: 'Subtitles which need to be checked and review',
  NEW_MOVIE_SUBS: 'New movie subtitles',
  NEW_SUBS: 'New subtitles',
  NEW_SUBS_DESC: 'These subtitles need you to take a look and check them',
  NEW_MOVIES: 'New Movies',
  NEW_MOVIES_DESC: 'These new movies have been added recently',
  YOUR_DOWNLOADS: 'Your downloads',
  YOUR_DOWNLOADS_DESC: 'Subtitles which you have downloaded',
  YOUR_EDITS: 'Your Edits',
  YOUR_EDITS_DESC: 'Subtitles which you have edited',
  ABOUT_PAGE_TTL: 'How to get the best subtitle from SubAsk?',
  ABOUT_PAGE_DESC: 'In this page we will show you how to sync subtitle with your movie and edit them.',
  ABOUT_PAGE_KEYWORDS: 'SubAsk, how to fix subtitles, how to edit subtitles, how to sync subtitles',
  HOW_TO_FIND_SUBS: 'How to find subtitles quickly',
  BY_MOVIE_NAME_TTL: 'Using the movie name',
  BY_MOVIE_FILE_TTL: 'Using the movie file',
  BY_MOVIE_URL_TTL: 'Using the movie url',
  BY_MOVIE_URL_DESC: 'Copy the movie\'s stream url to the box and select one of suggested subtitles',
  QUOTES_LISTS_TTL: 'SubAsk - Movie quotes lists',
  QUOTES_LISTS_DESC: 'List of quotes in movies',
  QUOTES_LISTS_KEYWORDS: 'Movie quotes',
  MOVIE_QUOTES_TTL: '_MOV_ quotes',
  MOVIE_QUOTES_DESC: 'Quotes list in _MOV_ ',
  MOVIE_QUOTES_KEYWORDS: '_MOV_, quotes, favorite quotes',
  MOVIE_QUOTES_H1: '_MOV_ movie quotes',
  SEARCH_QUOTES: 'Search in quotes',
  LIKED_QUOTES_RECENTLY: 'Quotes has been liked recently',
  LIKED_QUOTES_RECENTLY_DESC: ' ',
  FIRST_LIKE_QUOTES: 'Quotes got the first like',
  FIRST_LIKE_QUOTES_DESC: ' ',
  LIKED_MOVIE_QUOTES: 'Movies quotes need attention',
  LIKED_MOVIE_QUOTES_DESC: ' ',
  POPULAR_QUOTES: 'Popular quotes',
  POPULAR_QUOTES_DESC: ' ',
  YOUR_FAV_QUOTES: 'Your favorite quotes',
  YOUR_FAV_QUOTES_DESC: ' ',
  english: 'english',
  farsi: 'farsi',
  hindi: 'hindi',
  indonesian: 'indonesian',
  turkish: 'turkish',
  malayalam: 'malayalam',
  arabic: 'arabic',
  vietnamese: 'vietnamese',
  thai: 'thai',
  malay: 'malay',
  chinese: 'chinese',
  japanese: 'japanese',
  hebrew: 'hebrew',
  bengali: 'bengali',
  croatian: 'croatian',
  portuguese: 'portuguese',
  danish: 'danish',
  german: 'german',
  dutch: 'dutch',
  korean: 'korean',
  spanish: 'spanish',
  french: 'french',
  greek: 'greek',
  swedish: 'swedish',
  norwegian: 'norwegian',
  icelandic: 'icelandic',
  italian: 'italian',
  urdu: 'urdu',
  russian: 'russian',
  romanian: 'romanian',
  pashto: 'pashto',
}
