module.exports = {
	DONATE:"Donar",
	DONATE_DESC:"Dependemos de las donaciones para llevar a cabo nuestra misión.",
	MESSAGE:"Mensaje",
	YOUR_HELPS:"Como ayudar",
	YOUR_HELPS_DESC:"Confiamos en su ayuda para mejorar los subtítulos para todos los idiomas, puede ayudarnos de las siguientes maneras",
	SUBASK_I18N_DESC:"Si encuentra algún problema en su idioma puede ayudarnos a solucionarlo en el siguiente enlace",
	SUBASK_I18N:"Subask en español",
	CONTRIBUTE:"Edite subtítulos, confirme las ediciones y valore los subtítulos descargados.",
	SEND_FEEDBACKS:"Envíenos sus comentarios.",
	ALWAYS_RATE:'Cuantos más comentarios proporcione, más privilegios tendrá en Subask,',
	SEE_PROFILE:'Ver su perfil y privilegios',
	AUTO_TRANS_MSG:'Se agrega a una cola para que se traduzca automáticamente, luego puede solucionar los problemas que se han realizado mediante la traducción automática.',
	UPLOAD_MSG:'Gracias, se agregó a una cola para investigar cómo podemos usarlo.',
	NEEDS_LOGIN:'Necesitas iniciar sesión',
	CHECK_EDIT:'Haga clic aquí para verificar una edición',
	USER_PRIVILEGES: "Privilegios de usuario",
	RATED_SUBTITLES: "Subtítulos clasificados",
	APPROVED_EDITS: "Ediciones aprobadas",
	LIKED_QUOTES: "Citas que me gustaron",
	REPUTATION: "Reputación",
	SCORE: "Puntuación",
	PRIVILEGES: "Privilegios",
	BADGES: "Insignias",
	MOVIES: "Películas",
	QUOTES: "Citas",
	LANGUAGES: "Idiomas",
	EDIT_REQ: "Necesita 7 Descargar y calificar los subtiles",
	QUOTES_REQ: "Necesita 15 Descargar y calificar los subtiles",
	UPLOAD_REQ: "Necesita 35 Descargar y calificar los subtiles",
	APPROVE_REQ: "Necesita 25 Descargar y calificar los subtiles, 5 Editar",
	AUTOTRAN_REQ: "Necesita 5 Aprobar Editar, 10 Editar",
	NEWMOVIE_REQ: "Necesita 20 Aprobar Editar",
	TYPE_MOVIE: "Ingrese el nombre de la película, URL o archivo",
	SUB_MISSED: "El subtítulo no está disponible",
	ADD_UR_SUB: "Agrega tu subtítulo para esta película",
	CLICK_NXT_BTN: "O haga clic en el siguiente botón para crear",
	AUTO_TRANS: "Automáticamente una nueva traducción",
	NOTIFS: "Notificaciones",
	USR_ACTS: "Actividades del usuario",
	LOADING: "Cargando",
	ADD_TXT: "Añadir texto",
	DIALOGS: "Diálogos",
	H_I: "discapacidad auditiva",
	NO_H_I: "No se han creado textos para sordos, haga clic en editar para crear",
	SUB_LISTS_DESC: "Listas de algunos subtítulos disponibles en SubAsk para la contribución de los usuarios",
	INCLUDE_H_I: "¿Tiene problemas de audición?",
	NOT_INCLUDED: "no ha agregado",
	INCLUDED: "ha añadido",
	NO_MATCH: "No hay ninguna coincidencia con el texto de búsqueda.",
	YOUR_SUB: "Suelta o selecciona un archivo de subtítulos aquí",
	TOP: "Parte superior",
	BOTTOM: "Fondo",
	EDIT_TEXTS: "Editar textos",
	EDIT_BTN_TTL: "Para cambiar los textos de subtítulos",
	SYNC: "Sincronización",
	SYNC_TTL: "Para cambiar el tiempo de subtítulos",
	H_I_TTL: "Están destinados a personas con discapacidad auditiva",
	DUALITY: "Subtítulos duales",
	DUALITY_TTL: "Mire películas con dos conjuntos de subtítulos usando subtítulos bilingües",
	QUOTES_LIST_TTL: "Listado de algunas citas de películas",
	MOVIE_LIST_TTL: "Listado de algunos subtítulos de películas",
	FEEDBACK_MSG: "¡Nos encantaría escuchar sus pensamientos, inquietudes o problemas con cualquier cosa!",
	ASK_NEW_MOVIE: "Solicitar agregar una nueva película",
	ASK_MOVIE_DESC: "Busque la película en imdb y copie la dirección del enlace en el siguiente cuadro de texto",
	SUBMIT: "Enviar",
	NOT_VALID_IMDB_URL: "la url imdb ingresada no es válida, debería ser como https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Haga clic para agregar el archivo de película aquí y facilitar la búsqueda del subtítulo más adecuado",
	SYNC_BY_RT: "Seleccione subtítulos en función de la calidad de la película.",
	SYNC_BY_RT_DESC: "Para obtener el subtítulo deseado, sugerimos una de las soluciones anteriores. De lo contrario, puede sincronizar los subtítulos seleccionando el tipo de lanzamiento de la película.",
	NEW_SYNC: "Crea un nuevo momento para los subtítulos",
	NEW_SYNC_DESC: "Si no puede encontrar el tiempo deseado en la lista de tipos de lanzamiento, puede crear un nuevo tiempo de subtítulos como la siguiente imagen",
	EDIT_ONLINE: "Editar subtítulos en línea",
	EDIT_ONLINE_DESC: "Debe haber encontrado subtítulos no profesionales que están llenos de errores; Este sitio proporciona una edición fácil de cada oración en subtítulos y puede ayudar a mejorar los subtítulos.",
	EDITING: "Ayuda para editar subtítulos",
	EDITING_DESC: "Las modificaciones las realizan los usuarios o automáticamente, pero necesita la aprobación de los usuarios. Puede encontrar una lista de subtítulos que se han editado y necesitan aprobación en el siguiente enlace.",
	HOW_TO_FIND_SUBS_DESC: "Encontrar el subtítulo adecuado para películas de diferente calidad puede llevar su tiempo o puede que tenga una versión mala (mala traducción). Aquí hay algunas formas de acceder a subtítulos profesionales.",
	FIND_SUBS_WAYS: "Tres formas de encontrar un subtítulo:",
	BY_MOVIE_NAME_DESC: "Escriba el nombre de la película como la siguiente imagen en el cuadro y luego seleccione la película para pasar a la página de descarga de subtítulos.",
	BY_MOVIE_FILE_DESC: "Puede ver algunos subtítulos de películas sugeridos usando el botón + o arrastrando el archivo de película al cuadro.",
	HOME_H1: "Encuentra y sincroniza subtítulos",
	BRING_YOUR_SUB: "Los usuarios aún no han agregado este subtítulo, si tiene un buen subtítulo para esta película, arrástrelo aquí para editarlo y sincronizarlo y permitir que otros usuarios accedan a él.",
	HOME_TTL: "SubAsk - Buscar subtítulos",
	HOME_KEYWORDS: "Subtítulos, Sincronizar, Editar, Descargar",
	HOME_DESC: "Encuentre los subtítulos correctos y sincronizados en su película y edítelos en línea",
	TypeMovieQualities: "Agregue o arrastre el archivo de película aquí o escriba el tipo de lanzamiento de película",
	SEARCH_SUBTITLES: "Buscar subtítulo",
	SUB_LISTS: "Lista de subtítulos",
	SUBTITLE_LANGS: "_MOV_ Traducciones",
	SUBTITLE_LANGS_DESC: "Lista de todos los idiomas traducidos del subtítulo _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "traducciones, _MOV_, idiomas",
	DEFAULT_LANGS: "Tu idioma predeterminado",
	AVAILABLE_LANGUAGES: "Idiomas de subtítulos disponibles",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ subtítulos de películas en el idioma ",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ subtítulo de _MOV_",
	MISSED_LANGUAGES: "Idiomas no disponibles",
	MISSED_LANGUAGES_DESC: "Crea nuevos subtítulos para _MOV_ en el idioma",
	FEEDBACK: "Realimentación",
	MOVIE_LANG_SUB: "_MOV_ subtítulo _LANG_",
	DNLOAD_PAGE_DESC: "Sincroniza, edita y descarga _MOV_ subtítulos en _LANG_",
	MOVIE_QUOTES: "Frases famosas de _MOV_",
	DNLOAD_BTN: "Descargar subtítulo en _LANG_",
	DOWNLOAD_PAGE_TTL: "subtítulo en _LANG_ de _MOV_ en _YEAR_",
	DIALOG_HINT: "Cambiar este diálogo",
	OTHER_LANGS: "Otros idiomas",
	RELEASE_DATE: "Fecha",
	MOVIE_SCORE: "Tarifa",
	SEARCH_HINT: "Buscar",
	THANKS: "Gracias",
	RE_ADJUST: "Seleccione otra velocidad de tiempo",
	NEED_RE_ADJUST: "Pruebe el subtítulo descargado y luego, si no está sincronizado o si no se sincroniza después de unos minutos,",
	RATE_SUB: "Danos tu opinión después de ver la película.",
	NOT_ADDED: "Necesita agregar un subtítulo",
	NAME: "Nombre",
	OR: "O",
	SIGN_IN: "Registrarse",
	SIGN_IN_DESC: "Para iniciar sesión y realizar cambios en los subtítulos",
	SIGN_UP: "Regístrate",
	SIGN_UP_DESC: "Para crear una cuenta en SubAsk, regístrese",
	SIGN_IN_KEYWORDS: "SubAsk inicio de sesión",
	SIGN_UP_KEYWORDS: "SubAsk registro",
	USERNAME_HAS_TAKEN: "Nombre de usuario ha sido tomado antes",
	WRONG_PASS: "Nombre de usuario o contraseña incorrecta",
	EMAIL: "Email",
	PASSWORD: "Contraseña",
	SIGN_OUT: "Desconectar",
	ABOUT: "acerca de",
	NAV_QUOTES: "Citas",
	NAV_SUBTITLES: "Subtitulos",
	FIND_SUBTITLES: "Encuentra subtítulos",
	FOOTER_DESC: "Un lugar para crear y editar subtítulos",
	CONTACT_US: "Contáctenos",
	CONTACT_US_DESC: "Puede usar los enlaces a continuación para compartir sus comentarios y seguirnos en las redes sociales",
	SUB_LISTS_TTL: "SubAsk Listas de subtítulos",
	SUB_LISTS_KEYWORDS: "Subtítulos, Lista, Contribuir",
	EDITED_SUBS: "Subtítulos editados",
	EDITED_SUBS_DESC: "Estos subtítulos deben ser verificados o editados",
	NOT_TRANSLATED_SUBS: "Traducir subtítulos",
	NOT_TRANSLATED_SUBS_DESC: "Estos subtítulos deben traducirse a su idioma.",
	NOT_ADDED_MOVIES: "Películas no disponibles",
	NOT_ADDED_MOVIES_DESC: "lista de películas sin subtítulos",
	DEFECTED_SUBS: "Subtítulos defectuosos",
	DEFECTED_SUBS_DESC: "Subtítulos que necesitan ser revisados ​​y revisados",
	NEW_MOVIE_SUBS: "Nuevos subtítulos de películas",
	NEW_SUBS: "Nuevos subtítulos",
	NEW_SUBS_DESC: "Estos subtítulos necesitan que le eches un vistazo y los revises",
	NEW_MOVIES: "Nuevas películas",
	NEW_MOVIES_DESC: "Estas nuevas películas se han agregado recientemente",
	YOUR_DOWNLOADS: "Sus descargas",
	YOUR_DOWNLOADS_DESC: "Subtítulos que has descargado",
	YOUR_EDITS: "Sus ediciones",
	YOUR_EDITS_DESC: "Subtítulos que has editado",
	ABOUT_PAGE_TTL: "¿Cómo obtener el mejor subtítulo de SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk permite a los usuarios sincronizar y corregir subtítulos",
	ABOUT_PAGE_KEYWORDS: "SubAsk, corregir subtítulos, editar subtítulos, sincronizar subtítulos",
	HOW_TO_FIND_SUBS: "Cómo encontrar subtítulos rápidamente",
	BY_MOVIE_NAME_TTL: "Usando el nombre de la película",
	BY_MOVIE_FILE_TTL: "Usando el archivo de película",
	BY_MOVIE_URL_TTL: "Usando la URL de la película",
	BY_MOVIE_URL_DESC: "Copie la URL de la transmisión de la película en el cuadro y seleccione uno de los subtítulos sugeridos",
	QUOTES_LISTS_TTL: "SubAsk - Listas de citas de películas",
	QUOTES_LISTS_DESC: "Lista de citas en películas",
	QUOTES_LISTS_KEYWORDS: "citas de películas",
	MOVIE_QUOTES_TTL: "_MOV_ citas",
	MOVIE_QUOTES_DESC: "Lista de cotizaciones en _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, citas, citas favoritas",
	MOVIE_QUOTES_H1: "_MOV_ Citas de películas",
	SEARCH_QUOTES: "Buscar en cotizaciones",
	LIKED_QUOTES_RECENTLY: "Las citas se han recibido recientemente",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Quotes Got the first Like",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Citas de películas necesitan atención",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Cotizaciones populares",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Tus citas favoritas",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Inglés",
	farsi: "farsi",
	hindi: "hindi",
	indonesian: "indonesio",
	turkish: "turco",
	malayalam: "malayalam",
	arabic: "Arábica",
	vietnamese: "vietnamita",
	thai: "tailandés",
	malay: "malayo",
	chinese: "chino",
	japanese: "japonés",
	hebrew: "hebreo",
	bengali: "bengalí",
	croatian: "croata",
	portuguese: "portugués",
	danish: "danés",
	german: "alemán",
	dutch: "holandés",
	korean: "coreano",
	spanish: "Español",
	french: "francés",
	greek: "griego",
	swedish: "sueco",
	norwegian: "noruego",
	icelandic: "islandés",
	italian: "italiano",
	urdu: "urdu",
	russian: "ruso",
	romanian: "rumano",
	pashto: "pashto"
}
