module.exports = {
	DONATE:"Faire un don",
	DONATE_DESC:"Nous comptons sur les dons pour mener à bien notre mission.",
	MESSAGE:"Message",
	YOUR_HELPS:"Comment aider",
	YOUR_HELPS_DESC:"Nous comptons sur votre aide pour améliorer les sous-titres pour toutes les langues, vous pouvez nous aider par les moyens suivants",
	SUBASK_I18N_DESC:"Si vous rencontrez un problème dans votre langue, vous pouvez nous aider à le résoudre dans le lien suivant",
	SUBASK_I18N:"subask en français",
	CONTRIBUTE:"Modifiez les sous-titres, confirmez les modifications et évaluez les sous-titres téléchargés.",
	SEND_FEEDBACKS:"Envoyez-nous vos commentaires.",
	ALWAYS_RATE:"Plus vous donnez de commentaires, plus vous aurez de privilèges dans Subask,",
	SEE_PROFILE:"Voir votre profil et vos privilèges",
	AUTO_TRANS_MSG:"Il est ajouté à une file d'attente pour être traduit automatiquement, vous pouvez alors résoudre les problèmes qui ont été causés par la traduction automatique.",
	UPLOAD_MSG:"Merci, il a été ajouté à une file d'attente pour savoir comment nous pouvons l'utiliser.",
	NEEDS_LOGIN:"Vous devez vous connecter",
	CHECK_EDIT:"Veuillez cliquer ici pour vérifier une modification",
	USER_PRIVILEGES: "Privilèges utilisateur",
	RATED_SUBTITLES: "Sous-titres classés",
	APPROVED_EDITS: "Modifications approuvées",
	LIKED_QUOTES: "Citations aimées",
	REPUTATION: "Réputation",
	SCORE: "But",
	PRIVILEGES: "Privilèges",
	BADGES: "BADGES",
	MOVIES: "Films",
	QUOTES: "Citations",
	LANGUAGES: "Langues",
	EDIT_REQ: "Besoin de 7 télécharger et évaluer les sous-tuiles",
	QUOTES_REQ: "Besoin de 15 télécharger et évaluer les sous-tuiles",
	UPLOAD_REQ: "Besoin de 35 Télécharger et noter les sous-tuiles",
	APPROVE_REQ: "Besoin de 25 télécharger et noter les sous-tuiles, 5 éditer",
	AUTOTRAN_REQ: "Nécessite 5 Approuver Modifier, 10 Modifier",
	NEWMOVIE_REQ: "Nécessite 20 Approuver Modifier",
	TYPE_MOVIE: "Entrez le nom du film, l'URL ou le fichier",
	SUB_MISSED: "Le sous-titre n'est pas disponible",
	ADD_UR_SUB: "Ajoutez votre sous-titre pour ce film",
	CLICK_NXT_BTN: "Ou cliquez sur le bouton suivant pour créer",
	AUTO_TRANS: "Une nouvelle traduction automatiquement",
	NOTIFS: "NOTIFS",
	USR_ACTS: "Activités des utilisateurs",
	LOADING: "Chargement",
	ADD_TXT: "Ajouter du texte",
	DIALOGS: "Dialogues",
	H_I: "Malentendant",
	NO_H_I: "Les textes sourds n'ont pas été créés, cliquez sur modifier pour créer",
	SUB_LISTS_DESC: "Listes de certains sous-titres disponibles dans SubAsk pour la contribution des utilisateurs",
	INCLUDE_H_I: "Êtes-vous malentendant?",
	NOT_INCLUDED: "n'a pas ajouté",
	INCLUDED: "a ajouté",
	NO_MATCH: "Il n'y a aucune correspondance avec le texte de recherche",
	YOUR_SUB: "Déposez ou sélectionnez un fichier de sous-titres ici",
	TOP: "Haut",
	BOTTOM: "Bas",
	EDIT_TEXTS: "Modifier les textes",
	EDIT_BTN_TTL: "Pour modifier les textes des sous-titres",
	SYNC: "Synchronisation",
	SYNC_TTL: "Pour modifier la synchronisation des sous-titres",
	H_I_TTL: "Sont destinés aux personnes malentendantes",
	DUALITY: "Double sous-titres",
	DUALITY_TTL: "Regardez des films avec deux séries de sous-titres en utilisant des sous-titres bilingues",
	QUOTES_LIST_TTL: "Liste de quelques citations de films",
	MOVIE_LIST_TTL: "Liste de sous-titres de films",
	FEEDBACK_MSG: "Nous aimerions entendre vos pensées, vos préoccupations ou vos problèmes avec quoi que ce soit!",
	ASK_NEW_MOVIE: "Demander d'ajouter un nouveau film",
	ASK_MOVIE_DESC: "Veuillez trouver le film dans imdb et copiez l'adresse du lien dans la zone de texte suivante",
	SUBMIT: "Soumettre",
	NOT_VALID_IMDB_URL: "l'URL imdb saisie n'est pas valide, elle devrait être comme https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Cliquez ici pour ajouter un fichier vidéo et trouver facilement le sous-titre le plus approprié",
	SYNC_BY_RT: "Sélectionnez les sous-titres en fonction de la qualité du film",
	SYNC_BY_RT_DESC: "Pour obtenir le sous-titre souhaité, nous suggérons l'une des solutions ci-dessus. Sinon, vous pouvez synchroniser les sous-titres en sélectionnant le type de sortie de film.",
	NEW_SYNC: "Créer un nouveau timing pour les sous-titres",
	NEW_SYNC_DESC: "Si vous ne trouvez pas le timing souhaité dans la liste des types de versions, vous pouvez créer un nouveau timing de sous-titres comme l'image suivante",
	EDIT_ONLINE: "Modifier les sous-titres en ligne",
	EDIT_ONLINE_DESC: "Vous devez avoir rencontré des sous-titres non professionnels qui sont pleins d'erreurs; ce site permet de modifier facilement chaque phrase en sous-titres et vous pouvez aider à améliorer les sous-titres.",
	EDITING: "Aide à l'édition des sous-titres",
	EDITING_DESC: "Les modifications sont effectuées par les utilisateurs ou automatiquement, mais elles nécessitent l'approbation des utilisateurs. Vous pouvez trouver une liste des sous-titres qui ont été modifiés et doivent être approuvés sur le lien suivant.",
	HOW_TO_FIND_SUBS_DESC: "Trouver le bon sous-titre pour des films de qualité différente peut prendre votre temps ou vous pouvez avoir une mauvaise version (mauvaise traduction). Voici quelques façons d'accéder aux sous-titres professionnels.",
	FIND_SUBS_WAYS: "Trois façons de trouver un sous-titre:",
	BY_MOVIE_NAME_DESC: "Tapez le nom du film comme l'image suivante dans la case, puis sélectionnez le film à déplacer vers la page de téléchargement des sous-titres.",
	BY_MOVIE_FILE_DESC: "Vous voyez des sous-titres de films suggérés en utilisant le bouton + ou en faisant glisser le fichier du film vers la boîte.",
	HOME_H1: "Rechercher et synchroniser des sous-titres",
	BRING_YOUR_SUB: "Ce sous-titre n'a pas encore été ajouté par les utilisateurs, si vous avez un bon sous-titre pour ce film, faites-le glisser ici pour le modifier et le synchroniser et laissez les autres utilisateurs y accéder",
	HOME_TTL: "SubAsk - Recherche de sous-titres",
	HOME_KEYWORDS: "Sous-titres, Synchroniser, Modifier, Télécharger",
	HOME_DESC: "Trouvez le sous-titre correct et synchronisé dans votre film et modifiez-le en ligne",
	TypeMovieQualities: "Ajoutez ou faites glisser un fichier de film ici ou tapez le type de version du film",
	SEARCH_SUBTITLES: "Recherche sous-titre",
	SUB_LISTS: "Liste des sous-titres",
	SUBTITLE_LANGS: "_MOV_ Traductions",
	SUBTITLE_LANGS_DESC: "Liste de toutes les langues traduites du sous-titre _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "traductions, _MOV_, langues",
	DEFAULT_LANGS: "Votre langage par défaut",
	AVAILABLE_LANGUAGES: "Langues de sous-titres disponibles",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ sous-titre du film dans la langue",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ sous-titre de _MOV_",
	MISSED_LANGUAGES: "Langues non disponibles",
	MISSED_LANGUAGES_DESC: "Créer un nouveau sous-titre pour _MOV_ dans la langue",
	FEEDBACK: "Retour d'information",
	MOVIE_LANG_SUB: "_MOV_ sous-titre _LANG_",
	DNLOAD_PAGE_DESC: "Synchronisez, modifiez et téléchargez _MOV_ sous-titre _LANG_",
	MOVIE_QUOTES: "Citations célèbres de _MOV_",
	DNLOAD_BTN: "Téléchargez le sous-titre _LANG_",
	DOWNLOAD_PAGE_TTL: "sous-titre _LANG_ pour _MOV_ dans _YEAR_",
	DIALOG_HINT: "Changer ce dialogue",
	OTHER_LANGS: "Autres langues",
	RELEASE_DATE: "Date",
	MOVIE_SCORE: "Taux",
	SEARCH_HINT: "Chercher",
	THANKS: "Merci",
	RE_ADJUST: "Sélectionnez une autre vitesse temporelle",
	NEED_RE_ADJUST: "Essayez le sous-titre téléchargé, s'il n'est pas synchronisé ou s'il devient désynchronisé après quelques minutes,",
	RATE_SUB: "S'il vous plaît nous donner vos commentaires après avoir regardé le film",
	NOT_ADDED: "Besoin d'ajouter un sous-titre",
	CHECK_EDIT: "Il y a une nouvelle édition pour ce sous-titre, voulez-vous vérifier?",
	NAME: "Nom",
	OR: "OU",
	SIGN_IN: "Se connecter",
	SIGN_IN_DESC: "Pour vous connecter et apporter des modifications sur les sous-titres",
	SIGN_UP: "S'inscrire",
	SIGN_UP_DESC: "Pour créer un compte sur SubAsk, veuillez vous inscrire.",
	SIGN_IN_KEYWORDS: "SubAsk login",
	SIGN_UP_KEYWORDS: "SubAsk inscription",
	USERNAME_HAS_TAKEN: "Le nom d'utilisateur a été pris avant",
	WRONG_PASS: "L'identifiant ou le mot de passe est incorrect",
	EMAIL: "Email",
	PASSWORD: "Mot de passe",
	SIGN_OUT: "Déconnexion",
	ABOUT: "sur",
	NAV_QUOTES: "Citations",
	NAV_SUBTITLES: "Les sous-titres",
	FIND_SUBTITLES: "Rechercher des sous-titres",
	FOOTER_DESC: "Un endroit pour créer et éditer des sous-titres",
	CONTACT_US: "Contactez-nous",
	CONTACT_US_DESC: "Vous pouvez utiliser les liens ci-dessous pour partager vos commentaires et nous suivre sur les médias sociaux.",
	SUB_LISTS_TTL: "SubAsk Listes de sous-titres",
	SUB_LISTS_KEYWORDS: "Sous-titres, Liste, Contribute",
	EDITED_SUBS: "Sous-titres édités",
	EDITED_SUBS_DESC: "Ces sous-titres doivent être vérifiés ou édités",
	NOT_TRANSLATED_SUBS: "Traduire les sous-titres",
	NOT_TRANSLATED_SUBS_DESC: "Ces sous-titres doivent être traduits dans votre langue.",
	NOT_ADDED_MOVIES: "Films non disponibles",
	NOT_ADDED_MOVIES_DESC: "liste des films sans sous-titres",
	DEFECTED_SUBS: "Sous-titres défigurés",
	DEFECTED_SUBS_DESC: "Sous-titres qui doivent être vérifiés et révisés",
	NEW_MOVIE_SUBS: "Nouveau film Sous-titres",
	NEW_SUBS: "Nouveaux sous-titres",
	NEW_SUBS_DESC: "Ces sous-titres ont besoin de vous pour regarder et les vérifier",
	NEW_MOVIES: "Nouveaux Films",
	NEW_MOVIES_DESC: "Ces nouveaux films ont été ajoutés récemment",
	YOUR_DOWNLOADS: "Vos téléchargements",
	YOUR_DOWNLOADS_DESC: "Sous-titres que vous avez téléchargés",
	YOUR_EDITS: "Vos modifications",
	YOUR_EDITS_DESC: "Sous-titres que vous avez édités",
	ABOUT_PAGE_TTL: "Comment obtenir le meilleur sous-titre de SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk permet aux utilisateurs de synchroniser et de corriger les sous-titres",
	ABOUT_PAGE_KEYWORDS: "SubAsk, correction des sous-titres, modification des sous-titres, synchronisation des sous-titres",
	HOW_TO_FIND_SUBS: "Comment trouver les sous-titres rapidement",
	BY_MOVIE_NAME_TTL: "Utiliser le nom du film",
	BY_MOVIE_FILE_TTL: "Utiliser le fichier de film",
	BY_MOVIE_URL_TTL: "Utiliser l'URL du film",
	BY_MOVIE_URL_DESC: "Copiez l'URL du flux du film dans la boîte et sélectionnez l'un des sous-titres suggérés.",
	QUOTES_LISTS_TTL: "SubAsk - Listes de citations de films",
	QUOTES_LISTS_DESC: "Liste de citations dans les films",
	QUOTES_LISTS_KEYWORDS: "citations de film",
	MOVIE_QUOTES_TTL: "_MOV_ citations",
	MOVIE_QUOTES_DESC: "Liste des citations dans _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, citations, citations préférées",
	MOVIE_QUOTES_H1: "_MOV_ Citations de films",
	SEARCH_QUOTES: "Rechercher dans les citations",
	LIKED_QUOTES_RECENTLY: "Citations a été aimé récemment",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Les citations ont le premier comme",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Films citations ont besoin d'attention",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Citations populaires",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Vos citations préférées",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Anglais",
	farsi: "farsi",
	hindi: "hindi",
	indonesian: "indonésien",
	turkish: "turc",
	malayalam: "malayalam",
	arabic: "arabe",
	vietnamese: "vietnamien",
	thai: "thaïlandais",
	malay: "malais",
	chinese: "chinois",
	japanese: "Japonais",
	hebrew: "hébreu",
	bengali: "bengali",
	croatian: "croate",
	portuguese: "Portugais",
	danish: "danois",
	german: "allemand",
	dutch: "néerlandais",
	korean: "coréen",
	spanish: "Espagnol",
	french: "français",
	greek: "grec",
	swedish: "suédois",
	norwegian: "norvégien",
	icelandic: "islandais",
	italian: "italien",
	urdu: "ourdou",
	russian: "russe",
	romanian: "roumain",
	pashto: "pashto"
}
