module.exports ={
	DONATE:"לִתְרוֹם",
	DONATE_DESC:"אנו מסתמכים על תרומות לביצוע משימתנו.",
	MESSAGE:"הוֹדָעָה",
	YOUR_HELPS:"איך לעזור",
	YOUR_HELPS_DESC:"אנו מסתמכים על העזרה שלך בשיפור הכתוביות לכל השפות. אתה יכול לעזור לנו בדרכים הבאות",
	SUBASK_I18N_DESC:"אם מצאת בעיה כלשהי בשפה שלך תוכל לעזור לנו לתקן אותה בקישור הבא",
	SUBASK_I18N:"Subask בעברית",
	CONTRIBUTE:"ערוך כתוביות, אשר עריכות ודרג כתוביות שהורדת.",
	SEND_FEEDBACKS:"שלח לנו את הפידבקים שלך.",
	ALWAYS_RATE:"ככל שתעניק יותר משוב כך תהיה לך יותר הרשאות בסבאסק,",
	SEE_PROFILE:"ראה את הפרופיל וההרשאות שלך",
	AUTO_TRANS_MSG:"זה נוסף לתור כדי לתרגם אוטומטית, ואז אתה יכול לתקן את הבעיות שנעשו בתרגום אוטומטי.",
	UPLOAD_MSG:"תודה, זה נוסף לתור כדי לחקור כיצד נוכל להשתמש בו.",
	NEEDS_LOGIN:"אתה צריך להתחבר",
	CHECK_EDIT:"אנא לחץ כאן כדי לבדוק עריכה",
	USER_PRIVILEGES: "הרשאות משתמש",
	RATED_SUBTITLES: "כתוביות מדורג",
	APPROVED_EDITS: "עריכות שאושרו",
	LIKED_QUOTES: "הצעות מחיר אהובות",
	REPUTATION: "תדמית",
	SCORE: "ציון",
	PRIVILEGES: "פריבילגיות",
	BADGES: "תגים",
	MOVIES: "סרטים",
	QUOTES: "ציטוטים",
	LANGUAGES: "שפות",
	EDIT_REQ: "צריך 7 הורדות ודרג את תוכנות המשנה",
	QUOTES_REQ: "צריך 15 הורדות ודרג את תוכנות המשנה",
	UPLOAD_REQ: "זקוק ל 35 הורדה ודרג את תוכנות המשנה",
	APPROVE_REQ: "צריך 25 הורדות ודרג את תוכנות המשנה, 5 ערוך",
	AUTOTRAN_REQ: "צרכים 5 מאשרים עריכה, 10 עריכה",
	NEWMOVIE_REQ: "צרכים 20 מאשרים עריכה",
	TYPE_MOVIE: "הזן שם סרט, כתובת אתר או קובץ",
	SUB_MISSED: "כתובית אינה זמינה",
	ADD_UR_SUB: "הוסף את הכתובית שלך לסרט זה",
	CLICK_NXT_BTN: "או לחץ על הכפתור הבא כדי ליצור",
	AUTO_TRANS: "באופן אוטומטי תרגום חדש",
	NOTIFS: "התראות",
	USR_ACTS: "פעילויות משתמש",
	LOADING: "טוען",
	ADD_TXT: "הוסף טקסט",
	DIALOGS: "דיאלוגים",
	H_I: "לקויי שמיעה",
	NO_H_I: "טקסטים חרשים לא נוצרו, לחץ על עריכה כדי ליצור",
	SUB_LISTS_DESC: "רשימות של כמה כתוביות זמינות ב- SubAsk לתרומת המשתמשים",
	INCLUDE_H_I: "האם אתה לקוי שמיעה?",
	NOT_INCLUDED: "לא הוסיף",
	INCLUDED: "הוסיף",
	NO_MATCH: "אין התאמה לטקסט החיפוש",
	YOUR_SUB: "שחרר או בחר קובץ כתוביות כאן",
	TOP: "חלק עליון",
	BOTTOM: "בתחתית",
	EDIT_TEXTS: "ערוך טקסטים",
	EDIT_BTN_TTL: "כדי לשנות את טקסטי הכתוביות",
	SYNC: "סנכרון",
	SYNC_TTL: "כדי לשנות את תזמון הכתוביות",
	H_I_TTL: "מיועדים לאנשים לקויי שמיעה",
	DUALITY: "כתוביות כפולות",
	DUALITY_TTL: "צפו בסרטים עם שתי קבוצות של כתוביות בעזרת כתוביות דו-לשוניות",
	QUOTES_LIST_TTL: "מפרט כמה ציטוטים לסרטים",
	MOVIE_LIST_TTL: "מפרט כמה כתוביות לסרטים",
	FEEDBACK_MSG: "נשמח לשמוע את המחשבות, הדאגות או הבעיות שלך בכל דבר!",
	ASK_NEW_MOVIE: "בקש להוסיף סרט חדש",
	ASK_MOVIE_DESC: "אנא מצא את הסרט ב- imdb והעתק את כתובת הקישור לתיבת הטקסט הבאה",
	SUBMIT: "שלח",
	NOT_VALID_IMDB_URL: "כתובת האתר של ה- imdb שהוזנה אינה תקפה והיא צריכה להיות כמו https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "לחץ כדי להוסיף קובץ סרט כאן ולהקל על מציאת כותרת המשנה הנכונה ביותר",
	SYNC_BY_RT: "בחר כתוביות על סמך איכות הסרט",
	SYNC_BY_RT_DESC: "כדי לקבל את הכותרת המשנה הרצויה, אנו מציעים אחד מהפתרונות לעיל. אחרת אתה יכול לסנכרן את הכתובית על ידי בחירת סוג יציאת הסרט.",
	NEW_SYNC: "צור תזמון חדש עבור כותרת המשנה",
	NEW_SYNC_DESC: "אם אינך מצליח למצוא את התזמון הרצוי ברשימת סוג השחרור, תוכל ליצור תזמון כתוביות חדש כתמונה הבאה",
	EDIT_ONLINE: "ערוך כתוביות באופן מקוון",
	EDIT_ONLINE_DESC: "בטח נתקלת בכתוביות לא מקצועיות מלאות בשגיאות; אתר זה מספק עריכה קלה של כל המשפטים בכתוביות ותוכלו לעזור בשיפור הכתוביות.",
	EDITING: "עזרה בעריכת כתוביות",
	EDITING_DESC: "העריכה נעשית על ידי משתמשים או באופן אוטומטי, אך היא זקוקה לאישור המשתמשים. תוכל למצוא רשימת כתוביות שנערכו וצריכות אישור בקישור הבא.",
	HOW_TO_FIND_SUBS_DESC: "מציאת כותרת המשנה הנכונה לסרטים באיכות שונה עשוי לקחת את הזמן שלך או שתיתכן גרסה גרועה (תרגום גרוע). להלן כמה דרכים לגשת לתרגום לעברית עם כתוביות מקצועיות.",
	FIND_SUBS_WAYS: "שלוש דרכים למצוא כתובית:",
	BY_MOVIE_NAME_DESC: "הקלד את שם הסרט כתמונה הבאה בתיבה ואז בחר את הסרט כדי לעבור לדף ההורדה של כתוביות.",
	BY_MOVIE_FILE_DESC: "אתה רואה כמה כתוביות לסרטים המוצעים באמצעות כפתור + או על ידי גרירת קובץ הסרט לתיבה.",
	HOME_H1: "מצא וסנכרן כתוביות",
	BRING_YOUR_SUB: "כותרת המשנה הזו לא נוספה על ידי משתמשים עדיין, אם יש לך כתובית טובה לסרט זה, גרור אותו לכאן כדי לערוך ולסנכרן ולתת למשתמשים אחרים לגשת אליו",
	HOME_TTL: "SubAsk - כתוביות לחיפוש",
	HOME_KEYWORDS: "כתוביות, סנכרון, עריכה, הורדה",
	HOME_DESC: "מצא את הכתובית הנכונה והסינכרונית בסרט שלך, וערוך אותם באופן מקוון",
	TypeMovieQualities: "הוסף או גרור קובץ סרטים לכאן או הקלד את סוג יציאת הסרט",
	SEARCH_SUBTITLES: "כתובית חיפוש",
	SUB_LISTS: "רשימת הכתוביות",
	SUBTITLE_LANGS: "_MOV_ תרגומים",
	SUBTITLE_LANGS_DESC: "רשימת כל השפות המתורגמות של כותרת המשנה _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "תרגומים, _MOV_, שפות",
	DEFAULT_LANGS: "שפת ברירת המחדל שלך",
	AVAILABLE_LANGUAGES: "שפות כתוביות זמינות",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ כתוביות לסרט בשפה",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ כתובית של _MOV_",
	MISSED_LANGUAGES: "שפות לא זמינות",
	MISSED_LANGUAGES_DESC: "צור כתובית חדשה עבור _MOV_ בשפה",
	FEEDBACK: "משוב",
	MOVIE_LANG_SUB: "_MOV_ כתובית _LANG_",
	DNLOAD_PAGE_DESC: "סנכרון, עריכה והורדה של _MOV_ כתוביות _LANG_",
	MOVIE_QUOTES: "הציטוטים המפורסמים של _MOV_",
	DNLOAD_BTN: "הורד כתובית _LANG_",
	DOWNLOAD_PAGE_TTL: "כתובית _LANG_ עבור _MOV_ ב- _YEAR_",
	DIALOG_HINT: "שנה דיאלוג זה",
	OTHER_LANGS: "שפות אחרות",
	RELEASE_DATE: "תאריך",
	MOVIE_SCORE: "ציון",
	SEARCH_HINT: "לחפש",
	THANKS: "תודה",
	RE_ADJUST: "בחר מהירות זמן אחרת",
	NEED_RE_ADJUST: "נסה את הכותרת המשנה שהורדת ואז אם היא לא מסונכרנת או שהיא מתבטלת בסינכרון לאחר מספר דקות,",
	RATE_SUB: "אנא תן לנו את המשוב שלך לאחר צפייה בסרט",
	NOT_ADDED: "צריך להוסיף כתובית",
	NAME: "שם",
	OR: "או",
	SIGN_IN: "היכנס",
	SIGN_IN_DESC: "כדי להתחבר ולבצע שינויים בכתוביות",
	SIGN_UP: "הירשם",
	SIGN_UP_DESC: "ליצירת חשבון ב- SubAsk, אנא הירשם",
	SIGN_IN_KEYWORDS: "SubAsk התחברות",
	SIGN_UP_KEYWORDS: "הרשמה SubAsk",
	USERNAME_HAS_TAKEN: "שם המשתמש נלקח בעבר",
	WRONG_PASS: "שם המשתמש או הסיסמה שגויים",
	EMAIL: "אימייל",
	PASSWORD: "סיסמה",
	SIGN_OUT: "התנתק",
	ABOUT: "על אודות",
	NAV_QUOTES: "ציטוטים",
	NAV_SUBTITLES: "כתוביות",
	FIND_SUBTITLES: "מצא כתוביות",
	FOOTER_DESC: "מקום ליצור ולערוך כתוביות",
	CONTACT_US: "תיצור איתנו קשר",
	CONTACT_US_DESC: "אתה יכול להשתמש בקישורים למטה כדי לשתף את התגובות שלך ולעקוב אחרינו במדיה החברתית",
	SUB_LISTS_TTL: "SubAsk רשימות כתוביות",
	SUB_LISTS_KEYWORDS: "כתוביות, רשימה, תרומה",
	EDITED_SUBS: "כתוביות ערוכות",
	EDITED_SUBS_DESC: "צריך לאמת או לערוך כתוביות אלה",
	NOT_TRANSLATED_SUBS: "תרגם כתוביות",
	NOT_TRANSLATED_SUBS_DESC: "יש לתרגם את הכתוביות בשפה שלך",
	NOT_ADDED_MOVIES: "סרטים שאינם זמינים",
	NOT_ADDED_MOVIES_DESC: "רשימת סרטים ללא כתוביות",
	DEFECTED_SUBS: "כתוביות ערוכות",
	DEFECTED_SUBS_DESC: "כתוביות שצריך לבדוק ולעיין בהן",
	NEW_MOVIE_SUBS: "כתוביות לסרטים חדשים",
	NEW_SUBS: "כתוביות חדשות",
	NEW_SUBS_DESC: "כתוביות אלה זקוקות לכם להציץ ולבדוק אותם",
	NEW_MOVIES: "סרטים חדשים",
	NEW_MOVIES_DESC: "הסרטים החדשים הללו נוספו לאחרונה",
	YOUR_DOWNLOADS: "ההורדות שלך",
	YOUR_DOWNLOADS_DESC: "כתוביות שהורדת",
	YOUR_EDITS: "העריכות שלך",
	YOUR_EDITS_DESC: "כתוביות שערכתם",
	ABOUT_PAGE_TTL: "איך להשיג את הכותרת המשנה הטובה ביותר מ- SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk מאפשר למשתמשים לסנכרן ולתקן כתוביות",
	ABOUT_PAGE_KEYWORDS: "SubAsk, לתקן כתובית, לערוך כתובית, לסנכרן כתוביות",
	HOW_TO_FIND_SUBS: "כיצד למצוא כתוביות במהירות",
	BY_MOVIE_NAME_TTL: "שימוש בשם הסרט",
	BY_MOVIE_FILE_TTL: "שימוש בקובץ הסרט",
	BY_MOVIE_URL_TTL: "באמצעות כתובת האתר של הסרט",
	BY_MOVIE_URL_DESC: "העתק את כתובת האתר של הזרם לתיבה ובחר אחת מהכתוביות המוצעות",
	QUOTES_LISTS_TTL: "SubAsk - רשימות ציטוטים של סרטים",
	QUOTES_LISTS_DESC: "רשימת ציטוטים בסרטים",
	QUOTES_LISTS_KEYWORDS: "ציטוטים בסרט",
	MOVIE_QUOTES_TTL: "_MOV_ ציטוטים",
	MOVIE_QUOTES_DESC: "רשימת ציטוטים ב- _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, ציטוטים, ציטוטים מועדפים",
	MOVIE_QUOTES_H1: "_MOV_ ציטוטים לסרטים",
	SEARCH_QUOTES: "חפש בציטוטים",
	LIKED_QUOTES_RECENTLY: "ציטוטים אהבו לאחרונה",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "ציטוטים קיבלו את הדומה לייק הראשון",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "ציטוטים של סרטים זקוקים לתשומת לב",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "ציטוטים פופולריים",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "הציטוטים המועדפים עליך",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "אנגלית",
	farsi: "פרסי",
	hindi: "הינדית",
	indonesian: "אינדונזית",
	turkish: "טורקי",
	malayalam: "מלזאלם",
	arabic: "ערבית",
	vietnamese: "ויאטנמית",
	thai: "תאילנדי",
	malay: "מלזית",
	chinese: "סינית",
	japanese: "יפנית",
	hebrew: "עברי",
	bengali: "בנגאלי",
	croatian: "קרואטי",
	portuguese: "פורטוגזית",
	danish: "דנית",
	german: "גרמנית",
	dutch: "הולנדית",
	korean: "קוריאנית",
	spanish: "ספרדית",
	french: "צרפתית",
	greek: "יווני",
	swedish: "שוודית",
	norwegian: "נורווגית",
	icelandic: "איסלנדית",
	italian: "אִיטַלְקִית",
	urdu: "אורדו",
	russian: "רוּסִי",
	romanian: "רומנית",
	pashto: "פשטו"
}