module.exports = {
	DONATE:"Donirajte",
	DONATE_DESC:"U izvršavanju svoje misije oslanjamo se na donacije.",
	MESSAGE:"Poruka",
	YOUR_HELPS:"Kako pomoći",
	YOUR_HELPS_DESC:"Oslanjamo se na vašu pomoć za poboljšanje titlova za sve jezike, a možete nam pomoći na sljedeće načine",
	SUBASK_I18N_DESC:"Ako ste pronašli bilo kakav problem na svom jeziku, možete nam pomoći da ga riješimo na sljedećoj poveznici",
	SUBASK_I18N:"Subask na hrvatskom",
	CONTRIBUTE:"Uredite titlove, potvrdite izmjene i ocijenite preuzete titlove.",
	SEND_FEEDBACKS:"Pošaljite nam svoje povratne informacije.",
	ALWAYS_RATE:"Što više povratnih informacija date, više privilegija biste imali u Subask-u,",
	SEE_PROFILE:"Pogledajte svoj profil i privilegije",
	AUTO_TRANS_MSG:"Dodaje se u red za automatsko prevođenje, a zatim možete riješiti probleme nastale automatskim prevođenjem.",
	UPLOAD_MSG:"Hvala, dodan je u red za istragu kako ga možemo koristiti.",
	NEEDS_LOGIN:"Morate se prijaviti",
	CHECK_EDIT:"Kliknite ovdje da biste provjerili uređivanje",
	TYPE_MOVIE: "Unesite naziv filma, URL ili datoteku",
	SUB_MISSED: "Podnaslov nije dostupan",
	ADD_UR_SUB: "Dodajte svoj titl za ovaj film",
	CLICK_NXT_BTN: "Ili kliknite sljedeći gumb za stvaranje",
	AUTO_TRANS: "Automatski novi prijevod",
	NOTIFS: "Obavijesti",
	USR_ACTS: "Aktivnosti korisnika",
	LOADING: "Učitavam",
	ADD_TXT: "Dodaj tekst",
	DIALOGS: "Dijalozi",
	H_I: "Oštećen sluh",
	NO_H_I: "Gluhi tekstovi nisu stvoreni, kliknite na uredi za stvaranje",
	SUB_LISTS_DESC: "Popisi nekih dostupnih titlova u SubAsk za doprinos korisnika",
	INCLUDE_H_I: "Imate li oštećenje sluha?",
	NOT_INCLUDED: "Korisnik nije dodan",
	INCLUDED: "je dodao",
	NO_MATCH: "Ne postoji podudaranje s tekstom pretraživanja",
	YOUR_SUB: "Ovdje ispustite ili odaberite datoteku s titlovima",
	TOP: "Vrh",
	BOTTOM: "Dno",
	EDIT_TEXTS: "Uređivanje tekstova",
	EDIT_BTN_TTL: "Za promjenu tekstova podnaslova",
	SYNC: "Sinkronizacija",
	SYNC_TTL: "Za promjenu vremena titlova",
	H_I_TTL: "Namijenjeni su osobama sa oštećenjem sluha",
	DUALITY: "Dvostruki titlovi",
	DUALITY_TTL: "Gledajte filmove s dva niza titlova koristeći dvojezične titlove",
	QUOTES_LIST_TTL: "Navođenje nekih filmskih citata",
	MOVIE_LIST_TTL: "Navođenje nekih titlova za filmove",
	FEEDBACK_MSG: "Voljeli bismo čuti vaše misli, zabrinutosti ili probleme s bilo čim!",
	ASK_NEW_MOVIE: "Zatražite dodavanje novog filma",
	ASK_MOVIE_DESC: "Pronađite film u imdb i kopirajte adresu veze u sljedeći tekstni okvir",
	SUBMIT: "podnijeti",
	NOT_VALID_IMDB_URL: "uneseni imdb URL nije važeći trebao bi biti poput https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Kliknite ovdje da dodate filmsku datoteku i olakšate pronalaženje najjačih podnaslova",
	SYNC_BY_RT: "Odaberite titlove na temelju kvalitete filma",
	SYNC_BY_RT_DESC: "Da biste dobili željeni podnaslov, predlažemo jedno od gore navedenih rješenja. Inače možete sinkronizirati podnaslov odabirom vrste izdanja filma.",
	NEW_SYNC: "Stvaranje novog vremena za podnaslove",
	NEW_SYNC_DESC: "Ako na popisu vrsta izdanja ne možete pronaći željeno vrijeme, možete stvoriti novu vremensku podnaslov kao sljedeću sliku",
	EDIT_ONLINE: "Uređivanje titlova na mreži",
	EDIT_ONLINE_DESC: "Sigurno ste naišli na neprofesionalne titlove koji su puni pogrešaka; Ova stranica omogućuje jednostavno uređivanje svake rečenice u titlovima, a možete pomoći i u poboljšanju titlova.",
	EDITING: "Pomozite u uređivanju titlova",
	EDITING_DESC: "Izmjene vrše korisnici ili automatski, ali za to je potrebno odobrenje korisnika. Popis titlova koji su uređeni i treba im odobrenje možete pronaći na sljedećoj poveznici.",
	HOW_TO_FIND_SUBS_DESC: "Pronalaženje pravog podnaslova za filmove različitih kvaliteta možda vam treba vremena ili vam je potrebna loša verzija (lošeg prijevoda). Evo nekoliko načina za pristup profesionalnim titlovima.",
	FIND_SUBS_WAYS: "Tri načina za pronalaženje titlova:",
	BY_MOVIE_NAME_DESC: "Upišite naziv filma kao sljedeću sliku u okvir, a zatim odaberite film za pomicanje na stranicu za preuzimanje titlova.",
	BY_MOVIE_FILE_DESC: "Neke predložene podnaslove filmova vidite pomoću gumba + ili povlačenjem datoteke filma u okvir.",
	HOME_H1: "Pronađite i sinkronizirajte titlove",
	BRING_YOUR_SUB: "Korisnici još nisu dodali ovaj podnaslov. Ako imate dobar podnaslov za ovaj film, povucite ga ovdje za uređivanje i sinkronizaciju i ostalim korisnicima omogućite pristup",
	HOME_TTL: "SubAsk - Pretraži titlove",
	HOME_KEYWORDS: "Titlovi, Sinhronizacija, Uredi, Preuzmi",
	HOME_DESC: "Pronađite pravi i sinkronizirani podnaslov u svom filmu i uredite ih na mreži",
	TypeMovieQualities: "Ovdje dodajte ili povucite datoteku filma ili upišite vrstu izdanja filma",
	SEARCH_SUBTITLES: "Pretraži titl",
	SUB_LISTS: "Popis titlova",
	SUBTITLE_LANGS: "_MOV_ Prijevodi",
	SUBTITLE_LANGS_DESC: "Popis svih prevedenih jezika _MOV_ podnaslova",
	SUBTITLE_LANGS_KEYWORDS: "prijevodi, _MOV_, jezici",
	DEFAULT_LANGS: "Vaš zadani jezik",
	AVAILABLE_LANGUAGES: "Dostupni jezici titlova",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ titl filma na jeziku _LANG_",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ podnaslov _MOV_",
	MISSED_LANGUAGES: "Nedostupni jezici",
	MISSED_LANGUAGES_DESC: "Napravite novi podnaslov za _MOV_ na jeziku",
	FEEDBACK: "Povratne informacije",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ podnaslov",
	DNLOAD_PAGE_DESC: "Sinkronizirajte, uredite i preuzmite _MOV_ _LANG_ podnaslov",
	MOVIE_QUOTES: "_MOV_-ovi poznati navodnici",
	DNLOAD_BTN: "Preuzmi _LANG_ titl",
	DOWNLOAD_PAGE_TTL: "_LANG_ podnapis za _MOV_ u _YEAR_",
	DIALOG_HINT: "Promijenite ovaj dijaloški okvir",
	OTHER_LANGS: "Drugi jezici",
	RELEASE_DATE: "Datum",
	MOVIE_SCORE: "Stopa",
	SEARCH_HINT: "traži",
	THANKS: "Hvala vam",
	RE_ADJUST: "Odaberite drugu vremensku brzinu",
	NEED_RE_ADJUST: "Pokušajte s preuzetim podnaslovom ako nakon nekoliko minuta nije sinkroniziran ili se nesinhronizira,",
	RATE_SUB: "Molimo da nam kažete svoje komentare nakon gledanja filma",
	NOT_ADDED: "Potrebno je dodati podnaslov",
	NAME: "Ime",
	OR: "ILI",
	SIGN_IN: "Prijaviti se",
	SIGN_IN_DESC: "Da biste se prijavili i unijeli promjene na titlovima",
	SIGN_UP: "Prijavite se",
	SIGN_UP_DESC: "Da biste stvorili račun na SubAsk, prijavite se",
	SIGN_IN_KEYWORDS: "SubAsk prijava",
	SIGN_UP_KEYWORDS: "SubAsk prijava",
	USERNAME_HAS_TAKEN: "Korisničko ime je preuzeto",
	WRONG_PASS: "Korisničko ime ili lozinka nisu točni",
	EMAIL: "E-mail",
	PASSWORD: "Lozinka",
	SIGN_OUT: "Odjavi se",
	ABOUT: "oko",
	NAV_QUOTES: "Citati",
	NAV_SUBTITLES: "titlovi",
	FIND_SUBTITLES: "Pronađi titlove",
	FOOTER_DESC: "Mjesto za stvaranje i uređivanje titlova",
	CONTACT_US: "Kontaktirajte nas",
	CONTACT_US_DESC: "Veze dolje možete koristiti za dijeljenje komentara i praćenje nas na društvenim mrežama",
	SUB_LISTS_TTL: "Popisi titlova SubAsk",
	SUB_LISTS_KEYWORDS: "Titlovi, spisak, doprinos",
	EDITED_SUBS: "Uređeni titlovi",
	EDITED_SUBS_DESC: "Ove titlove treba provjeriti ili urediti",
	NOT_TRANSLATED_SUBS: "Prevedi titlove",
	NOT_TRANSLATED_SUBS_DESC: "Ti titlovi trebaju biti prevedeni na vaš jezik",
	NOT_ADDED_MOVIES: "Filmovi koji nisu dostupni",
	NOT_ADDED_MOVIES_DESC: "popis filmova bez podnaslova",
	DEFECTED_SUBS: "Oštećeni titlovi",
	DEFECTED_SUBS_DESC: "Titlovi koje treba provjeriti i pregledati",
	NEW_MOVIE_SUBS: "Novi filmski titlovi",
	NEW_SUBS: "Novi titlovi",
	NEW_SUBS_DESC: "Potrebno je da ove titlove pogledate i provjerite",
	NEW_MOVIES: "Novi filmovi",
	NEW_MOVIES_DESC: "Ovi novi filmovi dodani su nedavno",
	YOUR_DOWNLOADS: "Vaša preuzimanja",
	YOUR_DOWNLOADS_DESC: "Titlovi koje ste preuzeli",
	YOUR_EDITS: "Vaše promjene",
	YOUR_EDITS_DESC: "Titlovi koje ste uredili",
	ABOUT_PAGE_TTL: "Kako dobiti najbolji podnaslov iz SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk omogućuje korisnicima sinkronizaciju i popravljanje titlova",
	ABOUT_PAGE_KEYWORDS: "SubAsk, popraviti titl, urediti titl, sinkronizirati titl",
	HOW_TO_FIND_SUBS: "Kako brzo pronaći titlove",
	BY_MOVIE_NAME_TTL: "Korištenje naziva filma",
	BY_MOVIE_FILE_TTL: "Korištenje datoteke filma",
	BY_MOVIE_URL_TTL: "Korištenjem URL-a filma",
	BY_MOVIE_URL_DESC: "Kopirajte URL toka filma u okvir i odaberite jedan od predloženih titlova",
	QUOTES_LISTS_TTL: "SubAsk - Popisi citata filmova",
	QUOTES_LISTS_DESC: "Popis citata u filmovima",
	QUOTES_LISTS_KEYWORDS: "filmski citati",
	MOVIE_QUOTES_TTL: "_MOV_ citati",
	MOVIE_QUOTES_DESC: "Popis citata u _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, citati, omiljeni citati",
	MOVIE_QUOTES_H1: "_MOV_ Movie QUOTES",
	SEARCH_QUOTES: "Traži u navodnicima",
	LIKED_QUOTES_RECENTLY: "Citati su se nedavno svidjeli",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Citati Dobio je prvi Like",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Citati o filmovima trebaju pozornost",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Popularni citati",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Vaše omiljene ponude",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Engleski",
	farsi: "Perzijski",
	hindi: "hindski",
	indonesian: "indonezijski",
	turkish: "turski",
	malayalam: "Malayalam",
	arabic: "arapski",
	vietnamese: "vijetnamski",
	thai: "thai",
	malay: "malajski",
	chinese: "kineski",
	japanese: "japanski",
	hebrew: "Hebrejski",
	bengali: "bengalski",
	croatian: "Hrvatski",
	portuguese: "Portugalski",
	danish: "danski",
	german: "njemački",
	dutch: "Nizozemac",
	korean: "korejski",
	spanish: "Španjolski",
	french: "francuski",
	greek: "grčki",
	swedish: "švedski",
	norwegian: "norveški",
	icelandic: "icelandic",
	italian: "talijanski",
	urdu: "urdu",
	russian: "ruski",
	romanian: "rumunjski",
	pashto: "paštu"
}