module.exports = {
	DONATE:"Menyumbangkan",
	DONATE_DESC:"Kami mengandalkan donasi untuk menjalankan misi kami.",
	MESSAGE:"Pesan",
	YOUR_HELPS:"Bagaimana membantu",
	YOUR_HELPS_DESC:"Kami mengandalkan bantuan Anda untuk meningkatkan subtitle untuk semua bahasa, Anda dapat membantu kami dengan cara berikut",
	SUBASK_I18N_DESC:"Jika Anda menemukan masalah dalam bahasa Anda, Anda dapat membantu kami memperbaikinya di tautan berikut",
	SUBASK_I18N:"Subask dalam bahasa Indonesia",
	CONTRIBUTE:"Edit subtitle, Konfirmasi edit dan Beri peringkat subtitle yang diunduh.",
	SEND_FEEDBACKS:"Kirimkan masukan Anda.",
	ALWAYS_RATE:"Semakin banyak umpan balik yang Anda berikan, semakin banyak hak istimewa yang Anda dapatkan di Subask,",
	SEE_PROFILE:"Lihat profil dan hak istimewa Anda",
	AUTO_TRANS_MSG:"Ini ditambahkan ke antrian untuk diterjemahkan secara otomatis, maka Anda dapat memperbaiki masalah yang telah dibuat oleh terjemahan otomatis.",
	UPLOAD_MSG:"Terima kasih, Ini ditambahkan ke antrean untuk menyelidiki bagaimana kami dapat menggunakannya.",
	NEEDS_LOGIN:"Anda harus login",
	CHECK_EDIT:"Silakan klik di sini untuk memeriksa edit",
	USER_PRIVILEGES: "Hak Istimewa Pengguna",
	RATED_SUBTITLES: "Teks Dinilai",
	APPROVED_EDITS: "Pengeditan yang Disetujui",
	LIKED_QUOTES: "Kutipan yang Disukai",
	REPUTATION: "Reputasi",
	SCORE: "Skor",
	PRIVILEGES: "Hak Istimewa",
	BADGES: "Lencana",
	MOVIES: "Film",
	QUOTES: "Tanda kutip",
	LANGUAGES: "Bahasa",
	EDIT_REQ: "Perlu 7 Unduh Dan Beri Nilai Teks",
	QUOTES_REQ: "Perlu 15 Download Dan Nilai Subtitle",
	UPLOAD_REQ: "Perlu 35 Download Dan Beri Nilai Subtitle",
	APPROVE_REQ: "Perlu 25 Download Dan Beri Nilai Subtitle, 5 Edit",
	AUTOTRAN_REQ: "Perlu 5 Setujui Edit, 10 Edit",
	NEWMOVIE_REQ: "Perlu 20 Setujui Edit",
	TYPE_MOVIE: "Masukkan Nama Film, Url atau File",
	SUB_MISSED: "Subtitle tidak tersedia",
	ADD_UR_SUB: "Tambahkan subtitle Anda untuk film ini",
	CLICK_NXT_BTN: "Atau klik tombol berikut untuk membuat",
	AUTO_TRANS: "Terjemahan baru secara otomatis",
	NOTIFS: "Notifikasi",
	USR_ACTS: "Aktivitas Pengguna",
	LOADING: "Memuat",
	ADD_TXT: "Tambahkan teks",
	DIALOGS: "Dialog",
	H_I: "Tuna rungu",
	NO_H_I: "Teks tunarungu belum dibuat, klik edit untuk membuat",
	SUB_LISTS_DESC: "Daftar beberapa subtitle yang tersedia di SubAsk untuk kontribusi pengguna",
	INCLUDE_H_I: "Apakah Anda mengalami gangguan pendengaran?",
	NOT_INCLUDED: "belum ditambahkan",
	INCLUDED: "telah ditambahkan",
	NO_MATCH: "Tidak ada kecocokan dengan teks pencarian",
	YOUR_SUB: "Jatuhkan atau pilih file subtitle di sini",
	TOP: "Teratas",
	BOTTOM: "Bawah",
	EDIT_TEXTS: "Edit Teks",
	EDIT_BTN_TTL: "Untuk mengubah teks subtitle",
	SYNC: "Sinkronisasi",
	SYNC_TTL: "Untuk mengubah waktu subtitle",
	H_I_TTL: "Ditujukan untuk orang-orang dengan gangguan pendengaran",
	DUALITY: "Subtitle Ganda",
	DUALITY_TTL: "Tonton film dengan dua set subtitle menggunakan subtitle bilingual",
	QUOTES_LIST_TTL: "Daftar beberapa kutipan film",
	MOVIE_LIST_TTL: "Mendaftarkan beberapa subtitle film",
	FEEDBACK_MSG: "Kami akan sangat senang mendengar pikiran, masalah, atau masalah Anda dengan apa pun!",
	ASK_NEW_MOVIE: "Minta untuk menambahkan film baru",
	ASK_MOVIE_DESC: "Silakan temukan film di imdb dan salin alamat tautan ke kotak teks berikut",
	SUBMIT: "Kirimkan",
	NOT_VALID_IMDB_URL: "url imdb yang dimasukkan tidak valid, seharusnya seperti https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Klik untuk menambahkan file film di sini dan membuatnya mudah untuk menemukan subtitle yang paling benar",
	SYNC_BY_RT: "Pilih subtitle berdasarkan kualitas film",
	SYNC_BY_RT_DESC: "Untuk mendapatkan subtitle yang diinginkan, kami menyarankan salah satu solusi di atas. Kalau tidak, Anda dapat menyinkronkan subtitle dengan memilih jenis rilis film.",
	NEW_SYNC: "Buat waktu baru untuk subtitle",
	NEW_SYNC_DESC: "Jika Anda tidak dapat menemukan waktu yang diinginkan dalam daftar tipe rilis Anda dapat membuat waktu subtitle baru sebagai gambar berikut",
	EDIT_ONLINE: "Edit subtitle online",
	EDIT_ONLINE_DESC: "Anda harus menemukan teks terjemahan tidak profesional yang penuh kesalahan; situs ini menyediakan pengeditan yang mudah setiap kalimat dalam subtitle dan Anda dapat membantu meningkatkan subtitle.",
	EDITING: "Bantu mengedit subtitle",
	EDITING_DESC: "Pengeditan dilakukan oleh pengguna atau secara otomatis, tetapi perlu persetujuan pengguna. Anda dapat menemukan daftar subtitle yang telah diedit dan perlu persetujuan di tautan berikut.",
	HOW_TO_FIND_SUBS_DESC: "Menemukan subtitle yang tepat untuk film-film berkualitas berbeda mungkin membutuhkan waktu Anda atau Anda mungkin memiliki versi yang buruk (terjemahan buruk). Berikut ini beberapa cara untuk mengakses subtitle profesional.",
	FIND_SUBS_WAYS: "Tiga cara untuk menemukan subtitle:",
	BY_MOVIE_NAME_DESC: "Ketikkan nama film sebagai gambar berikut di dalam kotak lalu Pilih film untuk pindah ke halaman unduhan subtitle.",
	BY_MOVIE_FILE_DESC: "Anda melihat beberapa subtitle film yang disarankan dengan menggunakan tombol + atau dengan menyeret file film ke kotak.",
	HOME_H1: "Temukan dan sinkronkan subtitle",
	BRING_YOUR_SUB: "Subtitle ini belum ditambahkan oleh pengguna, jika Anda memiliki subtitle yang bagus untuk film ini, seret ke sini untuk mengedit dan menyinkronkan dan membiarkan pengguna lain mengaksesnya",
	HOME_TTL: "SubAsk - Cari Teks",
	HOME_KEYWORDS: "Teks, Sinkronisasi, Edit, Unduh",
	HOME_DESC: "Temukan subtitle yang tepat dan tersinkron dalam film Anda, dan edit secara online",
	TypeMovieQualities: "Tambahkan atau seret file film di sini atau ketik jenis rilis film",
	SEARCH_SUBTITLES: "Cari Subtitle",
	SUB_LISTS: "Daftar Teks",
	SUBTITLE_LANGS: "_MOV_ Terjemahan",
	SUBTITLE_LANGS_DESC: "Daftar semua bahasa terjemahan subtitle _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "terjemahan, _MOV_, bahasa",
	DEFAULT_LANGS: "Bahasa default Anda",
	AVAILABLE_LANGUAGES: "Bahasa Terjemahan yang Tersedia",
	AVAILABLE_LANGUAGES_DESC: "Subtitle film _MOV_ dalam bahasa",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ subtitle dari _MOV_",
	MISSED_LANGUAGES: "Bahasa tidak tersedia",
	MISSED_LANGUAGES_DESC: "Buat subtitle baru untuk _MOV_ dalam bahasa",
	FEEDBACK: "Umpan balik",
	MOVIE_LANG_SUB: "Subtitle Bahasa _LANG_ _MOV_",
	DNLOAD_PAGE_DESC: "Sinkronkan, Edit dan Unduh _MOV_ Subtitle Bahasa _LANG_",
	MOVIE_QUOTES: "Kutipan Terkenal _MOV_",
	DNLOAD_BTN: "Unduh subtitle bahasa _LANG_",
	DOWNLOAD_PAGE_TTL: "Subtitle bahasa _LANG_ untuk _MOV_ dalam _YEAR_",
	DIALOG_HINT: "Ubah dialog ini",
	OTHER_LANGS: "Bahasa lainnya",
	RELEASE_DATE: "Tanggal",
	MOVIE_SCORE: "Menilai",
	SEARCH_HINT: "Cari",
	THANKS: "Terima kasih",
	RE_ADJUST: "Pilih kecepatan Waktu Lain",
	NEED_RE_ADJUST: "Coba subtitle yang diunduh lalu jika tidak disinkronkan atau tidak disinkronkan setelah beberapa menit,",
	RATE_SUB: "Tolong beri kami tanggapan Anda setelah menonton film",
	NOT_ADDED: "Perlu menambahkan subtitle",
	NAME: "Nama",
	OR: "ATAU",
	SIGN_IN: "Masuk",
	SIGN_IN_DESC: "Untuk masuk dan membuat perubahan pada subtitle",
	SIGN_UP: "Daftar",
	SIGN_UP_DESC: "Untuk membuat akun di SubAsk, Silakan daftar",
	SIGN_IN_KEYWORDS: "Login SubAsk",
	SIGN_UP_KEYWORDS: "Pendaftaran SubAsk",
	USERNAME_HAS_TAKEN: "Nama pengguna telah diambil sebelumnya",
	WRONG_PASS: "Nama pengguna atau kata sandi salah",
	EMAIL: "Surel",
	PASSWORD: "Kata sandi",
	SIGN_OUT: "Keluar",
	ABOUT: "tentang",
	NAV_QUOTES: "Tanda kutip",
	NAV_SUBTITLES: "Teks",
	FIND_SUBTITLES: "Temukan Teks",
	FOOTER_DESC: "Tempat untuk membuat dan mengedit subtitle",
	CONTACT_US: "Hubungi kami",
	CONTACT_US_DESC: "Anda dapat menggunakan tautan di bawah untuk membagikan komentar Anda dan mengikuti kami di media sosial",
	SUB_LISTS_TTL: "Daftar Subtitle SubAsk",
	SUB_LISTS_KEYWORDS: "Teks, Daftar, Berkontribusi",
	EDITED_SUBS: "Teks yang diedit",
	EDITED_SUBS_DESC: "Subtitle ini perlu diverifikasi atau diedit",
	NOT_TRANSLATED_SUBS: "Terjemahkan subtitle",
	NOT_TRANSLATED_SUBS_DESC: "Subtitle ini harus diterjemahkan dalam bahasa Anda",
	NOT_ADDED_MOVIES: "Film tidak tersedia",
	NOT_ADDED_MOVIES_DESC: "daftar Film tanpa subtitle",
	DEFECTED_SUBS: "Teks Terjemahan",
	DEFECTED_SUBS_DESC: "Teks yang perlu diperiksa dan ditinjau",
	NEW_MOVIE_SUBS: "Teks Film Baru",
	NEW_SUBS: "Teks Baru",
	NEW_SUBS_DESC: "Subtitle ini membutuhkan Anda untuk melihatnya dan memeriksanya",
	NEW_MOVIES: "Film-film baru",
	NEW_MOVIES_DESC: "Film-film baru ini telah ditambahkan baru-baru ini",
	YOUR_DOWNLOADS: "Unduhan Anda",
	YOUR_DOWNLOADS_DESC: "Terjemahan yang telah Anda unduh",
	YOUR_EDITS: "Suntingan Anda",
	YOUR_EDITS_DESC: "Teks terjemahan yang telah Anda edit",
	ABOUT_PAGE_TTL: "Bagaimana cara mendapatkan subtitle terbaik dari SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk memungkinkan pengguna untuk menyinkronkan dan memperbaiki subtitle",
	ABOUT_PAGE_KEYWORDS: "SubAsk, perbaiki subtitle, edit subtitle, sinkronisasi subtitle",
	HOW_TO_FIND_SUBS: "Cara menemukan subtitle dengan cepat",
	BY_MOVIE_NAME_TTL: "Menggunakan nama film",
	BY_MOVIE_FILE_TTL: "Menggunakan file film",
	BY_MOVIE_URL_TTL: "Menggunakan url film",
	BY_MOVIE_URL_DESC: "Salin url aliran film ke kotak dan pilih salah satu subtitle yang disarankan",
	QUOTES_LISTS_TTL: "SubAsk - Daftar kutipan film",
	QUOTES_LISTS_DESC: "Daftar kutipan dalam film",
	QUOTES_LISTS_KEYWORDS: "kutipan film",
	MOVIE_QUOTES_TTL: "_MOV_ mengutip",
	MOVIE_QUOTES_DESC: "Daftar kutipan di _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, kutipan, kutipan favorit",
	MOVIE_QUOTES_H1: "_MOV_ Kutipan Film",
	SEARCH_QUOTES: "Cari Dalam Kutipan",
	LIKED_QUOTES_RECENTLY: "Harga telah disukai baru-baru ini",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Quotes Got the Like pertama",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Kutipan Film Butuh Perhatian",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Kutipan Populer",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Kutipan Favorit Anda",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Inggris",
	farsi: "farsi",
	hindi: "Hindi",
	indonesian: "bahasa Indonesia",
	turkish: "Turki",
	malayalam: "malayalam",
	arabic: "Arab",
	vietnamese: "Orang Vietnam",
	thai: "Thai",
	malay: "Melayu",
	chinese: "Cina",
	japanese: "Jepang",
	hebrew: "Ibrani",
	bengali: "Benggala",
	croatian: "Kroasia",
	portuguese: "Portugis",
	danish: "Orang Denmark",
	german: "Jerman",
	dutch: "Belanda",
	korean: "Korea",
	spanish: "Spanyol",
	french: "Perancis",
	greek: "Yunani",
	swedish: "Orang Swedia",
	norwegian: "norwegia",
	icelandic: "islandia",
	italian: "Italia",
	urdu: "urdu",
	russian: "Rusia",
	romanian: "Rumania",
	pashto: "pashto"
}