module.exports = {
	DONATE:"Styrkja",
	DONATE_DESC:"Við treystum á framlögum til að framkvæma verkefni okkar.",
	MESSAGE:"Skilaboð",
	YOUR_HELPS:"Hvernig á að hjálpa",
	YOUR_HELPS_DESC:"Við treystum á hjálp þína við að bæta texta fyrir öll tungumál, þú getur hjálpað okkur með eftirfarandi leiðum",
	SUBASK_I18N_DESC:"Ef þú fannst vandamál á þínu tungumáli geturðu hjálpað okkur að laga það með eftirfarandi hlekk",
	SUBASK_I18N:"Subask á ítölsku",
	CONTRIBUTE:"Breyttu texta, staðfestu breytingar og gefðu texta niður.",
	SEND_FEEDBACKS:"Sendu okkur athugasemdir þínar.",
	ALWAYS_RATE:"Því fleiri viðbrögð sem þú veitir þeim mun meiri forréttindi sem þú hefur í Subask,",
	SEE_PROFILE:"Sjáðu prófílinn þinn og forréttindi",
	AUTO_TRANS_MSG:"Þessu bætt við biðröð til að verða þýdd sjálfkrafa, þá er hægt að laga vandamálin sem gerð hafa verið með sjálfvirkri þýðingu.",
	UPLOAD_MSG:"Þakka þér fyrir, það bættist í biðröð til að kanna hvernig við getum notað það.",
	NEEDS_LOGIN:"Þú þarft að skrá þig inn",
	CHECK_EDIT:"Vinsamlegast smelltu hér til að athuga breytingu",
	USER_PRIVILEGES: "Sérleyfi notenda",
	RATED_SUBTITLES: "Metnir textar",
	APPROVED_EDITS: "Samþykktar breytingar",
	LIKED_QUOTES: "Líkaði tilvitnanir",
	REPUTATION: "Mannorð",
	SCORE: "Mark",
	PRIVILEGES: "Forréttindi",
	BADGES: "Merkin",
	MOVIES: "Kvikmyndir",
	QUOTES: "Tilvitnanir",
	LANGUAGES: "Tungumál",
	EDIT_REQ: "Þarfir 7 að hlaða niður og gefa einkennum undirverurnar",
	QUOTES_REQ: "Þarfir 15 að hlaða niður og gefa einkennum undirverurnar",
	UPLOAD_REQ: "Þarfir 35 að hlaða niður og gefa einkennum undirverurnar",
	APPROVE_REQ: "Þarfir 25 að hlaða niður og gefa einkunnum, 5 Breyta",
	AUTOTRAN_REQ: "Þarfir 5 Samþykkja Breyta, 10 Breyta",
	NEWMOVIE_REQ: "Þarfir 20 Samþykkja Breyta",
	TYPE_MOVIE: "Sláðu inn heiti kvikmyndar, slóð eða skrá",
	SUB_MISSED: "Undirtitillinn er ekki tiltækur",
	ADD_UR_SUB: "Bættu við texta þínum fyrir þessa kvikmynd",
	CLICK_NXT_BTN: "Eða smelltu á eftirfarandi hnapp til að búa til",
	AUTO_TRANS: "Sjálfkrafa ný þýðing",
	NOTIFS: "Tilkynningar",
	USR_ACTS: "Starfsemi notenda",
	LOADING: "Hleðsla",
	ADD_TXT: "Bæta við texta",
	DIALOGS: "Samræður",
	H_I: "Heyrnarskertir",
	NO_H_I: "Heyrnarlausir textar hafa ekki búið til, smelltu á breyta til að búa til",
	SUB_LISTS_DESC: "Listar yfir nokkur tiltæk undirtexti í SubAsk fyrir framlag notenda",
	INCLUDE_H_I: "Ertu heyrnarskertur?",
	NOT_INCLUDED: "hefur ekki bætt við",
	INCLUDED: "hefur bætt við",
	NO_MATCH: "Það er ekki samsvörun við leitartexta",
	YOUR_SUB: "Sendu eða veldu textaskil hér",
	TOP: "Efst",
	BOTTOM: "Neðst",
	EDIT_TEXTS: "Breyta texta",
	EDIT_BTN_TTL: "Til að breyta textatexta",
	SYNC: "Samstilling",
	SYNC_TTL: "Til að breyta tímatöku undirtitils",
	H_I_TTL: "Er ætlað fyrir fólk sem er heyrnarskert",
	DUALITY: "Tvöfaldur texti",
	DUALITY_TTL: "Horfðu á kvikmyndir með tveimur settum af textum með því að nota tvítyngd texta",
	QUOTES_LIST_TTL: "Listi yfir nokkrar tilvitnanir í kvikmyndir",
	MOVIE_LIST_TTL: "Listi yfir nokkra skjátexta",
	FEEDBACK_MSG: "Okkur þætti vænt um að heyra hugsanir þínar, áhyggjur eða vandamál varðandi hvað sem er!",
	ASK_NEW_MOVIE: "Biðjið um að bæta við nýrri kvikmynd",
	ASK_MOVIE_DESC: "Vinsamlegast finndu myndina á imdb og afritaðu heimilisfang hlekksins í eftirfarandi textbox",
	SUBMIT: "Sendu inn",
	NOT_VALID_IMDB_URL: "slóðin á imdb url er ekki gild ætti hún að vera eins og https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Smelltu til að bæta við kvikmyndaskrá hér og gera það auðvelt að finna réttan undirtitil",
	SYNC_BY_RT: "Veldu texti sem byggir á kvikmyndagæðum",
	SYNC_BY_RT_DESC: "Til að fá viðeigandi undirtitil mælum við með einni af ofangreindum lausnum. Annars geturðu samstillt undirtitilinn með því að velja gerð kvikmyndar.",
	NEW_SYNC: "Búðu til nýja tímasetningu fyrir undirtitil",
	NEW_SYNC_DESC: "Ef þú finnur ekki viðeigandi tímasetningu á listanum yfir útgáfutegundir geturðu búið til nýjan tímasetningartímabil sem eftirfarandi mynd",
	EDIT_ONLINE: "Breyta textum á netinu",
	EDIT_ONLINE_DESC: "Þú hlýtur að hafa lent í ófaglegum textum sem eru fullir af villum; á þessari síðu er auðvelt að breyta hverri setningu í textum og þú getur hjálpað til við að bæta texta.",
	EDITING: "Hjálpaðu til við að breyta textum",
	EDITING_DESC: "Breytingar eru gerðar af notendum eða sjálfkrafa en það þarf samþykki notenda. Þú getur fundið lista yfir texti sem hefur verið breytt og þarfnast samþykkis á eftirfarandi tengli.",
	HOW_TO_FIND_SUBS_DESC: "Að finna rétta undirtitil fyrir kvikmyndir í mismunandi gæðum getur tekið tíma þinn eða þú gætir haft slæma (lélega þýðingu) útgáfu. Hér eru nokkrar leiðir til að fá aðgang að faglegum textum.",
	FIND_SUBS_WAYS: "Þrjár leiðir til að finna undirtitil:",
	BY_MOVIE_NAME_DESC: "Sláðu inn heiti kvikmyndarinnar sem eftirfarandi mynd í reitinn og veldu síðan kvikmyndina sem á að fara á niðurhalssíðu textans.",
	BY_MOVIE_FILE_DESC: "Þú sérð nokkrar undirtektir á kvikmyndum með því að nota + hnappinn eða með því að draga kvikmyndaskrána í reitinn.",
	HOME_H1: "Finndu og samstilltu texta",
	BRING_YOUR_SUB: "Þessi texti hefur ekki verið bætt við af notendum ennþá, ef þú ert með góðan undirtitil fyrir þessa kvikmynd, dragðu hana hingað til að breyta og samstilla og láta aðra notendur fá aðgang að henni",
	HOME_TTL: "SubAsk - Leitartextar",
	HOME_KEYWORDS: "Undirtitlar, samstillt, breytt, niðurhal",
	HOME_DESC: "Finndu rétta og samstillta undirtitil í myndinni þinni og breyttu þeim á netinu",
	TypeMovieQualities: "Bættu við eða dragðu kvikmyndaskrá hingað eða skrifaðu gerð kvikmyndarinnar",
	SEARCH_SUBTITLES: "Leitartexti",
	SUB_LISTS: "Listi yfir texti",
	SUBTITLE_LANGS: "_MOV_ Þýðingar",
	SUBTITLE_LANGS_DESC: "Listi yfir öll þýdd tungumál _MOV_ undirtitils",
	SUBTITLE_LANGS_KEYWORDS: "þýðingar, _MOV_, tungumál",
	DEFAULT_LANGS: "Sjálfgefið tungumál",
	AVAILABLE_LANGUAGES: "Tungumál texta í boði",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ texti kvikmyndar á tungumáli",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ texti _MOV_",
	MISSED_LANGUAGES: "Tungumál sem ekki eru tiltæk",
	MISSED_LANGUAGES_DESC: "Búðu til nýjan undirtitil fyrir _MOV_ á tungumálinu",
	FEEDBACK: "Endurgjöf",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ texti",
	DNLOAD_PAGE_DESC: "Samstilla, breyta og hlaða niður _MOV_ _LANG_ texta",
	MOVIE_QUOTES: "Frægar tilvitnanir í _MOV_",
	DNLOAD_BTN: "Sæktu _LANG_ texta",
	DOWNLOAD_PAGE_TTL: "_LANG_ texti fyrir _MOV_ í _YEAR_",
	DIALOG_HINT: "Breyta þessum glugga",
	OTHER_LANGS: "Önnur tungumál",
	RELEASE_DATE: "Dagsetning",
	MOVIE_SCORE: "Verð",
	SEARCH_HINT: "Leitaðu",
	THANKS: "Þakka þér fyrir",
	RE_ADJUST: "Veldu annan tímahraða",
	NEED_RE_ADJUST: "Prófaðu að hlaða niður undirtitilinn ef hann er ekki samstilltur eða hann verður samstilltur eftir nokkrar mínútur,",
	RATE_SUB: "Vinsamlegast gefðu athugasemdir þínar eftir að hafa horft á kvikmynd",
	NOT_ADDED: "Þarf að bæta við undirtitli",
	NAME: "Nafn",
	OR: "EÐA",
	SIGN_IN: "Skráðu þig inn",
	SIGN_IN_DESC: "Til að skrá þig inn og gera breytingar á textum",
	SIGN_UP: "Skráðu þig",
	SIGN_UP_DESC: "Til að stofna reikning á SubAsk, vinsamlegast skráðu þig",
	SIGN_IN_KEYWORDS: "SubAsk innskráning",
	SIGN_UP_KEYWORDS: "SubAsk skráning",
	USERNAME_HAS_TAKEN: "Notandanafn hefur verið tekið áður",
	WRONG_PASS: "Notandanafn eða lykilorð er rangt",
	EMAIL: "Netfang",
	PASSWORD: "Lykilorð",
	SIGN_OUT: "Útskrá",
	ABOUT: "um",
	NAV_QUOTES: "Tilvitnanir",
	NAV_SUBTITLES: "Undirtitlar",
	FIND_SUBTITLES: "Finndu texti",
	FOOTER_DESC: "Staður til að búa til og breyta textum",
	CONTACT_US: "Hafðu samband við okkur",
	CONTACT_US_DESC: "Þú getur notað krækjurnar hér að neðan til að deila athugasemdum þínum og fylgja okkur á samfélagsmiðlum",
	SUB_LISTS_TTL: "SubAsk Listi yfir texti",
	SUB_LISTS_KEYWORDS: "Undirtitlar, Listi, Stuðla",
	EDITED_SUBS: "Breyttum textum",
	EDITED_SUBS_DESC: "Það þarf að staðfesta eða breyta þessum textum",
	NOT_TRANSLATED_SUBS: "Þýða texti",
	NOT_TRANSLATED_SUBS_DESC: "Þessa skjátexta ætti að þýða á þínu tungumáli",
	NOT_ADDED_MOVIES: "Kvikmyndir sem ekki eru fáanlegar",
	NOT_ADDED_MOVIES_DESC: "lista yfir Kvikmyndir án texta",
	DEFECTED_SUBS: "Gallaðir textar",
	DEFECTED_SUBS_DESC: "Texti sem þarf að athuga og fara yfir",
	NEW_MOVIE_SUBS: "Nýir kvikmyndatextar",
	NEW_SUBS: "Nýir textar",
	NEW_SUBS_DESC: "Þessir textar þurfa að kíkja á þig og skoða þær",
	NEW_MOVIES: "Nýjar kvikmyndir",
	NEW_MOVIES_DESC: "Þessum nýju kvikmyndum hefur verið bætt við að undanförnu",
	YOUR_DOWNLOADS: "Niðurhal þitt",
	YOUR_DOWNLOADS_DESC: "Texti sem þú hefur hlaðið niður",
	YOUR_EDITS: "Breytingar þínar",
	YOUR_EDITS_DESC: "Texti sem þú hefur breytt",
	ABOUT_PAGE_TTL: "Hvernig á að fá besta undirtitilinn frá SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk gerir notendum kleift að samstilla og laga textun",
	ABOUT_PAGE_KEYWORDS: "SubAsk, laga undirtitil, breyta undirtitli, samstilla undirtitil",
	HOW_TO_FIND_SUBS: "Hvernig á að finna undirtitla fljótt",
	BY_MOVIE_NAME_TTL: "Notkun kvikmyndanafnsins",
	BY_MOVIE_FILE_TTL: "Notkun kvikmyndaskrárinnar",
	BY_MOVIE_URL_TTL: "Með því að nota vefslóð kvikmyndarinnar",
	BY_MOVIE_URL_DESC: "Afritaðu straumslóð kvikmyndarinnar í reitinn og veldu einn af fyrirhuguðum textum",
	QUOTES_LISTS_TTL: "SubAsk - Tilvitnanir í kvikmyndir",
	QUOTES_LISTS_DESC: "Listi yfir tilvitnanir í kvikmyndir",
	QUOTES_LISTS_KEYWORDS: "tilvitnanir í kvikmyndir",
	MOVIE_QUOTES_TTL: "_MOV_ tilvitnanir",
	MOVIE_QUOTES_DESC: "Tilvitnunarlisti í _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, tilvitnanir, uppáhaldstilvitnanir",
	MOVIE_QUOTES_H1: "_MOV_ Tilvitnanir í kvikmyndir",
	SEARCH_QUOTES: "Leitaðu í tilvitnunum",
	LIKED_QUOTES_RECENTLY: "Tilvitnunum hefur verið líkað undanfarið",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Tilvitnanir Got the First Like",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Tilvitnanir í kvikmyndir þarfnast athygli",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Vinsælar tilvitnanir",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Uppáhalds tilvitnanir þínar",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Enska",
	farsi: "farsi",
	hindi: "hindi",
	indonesian: "indónesísku",
	turkish: "tyrkneska",
	malayalam: "malayalam",
	arabic: "arabíska",
	vietnamese: "víetnamskt",
	thai: "taílensku",
	malay: "malay",
	chinese: "kínverska",
	japanese: "japönsku",
	hebrew: "hebreska",
	bengali: "bengali",
	croatian: "króatíska",
	portuguese: "portúgalska",
	danish: "dönsku",
	german: "þýska, Þjóðverji, þýskur",
	dutch: "hollensk",
	korean: "kóreska",
	spanish: "spænska, spænskt",
	french: "frönsku",
	greek: "gríska",
	swedish: "sænsku",
	norwegian: "norsku",
	icelandic: "íslensku",
	italian: "ítalska",
	urdu: "úrdú",
	russian: "Rússneskt",
	romanian: "rúmenska",
	pashto: "pashto"
}