module.exports = {
	DONATE:"Donare",
	DONATE_DESC:"Contiamo sulle donazioni per portare a termine la nostra missione.",
	MESSAGE:"Messaggio",
	YOUR_HELPS:"Come aiutare",
	YOUR_HELPS_DESC:"Contiamo sul tuo aiuto per migliorare i sottotitoli per tutte le lingue, puoi aiutarci nei seguenti modi",
	SUBASK_I18N_DESC:"Se hai riscontrato un problema nella tua lingua, puoi aiutarci a risolverlo nel seguente link",
	SUBASK_I18N:"Subask in italiano",
	CONTRIBUTE:"Modifica i sottotitoli, Conferma le modifiche e Valuta i sottotitoli scaricati.",
	SEND_FEEDBACKS:"Inviaci i tuoi commenti.",
	ALWAYS_RATE: "Più feedback dai, più privilegi avresti in Subask,",
	SEE_PROFILE: "Visualizza il tuo profilo e i tuoi privilegi",
	AUTO_TRANS_MSG: "Viene aggiunto a una coda per essere tradotto automaticamente, quindi puoi risolvere i problemi che sono stati creati dalla traduzione automatica.",
	UPLOAD_MSG: "Grazie, è stato aggiunto a una coda per indagare su come possiamo usarlo.",
	NEEDS_LOGIN: "Devi prima effettuare il login",
	USER_PRIVILEGES: "Privilegi utente",
	RATED_SUBTITLES: "Sottotitoli classificati",
	APPROVED_EDITS: "Modifiche approvate",
	LIKED_QUOTES: "Citazioni piaciute",
	REPUTATION: "Reputazione",
	SCORE: "Punto",
	PRIVILEGES: "Privilegi",
	BADGES: "Distintivi",
	Movies: "Film",
	QUOTES: "Citazioni",
	LANGUAGES: "Le lingue",
	EDIT_REQ: "Richiede 7 Scarica e valuta i sottotitoli",
	QUOTES_REQ: "Richiede 15 Scarica e valuta i sottotitoli",
	UPLOAD_REQ: "Richiede 35 Scarica e valuta i sottotitoli",
	APPROVE_REQ: "Richiede 25 Scarica e valuta i sottotitoli, 5 Modifica",
	AUTOTRAN_REQ: "Richiede 5 Approva Modifica, 10 Modifica",
	NEWMOVIE_REQ: "Richiede 20 Approva Modifica",
	TYPE_MOVIE: "Inserisci il nome del film, l'URL o il file",
	SUB_MISSED: "Il sottotitolo non è disponibile",
	ADD_UR_SUB: "Aggiungi il tuo sottotitolo per questo film",
	CLICK_NXT_BTN: "Oppure fare clic sul pulsante seguente per creare",
	AUTO_TRANS: "Automaticamente una nuova traduzione",
	NOTIFS: "Notifiche",
	USR_ACTS: "Attività degli utenti",
	LOADING: "Caricamento in corso",
	ADD_TXT: "Aggiungi testo",
	DIALOGS: "Dialoghi",
	H_I: "Compromissione dell'udito",
	NO_H_I: "I testi sordi non sono stati creati, fare clic su modifica per creare",
	SUB_LISTS_DESC: "Modificato, aggiunto di recente, tradotto e alcuni altri elenchi di sottotitoli",
	INCLUDE_H_I: "Hai problemi di udito?",
	NOT_INCLUDED: "Non ha aggiunto",
	INCLUDED: "Ha aggiunto",
	NO_MATCH: "Non c'è alcuna corrispondenza con il testo di ricerca",
	YOUR_SUB: "Trascina o seleziona un file di sottotitoli qui",
	TOP: "Superiore",
	BOTTOM: "Parte inferiore",
	EDIT_TEXTS: "Modifica testi",
	EDIT_BTN_TTL: "Per modificare i testi dei sottotitoli",
	SYNC: "Sincronizzazione",
	SYNC_TTL: "Per modificare la tempistica dei sottotitoli",
	H_I_TTL: "Sono destinati a persone con problemi di udito",
	DUALITY: "Doppio sottotitolo",
	DUALITY_TTL: "Guarda film con due serie di sottotitoli utilizzando sottotitoli bilingue",
	QUOTES_LIST_TTL: "Elenchi di citazioni di film",
	MOVIE_LIST_TTL: "Elenchi dei sottotitoli dei film",
	CHECK_EDIT: "C'è una nuova edizione per questo sottotitolo, vuoi controllarlo?",
	FEEDBACK_MSG: "Ci piacerebbe sentire i tuoi pensieri, preoccupazioni o problemi con qualsiasi cosa",
	ASK_NEW_MOVIE: "Chiedi di aggiungere un nuovo film",
	ASK_MOVIE_DESC: "Trova il film in imdb e copia l'indirizzo del link nella seguente casella di testo",
	SUBMIT: "Invia",
	NOT_VALID_IMDB_URL: "l'URL imdb inserito non è valido dovrebbe essere come https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Fare clic per aggiungere qui il file del film e trovare facilmente il sottotitolo più corretto",
	SYNC_BY_RT: "Seleziona i sottotitoli in base alla qualità del film",
	SYNC_BY_RT_DESC: "Per ottenere il sottotitolo desiderato, suggeriamo una delle soluzioni sopra. Altrimenti puoi sincronizzare i sottotitoli selezionando il tipo di rilascio del film.",
	NEW_SYNC: "Crea una nuova tempistica per i sottotitoli",
	NEW_SYNC_DESC: "Se non riesci a trovare il tempo desiderato nell'elenco dei tipi di rilascio, puoi creare un nuovo tempo per i sottotitoli come nell'immagine seguente",
	EDIT_ONLINE: "Modifica i sottotitoli online",
	EDIT_ONLINE_DESC: "Devi aver riscontrato sottotitoli non professionali pieni di errori; questo sito fornisce un facile editing di ogni frase nei sottotitoli e puoi aiutare a migliorare i sottotitoli.",
	EDITING: "Aiuta a modificare i sottotitoli",
	EDITING_DESC: "Le modifiche vengono eseguite dagli utenti o automaticamente, ma è necessaria l'approvazione degli utenti. Puoi trovare un elenco di sottotitoli che sono stati modificati e che richiedono l'approvazione al seguente link.",
	HOW_TO_FIND_SUBS_DESC: "Trovare il sottotitolo giusto per film di qualità diversa potrebbe richiedere del tempo o potresti avere una versione scadente (traduzione scadente). Ecco alcuni modi per accedere ai sottotitoli professionali.",
	FIND_SUBS_WAYS: "Tre modi per trovare un sottotitolo:",
	BY_MOVIE_NAME_DESC: "Digita il nome del film come nell'immagine seguente nella casella, quindi seleziona il film per passare alla pagina di download dei sottotitoli.",
	BY_MOVIE_FILE_DESC: "Puoi vedere alcuni sottotitoli di film suggeriti usando il pulsante + o trascinando il file del film nella casella.",
	HOME_H1: "Trova e sincronizza i sottotitoli",
	BRING_YOUR_SUB: "Questo sottotitolo non è stato ancora aggiunto dagli utenti, se hai un buon sottotitolo per questo film, trascinalo qui per modificarlo e sincronizzarlo e consentire ad altri utenti di accedervi",
	HOME_TTL: "SubAsk - Cerca sottotitoli",
	HOME_KEYWORDS: "Sottotitoli, sincronizzazione, modifica, download",
	HOME_DESC: "Trova i sottotitoli giusti e sincronizzati per il tuo film e ti consente di modificarli e migliorarli online",
	TypeMovieQualities: "Aggiungi o trascina il file del filmato qui o digita il tipo di rilascio del film",
	SEARCH_SUBTITLES: "Cerca sottotitoli",
	SUB_LISTS: "Elenco dei sottotitoli",
	SUBTITLE_LANGS: "_MOV_ Traduzioni",
	SUBTITLE_LANGS_DESC: "Elenco di tutte le lingue tradotte dei sottotitoli _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "traduzioni, _MOV_, lingue",
	DEFAULT_LANGS: "La tua lingua predefinita",
	AVAILABLE_LANGUAGES: "Lingue sottotitoli disponibili",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ sottotitoli del film in lingua",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ sottotitolo di _MOV_",
	MISSED_LANGUAGES: "Lingue non disponibili",
	MISSED_LANGUAGES_DESC: "Crea un nuovo sottotitolo per _MOV_ nella lingua",
	FEEDBACK: "Risposta",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ Sottotitolo",
	DNLOAD_PAGE_DESC: "Sincronizza, modifica e scarica _MOV_ _LANG_ Sottotitoli",
	MOVIE_QUOTES: "Citazioni famose di _MOV_",
	DNLOAD_BTN: "Scarica il sottotitolo in _LANG_",
	DOWNLOAD_PAGE_TTL: "Sottotitoli in _LANG_ per _MOV_ in _YEAR_",
	DIALOG_HINT: "Cambia questa finestra di dialogo",
	OTHER_LANGS: "Altre lingue",
	RELEASE_DATE: "Data",
	MOVIE_SCORE: "Vota",
	SEARCH_HINT: "Ricerca",
	THANKS: "Grazie",
	RE_ADJUST: "Selezionare Another Time speed",
	NEED_RE_ADJUST: "Prova il sottotitolo scaricato, quindi se non è sincronizzato o non viene sincronizzato dopo pochi minuti,",
	RATE_SUB: "Si prega di valutare il sottotitolo dopo aver visto il film",
	NOT_ADDED: "Ha bisogno di aggiungere un sottotitolo",
	NAME: "Nome",
	OR: "O",
	SIGN_IN: "Registrati",
	SIGN_IN_DESC: "Per effettuare il login e apportare modifiche ai sottotitoli",
	SIGN_UP: "Iscriviti",
	SIGN_UP_DESC: "Per creare un account su SubAsk, registrati",
	SIGN_IN_KEYWORDS: "SubAsk login",
	SIGN_UP_KEYWORDS: "SubAsk registrazione",
	USERNAME_HAS_TAKEN: "Il nome utente è già stato utilizzato",
	WRONG_PASS: "Nome utente o password non sono corretti",
	EMAIL: "E-mail",
	PASSWORD: "Parola d'ordine",
	SIGN_OUT: "Disconnessione",
	ABOUT: "di",
	NAV_QUOTES: "Citazioni",
	NAV_SUBTITLES: "Sottotitoli",
	FIND_SUBTITLES: "Trova i sottotitoli",
	FOOTER_DESC: "Un luogo per creare, sincronizzare e modificare i sottotitoli",
	CONTACT_US: "Contattaci",
	CONTACT_US_DESC: "Puoi utilizzare i link sottostanti per condividere i tuoi commenti e seguirci sui social media",
	SUB_LISTS_TTL: "SubAsk Elenchi di sottotitoli",
	SUB_LISTS_KEYWORDS: "Sottotitoli, Elenco, Contributo",
	EDITED_SUBS: "Sottotitoli modificati",
	EDITED_SUBS_DESC: "Questi sottotitoli devono essere verificati o modificati",
	NOT_TRANSLATED_SUBS: "Traduci i sottotitoli",
	NOT_TRANSLATED_SUBS_DESC: "Questi sottotitoli dovrebbero essere tradotti nella tua lingua",
	NOT_ADDED_MOVIES: "Film non disponibili",
	NOT_ADDED_MOVIES_DESC: "elenco di film senza sottotitoli",
	DEFECTED_SUBS: "Sottotitoli difettosi",
	DEFECTED_SUBS_DESC: "Sottotitoli che devono essere controllati e rivisti",
	NEW_MOVIE_SUBS: "Sottotitoli per nuovi film",
	NEW_SUBS: "Nuovi sottotitoli",
	NEW_SUBS_DESC: "Questi sottotitoli richiedono che tu li dia un'occhiata e li controlli",
	NEW_MOVIES: "Nuovi film",
	NEW_MOVIES_DESC: "Questi nuovi film sono stati aggiunti di recente",
	YOUR_DOWNLOADS: "I tuoi download",
	YOUR_DOWNLOADS_DESC: "Sottotitoli che hai scaricato",
	YOUR_EDITS: "Le tue modifiche",
	YOUR_EDITS_DESC: "Sottotitoli che hai modificato",
	ABOUT_PAGE_TTL: "Come ottenere i migliori sottotitoli da SubAsk?",
	ABOUT_PAGE_DESC: "In questa pagina ti mostreremo come sincronizzare i sottotitoli con il tuo film e modificarli.",
	ABOUT_PAGE_KEYWORDS: "SubAsk, correggi i sottotitoli, modifica i sottotitoli, sincronizza i sottotitoli",
	HOW_TO_FIND_SUBS: "Come trovare rapidamente i sottotitoli",
	BY_MOVIE_NAME_TTL: "Usando il nome del film",
	BY_MOVIE_FILE_TTL: "Utilizzando il file del filmato",
	BY_MOVIE_URL_TTL: "Utilizzando l'URL del film",
	BY_MOVIE_URL_DESC: "Copia l'URL dello streaming del film nella casella e seleziona uno dei sottotitoli suggeriti",
	QUOTES_LISTS_TTL: "SubAsk - Elenchi di citazioni di film",
	QUOTES_LISTS_DESC: "Elenco di citazioni nei film",
	QUOTES_LISTS_KEYWORDS: "citazioni di film",
	MOVIE_QUOTES_TTL: "_MOV_ citazioni",
	MOVIE_QUOTES_DESC: "Elenco citazioni in _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, citazioni, citazioni preferite",
	MOVIE_QUOTES_H1: "_MOV_ Movie Quotes",
	SEARCH_QUOTES: "Cerca tra citazioni",
	LIKED_QUOTES_RECENTLY: "Le citazioni sono piaciute di recente",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Citazioni ha ottenuto il primo Mi piace",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Le citazioni sui film hanno bisogno di attenzione",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Citazioni popolari",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Le tue citazioni preferite",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "inglese",
	farsi: "farsi",
	hindi: "hindi",
	indonesian: "indonesiano",
	turkish: "Turco",
	malayalam: "malayalam",
	arabic: "Arabo",
	vietnamese: "vietnamita",
	thai: "tailandese",
	malay: "malese",
	chinese: "Cinese",
	japanese: "giapponese",
	hebrew: "ebraico",
	bengali: "bengalese",
	croatian: "croato",
	portuguese: "portoghese",
	danish: "danese",
	german: "Tedesco",
	dutch: "olandese",
	korean: "coreano",
	spanish: "spagnolo",
	french: "francese",
	greek: "greco",
	swedish: "svedese",
	norwegian: "norvegese",
	icelandic: "islandese",
	italian: "italiano",
	urdu: "urdu",
	russian: "russo",
	romanian: "rumeno",
	pashto: "pashto"
}
