module.exports = {
	DONATE:"寄付",
	DONATE_DESC:"私たちは使命を遂行するために寄付に依存しています。",
	MESSAGE:"メッセージ",
	YOUR_HELPS:"助ける方法",
	YOUR_HELPS_DESC:"私たちはすべての言語の字幕を改善するためにあなたの助けに頼っています、あなたは次の方法で私たちを助けることができます",
	SUBASK_I18N_DESC:"あなたの言語で問題を見つけた場合は、次のリンクでそれを修正するのを手伝うことができます",
	SUBASK_I18N:"韓国語のSubask",
	CONTRIBUTE:"字幕を編集し、編集を確認し、ダウンロードした字幕を評価します。",
	SEND_FEEDBACKS:"フィードバックをお送りください。",
	ALWAYS_RATE:"フィードバックが多ければ多いほど、Subaskで持つ特権が増えます。",
	SEE_PROFILE:"あなたのプロフィールと特権を見る",
	AUTO_TRANS_MSG:"自動的に翻訳されるようにキューに追加され、自動翻訳によって発生した問題を修正できます。",
	UPLOAD_MSG:"ありがとう、それは私たちがそれをどのように使うことができるかを調査するためにキューに追加されました。",
	NEEDS_LOGIN:"ログインする必要があります",
	CHECK_EDIT:"編集を確認するには、ここをクリックしてください",
	USER_PRIVILEGES: "ユーザー権限",
	RATED_SUBTITLES: "定格字幕",
	APPROVED_EDITS: "承認された編集",
	LIKED_QUOTES: "好きな引用",
	REPUTATION: "評判",
	SCORE: "スコア",
	PRIVILEGES: "特権",
	BADGES: "バッジ",
	MOVIES: "映画",
	QUOTES: "引用",
	LANGUAGES: "言語",
	EDIT_REQ: "サブタイルをダウンロードして評価する必要があります",
	QUOTES_REQ: "15のダウンロードとサブタイルの評価が必要",
	UPLOAD_REQ: "35のダウンロードとサブタイルの評価が必要",
	APPROVE_REQ: "25のダウンロードとサブタイルの評価、5の編集が必要",
	AUTOTRAN_REQ: "5承認編集、10編集が必要",
	NEWMOVIE_REQ: "20の承認編集が必要",
	TYPE_MOVIE: "映画名、URLまたはファイルを入力してください",
	SUB_MISSED: "字幕はありません",
	ADD_UR_SUB: "この映画の字幕を追加してください",
	CLICK_NXT_BTN: "または、次のボタンをクリックして作成します",
	AUTO_TRANS: "自動的に新しい翻訳",
	NOTIFS: "お知らせ",
	USR_ACTS: "ユーザーの活動",
	LOADING: "読み込み中",
	ADD_TXT: "テキストを追加",
	DIALOGS: "ダイアログ",
	H_I: "聴覚障害者",
	NO_H_I: "聴覚障害者向けテキストは作成されていません。編集するにはクリックして作成してください",
	SUB_LISTS_DESC: "SubAskのユーザー投稿用の利用可能な字幕のリスト",
	INCLUDE_H_I: "聴覚障害はありますか？",
	NOT_INCLUDED: "追加されていません",
	INCLUDED: "追加しました",
	NO_MATCH: "検索テキストと一致するものはありません",
	YOUR_SUB: "ここに字幕ファイルをドロップまたは選択します",
	TOP: "上",
	BOTTOM: "底",
	EDIT_TEXTS: "テキストを編集",
	EDIT_BTN_TTL: "字幕テキストを変更するには",
	SYNC: "同期",
	SYNC_TTL: "字幕のタイミングを変更するには",
	H_I_TTL: "聴覚障害のある方を対象としています",
	DUALITY: "デュアル字幕",
	DUALITY_TTL: "2か国語の字幕を使用して2セットの字幕を含む映画を視聴する",
	QUOTES_LIST_TTL: "映画の引用のリスト",
	MOVIE_LIST_TTL: "映画の字幕のリスト",
	FEEDBACK_MSG: "私たちはあなたの考え、懸念や何かに関する問題を聞いてみたいです！",
	ASK_NEW_MOVIE: "新しい映画を追加するように頼む",
	ASK_MOVIE_DESC: "imdbで映画を見つけ、リンクアドレスを次のテキストボックスにコピーしてください",
	SUBMIT: "参加する",
	NOT_VALID_IMDB_URL: "入力されたimdbのURLは無効です。https：//www.imdb.com/title/tt2106476/？ref_ = tt_sims_ttのようにする必要があります",
	ADD_MOVIE_FILE: "クリックしてここに動画ファイルを追加し、最も適切な字幕を簡単に見つけられるようにします",
	SYNC_BY_RT: "映画の品質に基づいて字幕を選択する",
	SYNC_BY_RT_DESC: "希望の字幕を取得するには、上記の解決策のいずれかをお勧めします。それ以外の場合は、映画のリリースタイプを選択して字幕を同期できます。",
	NEW_SYNC: "字幕の新しいタイミングを作成する",
	NEW_SYNC_DESC: "リリースタイプリストで目的のタイミングが見つからない場合は、次の画像のように新しい字幕タイミングを作成できます",
	EDIT_ONLINE: "オンラインで字幕を編集する",
	EDIT_ONLINE_DESC: "エラーに満ちた専門外の字幕に出会ったことでしょう。このサイトでは、字幕の各文を簡単に編集でき、字幕の改善に役立ちます。",
	EDITING: "字幕の編集を手伝う",
	EDITING_DESC: "編集はユーザーが行うか、自動的に行われますが、ユーザーの承認が必要です。編集済みで承認が必要な字幕のリストは、次のリンクで確認できます。",
	HOW_TO_FIND_SUBS_DESC: "さまざまな品質の映画に適した字幕を見つけるには時間がかかる場合や、悪い（翻訳の悪い）バージョンがある場合があります。ここにプロの字幕にアクセスするいくつかの方法があります。",
	FIND_SUBS_WAYS: "字幕を見つける3つの方法：",
	BY_MOVIE_NAME_DESC: "ボックスに次の画像のように映画名を入力し、映画を選択して字幕ダウンロードページに移動します。",
	BY_MOVIE_FILE_DESC: "+ボタンを使用するか、ムービーファイルをボックスにドラッグすると、おすすめの映画の字幕がいくつか表示されます。",
	HOME_H1: "字幕を見つけて同期する",
	BRING_YOUR_SUB: "この字幕はまだユーザーによって追加されていません。この映画に適した字幕がある場合は、ここにドラッグして編集および同期し、他のユーザーにアクセスを許可してください",
	HOME_TTL: "SubAsk-字幕を検索",
	HOME_KEYWORDS: "字幕、同期、編集、ダウンロード",
	HOME_DESC: "ムービーで適切な同期字幕を見つけて、オンラインで編集します",
	TypeMovieQualities: "ここにムービーファイルを追加またはドラッグするか、ムービーリリースタイプを入力します",
	SEARCH_SUBTITLES: "字幕を検索",
	SUB_LISTS: "字幕リスト",
	SUBTITLE_LANGS: "_MOV_翻訳",
	SUBTITLE_LANGS_DESC: "_MOV_字幕のすべての翻訳言語のリスト",
	SUBTITLE_LANGS_KEYWORDS: "翻訳、_MOV_、言語",
	DEFAULT_LANGS: "デフォルトの言語",
	AVAILABLE_LANGUAGES: "利用可能な字幕言語",
	AVAILABLE_LANGUAGES_DESC: "_MOV_言語の映画の字幕",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ _MOV_のサブタイトル",
	MISSED_LANGUAGES: "利用できない言語",
	MISSED_LANGUAGES_DESC: "言語で_MOV_の新しいサブタイトルを作成",
	FEEDBACK: "フィードバック",
	MOVIE_LANG_SUB: "_MOV_ _LANG_字幕",
	DNLOAD_PAGE_DESC: "_MOV_ _LANG_字幕の同期、編集、ダウンロード",
	MOVIE_QUOTES: "_MOV_の有名な引用",
	DNLOAD_BTN: "_LANG_字幕をダウンロード",
	DOWNLOAD_PAGE_TTL: "_YEAR_の_MOV_の_LANG_字幕",
	DIALOG_HINT: "このダイアログを変更",
	OTHER_LANGS: "他の言語",
	RELEASE_DATE: "日付",
	MOVIE_SCORE: "割合",
	SEARCH_HINT: "調べる",
	THANKS: "ありがとうございました",
	RE_ADJUST: "別の時間速度を選択",
	NEED_RE_ADJUST: "ダウンロードした字幕を試してみてください。同期されていない場合、または数分後に同期が解除される場合は、",
	RATE_SUB: "映画を見た後、フィードバックをお願いします",
	NOT_ADDED: "字幕を追加する必要があります",
	NAME: "名前",
	OR: "または",
	SIGN_IN: "サインイン",
	SIGN_IN_DESC: "ログインして字幕を変更するには",
	SIGN_UP: "サインアップ",
	SIGN_UP_DESC: "SubAskにアカウントを作成するには、サインアップしてください",
	SIGN_IN_KEYWORDS: "SubAskログイン",
	SIGN_UP_KEYWORDS: "SubAskサインアップ",
	USERNAME_HAS_TAKEN: "以前にユーザー名を取得しました",
	WRONG_PASS: "ユーザー名かパスワードが間違っています",
	EMAIL: "Eメール",
	PASSWORD: "パスワード",
	SIGN_OUT: "サインアウト",
	ABOUT: "約",
	NAV_QUOTES: "引用",
	NAV_SUBTITLES: "字幕",
	FIND_SUBTITLES: "字幕を探す",
	FOOTER_DESC: "字幕を作成および編集する場所",
	CONTACT_US: "お問い合わせ",
	CONTACT_US_DESC: "以下のリンクを使用してコメントを共有し、ソーシャルメディアでフォローしてください",
	SUB_LISTS_TTL: "SubAsk字幕リスト",
	SUB_LISTS_KEYWORDS: "字幕、リスト、投稿",
	EDITED_SUBS: "編集された字幕",
	EDITED_SUBS_DESC: "これらの字幕は確認または編集する必要があります",
	NOT_TRANSLATED_SUBS: "字幕を翻訳する",
	NOT_TRANSLATED_SUBS_DESC: "これらの字幕はあなたの言語に翻訳されるべきです",
	NOT_ADDED_MOVIES: "利用できない映画",
	NOT_ADDED_MOVIES_DESC: "字幕なしの映画のリスト",
	DEFECTED_SUBS: "欠陥字幕",
	DEFECTED_SUBS_DESC: "チェックして確認する必要がある字幕",
	NEW_MOVIE_SUBS: "新しい映画の字幕",
	NEW_SUBS: "新しい字幕",
	NEW_SUBS_DESC: "これらの字幕を見るには、それらを確認する必要があります",
	NEW_MOVIES: "新しい映画",
	NEW_MOVIES_DESC: "これらの新しい映画は最近追加されました",
	YOUR_DOWNLOADS: "あなたのダウンロード",
	YOUR_DOWNLOADS_DESC: "ダウンロードした字幕",
	YOUR_EDITS: "あなたの編集",
	YOUR_EDITS_DESC: "編集した字幕",
	ABOUT_PAGE_TTL: "SubAskから最高の字幕を取得する方法は？",
	ABOUT_PAGE_DESC: "SubAskを使用すると、ユーザーは字幕を同期および修正できます",
	ABOUT_PAGE_KEYWORDS: "SubAsk、字幕の修正、字幕の編集、字幕の同期",
	HOW_TO_FIND_SUBS: "字幕をすばやく見つける方法",
	BY_MOVIE_NAME_TTL: "映画名を使用する",
	BY_MOVIE_FILE_TTL: "ムービーファイルを使用する",
	BY_MOVIE_URL_TTL: "映画のURLを使用する",
	BY_MOVIE_URL_DESC: "ムービーのストリームURLをボックスにコピーし、推奨される字幕のいずれかを選択します",
	QUOTES_LISTS_TTL: "SubAsk-映画の引用リスト",
	QUOTES_LISTS_DESC: "映画の引用のリスト",
	QUOTES_LISTS_KEYWORDS: "映画の引用",
	MOVIE_QUOTES_TTL: "_MOV_引用符",
	MOVIE_QUOTES_DESC: "_MOV_の引用リスト",
	MOVIE_QUOTES_KEYWORDS: "_MOV_、引用符、お気に入りの引用符",
	MOVIE_QUOTES_H1: "_MOV_映画の引用",
	SEARCH_QUOTES: "引用で検索",
	LIKED_QUOTES_RECENTLY: "引用は最近好かれています",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "引用符が最初に取得しました",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "映画の引用には注意が必要",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "人気の引用",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "お気に入りの引用",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "英語",
	farsi: "ペルシア語",
	hindi: "ヒンディー語",
	indonesian: "インドネシア人",
	turkish: "トルコ人",
	malayalam: "マラヤーラム語",
	arabic: "アラビア語",
	vietnamese: "ベトナム人",
	thai: "タイ人",
	malay: "マレー語",
	chinese: "中国語",
	japanese: "日本語",
	hebrew: "ヘブライ語",
	bengali: "ベンガル語",
	croatian: "クロアチア人",
	portuguese: "ポルトガル語",
	danish: "デンマーク人",
	german: "ドイツ人",
	dutch: "オランダの",
	korean: "韓国語",
	spanish: "スペイン語",
	french: "フランス語",
	greek: "ギリシャ語",
	swedish: "スウェーデンの",
	norwegian: "ノルウェー人",
	icelandic: "アイスランドの",
	italian: "イタリア語",
	urdu: "ウルドゥー語",
	russian: "ロシア",
	romanian: "ルーマニア語",
	pashto: "パシュトゥー語"
}