module.exports = {
	DONATE:"기부",
	DONATE_DESC:"우리는 사명을 수행하기 위해 기부금에 의존합니다.",
	MESSAGE:"메시지",
	YOUR_HELPS:"돕는 방법",
	YOUR_HELPS_DESC:"우리는 모든 언어의 자막을 향상시키기 위해 귀하의 도움에 의존하며 다음과 같은 방법으로 우리를 도울 수 있습니다",
	SUBASK_I18N_DESC:"귀하의 언어로 된 문제를 발견 한 경우 다음 링크에서 문제를 해결하도록 도울 수 있습니다.",
	SUBASK_I18N:"Subask에서 한국어",
	CONTRIBUTE:"자막 편집, 편집 확인 및 다운로드 한 자막 등급 지정.",
	SEND_FEEDBACKS:"피드백을 보내주세요.",
	ALWAYS_RATE:"더 많은 피드백을 제공할수록 Subask에서 더 많은 권한을 갖게됩니다.",
	SEE_PROFILE:"프로필 및 권한보기",
	AUTO_TRANS_MSG:"자동 번역을 위해 대기열에 추가하면 자동 번역으로 인해 발생한 문제를 수정할 수 있습니다.",
	UPLOAD_MSG:"감사합니다. 사용 방법을 조사하기 위해 대기열에 추가되었습니다.",
	NEEDS_LOGIN:"로그인이 필요합니다",
	CHECK_EDIT:"편집 내용을 확인하려면 여기를 클릭하십시오",
	USER_PRIVILEGES: "사용자 권한",
	RATED_SUBTITLES: "정격 자막",
	APPROVED_EDITS: "승인 된 편집",
	LIKED_QUOTES: "좋아요 인용구",
	REPUTATION: "평판",
	SCORE: "점수",
	PRIVILEGES: "특권",
	BADGES: "배지",
	MOVIES: "영화 산업",
	QUOTES: "인용 부호",
	LANGUAGES: "언어",
	EDIT_REQ: "7 다운로드 및 하위 항목 평가 필요",
	QUOTES_REQ: "15 다운로드 및 하위 항목 평가 필요",
	UPLOAD_REQ: "35 다운로드 및 자막 평가 필요",
	APPROVE_REQ: "자막 25 다운로드 및 평가 필요, 5 편집",
	AUTOTRAN_REQ: "5 승인 편집, 10 편집 필요",
	NEWMOVIE_REQ: "20 승인 편집 필요",
	TYPE_MOVIE: "영화 이름, URL 또는 파일 입력",
	SUB_MISSED: "자막을 사용할 수 없습니다.",
	ADD_UR_SUB: "이 영화의 자막 추가",
	CLICK_NXT_BTN: "또는 다음 버튼을 클릭하여",
	AUTO_TRANS: "자동으로 새 번역",
	NOTIFS: "알림",
	USR_ACTS: "사용자 활동",
	LOADING: "로딩 중",
	ADD_TXT: "텍스트 추가",
	DIALOGS: "대화",
	H_I: "청각 장애",
	NO_H_I: "청각 장애인 텍스트가 생성되지 않았습니다. 생성하려면 편집을 클릭하십시오.",
	SUB_LISTS_DESC: "SubAsk에서 사용자가 제공 한 일부 자막 목록",
	INCLUDE_H_I: "청각 장애가 있습니까?",
	NOT_INCLUDED: "추가하지 않았습니다",
	INCLUDED: "추가했다",
	NO_MATCH: "검색 텍스트와 일치하는 것이 없습니다",
	YOUR_SUB: "자막 파일을 여기에 놓거나 선택하십시오",
	TOP: "상단",
	BOTTOM: "바닥",
	EDIT_TEXTS: "텍스트 편집",
	EDIT_BTN_TTL: "자막 텍스트를 변경하려면",
	SYNC: "동기화",
	SYNC_TTL: "자막 타이밍을 변경하려면",
	H_I_TTL: "청각 장애가있는 사람들을위한 것입니다",
	DUALITY: "듀얼 자막",
	DUALITY_TTL: "이중 언어 자막을 사용하여 두 세트의 자막이있는 영화보기",
	QUOTES_LIST_TTL: "영화 인용구 나열",
	MOVIE_LIST_TTL: "영화 자막 나열",
	FEEDBACK_MSG: "우리는 당신의 생각, 우려 또는 무엇이든 문제를 듣고 싶습니다!",
	ASK_NEW_MOVIE: "새 영화 추가 요청",
	ASK_MOVIE_DESC: "imdb에서 영화를 찾아 링크 주소를 다음 텍스트 상자에 복사하십시오.",
	SUBMIT: "제출",
	NOT_VALID_IMDB_URL: "입력 한 imdb URL이 유효하지 않습니다. https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "여기에 동영상 파일을 추가하고 가장 적합한 자막을 쉽게 찾을 수 있도록 클릭하십시오",
	SYNC_BY_RT: "영화 품질을 기준으로 자막 선택",
	SYNC_BY_RT_DESC: "원하는 자막을 얻으려면 위의 솔루션 중 하나를 제안합니다. 그렇지 않으면 영화 릴리스 유형을 선택하여 자막을 동기화 할 수 있습니다.",
	NEW_SYNC: "자막에 대한 새로운 타이밍 만들기",
	NEW_SYNC_DESC: "릴리스 유형 목록에서 원하는 타이밍을 찾을 수 없으면 다음 이미지와 같이 새로운 자막 타이밍을 만들 수 있습니다",
	EDIT_ONLINE: "온라인 자막 편집",
	EDIT_ONLINE_DESC: "오류로 가득 찬 비전문 자막이 있어야합니다. 이 사이트는 자막의 각 문장을 쉽게 편집 할 수 있으며 자막을 향상시키는 데 도움을 줄 수 있습니다.",
	EDITING: "자막 편집 도움말",
	EDITING_DESC: "편집은 사용자가 수행하거나 자동으로 수행하지만 사용자의 승인이 필요합니다. 다음 링크에서 편집되어 승인이 필요한 자막 목록을 찾을 수 있습니다.",
	HOW_TO_FIND_SUBS_DESC: "다른 품질의 영화에 적합한 자막을 찾는 데 시간이 걸리거나 번역이 잘못 될 수 있습니다. 전문 자막에 액세스하는 방법은 다음과 같습니다.",
	FIND_SUBS_WAYS: "자막을 찾는 세 가지 방법 :",
	BY_MOVIE_NAME_DESC: "상자에 동영상 이름을 다음 이미지로 입력 한 다음 동영상을 선택하여 자막 다운로드 페이지로 이동하십시오.",
	BY_MOVIE_FILE_DESC: "+ 버튼을 사용하거나 동영상 파일을 상자로 드래그하여 추천 동영상 자막이 표시됩니다.",
	HOME_H1: "자막 찾기 및 동기화",
	BRING_YOUR_SUB: "이 자막은 아직 사용자가 추가하지 않은 상태입니다.이 영화의 자막이 좋은 경우 여기를 끌어 편집 및 동기화하고 다른 사용자가 액세스 할 수있게하십시오.",
	HOME_TTL: "SubAsk-자막 검색",
	HOME_KEYWORDS: "자막, 동기화, 편집, 다운로드",
	HOME_DESC: "영화에서 올 바르고 동기화 된 자막을 찾아 온라인으로 편집",
	TypeMovieQualities: "영화 파일을 여기에 추가 또는 드래그하거나 영화 출시 유형을 입력",
	SEARCH_SUBTITLES: "자막 검색",
	SUB_LISTS: "자막 목록",
	SUBTITLE_LANGS: "_MOV_ 번역",
	SUBTITLE_LANGS_DESC: "_MOV_ subtitle의 모든 번역 언어 목록",
	SUBTITLE_LANGS_KEYWORDS: "번역, _MOV_, 언어",
	DEFAULT_LANGS: "기본 언어",
	AVAILABLE_LANGUAGES: "사용 가능한 자막 언어",
	AVAILABLE_LANGUAGES_DESC: "언어 의 _MOV_ 영화 자막",
	AVAILABLE_LANGUAGE_TTL: "_MOV_의 _LANG_ 자막",
	MISSED_LANGUAGES: "사용할 수없는 언어",
	MISSED_LANGUAGES_DESC: "언어로 _MOV_에 대한 새로운 자막 만들기",
	FEEDBACK: "피드백",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ 자막",
	DNLOAD_PAGE_DESC: "동기화, 편집 및 다운로드 _MOV_ _LANG_ 자막",
	MOVIE_QUOTES: "_MOV_의 유명한 인용문",
	DNLOAD_BTN: "_LANG_ 자막 다운로드",
	DOWNLOAD_PAGE_TTL: "_YEAR_의 _MOV_에 대한 _LANG_ 자막",
	DIALOG_HINT: "이 대화 상자 변경",
	OTHER_LANGS: "다른 언어",
	RELEASE_DATE: "데이트",
	MOVIE_SCORE: "율",
	SEARCH_HINT: "검색",
	THANKS: "감사합니다",
	RE_ADJUST: "다른 시간 속도를 선택하십시오",
	NEED_RE_ADJUST: "다운로드 한 자막을 동기화 한 후 몇 분 후에 동기화되지 않으면",
	RATE_SUB: "영화를 본 후 의견을 보내주세요",
	NOT_ADDED: "자막을 추가해야합니다",
	NAME: "이름",
	OR: "또는",
	SIGN_IN: "로그인",
	SIGN_IN_DESC: "자막을 로그인하고 변경하려면",
	SIGN_UP: "가입하기",
	SIGN_UP_DESC: "SubAsk에서 계정을 만들려면 가입하십시오",
	SIGN_IN_KEYWORDS: "SubAsk 로그인",
	SIGN_UP_KEYWORDS: "SubAsk 가입",
	USERNAME_HAS_TAKEN: "사용자 이름이 이전에 사용되었습니다",
	WRONG_PASS: "사용자 이름 또는 암호가 올바르지 않습니다",
	EMAIL: "이메일",
	PASSWORD: "암호",
	SIGN_OUT: "로그 아웃",
	ABOUT: "약",
	NAV_QUOTES: "인용 부호",
	NAV_SUBTITLES: "자막",
	FIND_SUBTITLES: "자막 찾기",
	FOOTER_DESC: "자막을 만들고 편집 할 수있는 장소",
	CONTACT_US: "문의하기",
	CONTACT_US_DESC: "아래 링크를 사용하여 의견을 공유하고 소셜 미디어에서 우리를 따르십시오",
	SUB_LISTS_TTL: "SubAsk 자막 목록",
	SUB_LISTS_KEYWORDS: "자막, 목록, 참여",
	EDITED_SUBS: "편집 된 자막",
	EDITED_SUBS_DESC: "이 자막은 확인하거나 편집해야합니다",
	NOT_TRANSLATED_SUBS: "자막 번역",
	NOT_TRANSLATED_SUBS_DESC: "이 자막은 귀하의 언어로 번역되어야합니다",
	NOT_ADDED_MOVIES: "사용할 수없는 영화",
	NOT_ADDED_MOVIES_DESC: "자막이없는 영화 목록",
	DEFECTED_SUBS: "결함이있는 자막",
	DEFECTED_SUBS_DESC: "확인 및 검토가 필요한 자막",
	NEW_MOVIE_SUBS: "새로운 영화 자막",
	NEW_SUBS: "새로운 자막",
	NEW_SUBS_DESC: "이 자막은 살펴보고 확인해야합니다.",
	NEW_MOVIES: "새로운 영화",
	NEW_MOVIES_DESC: "이 새로운 영화는 최근에 추가되었습니다",
	YOUR_DOWNLOADS: "다운로드",
	YOUR_DOWNLOADS_DESC: "다운로드 한 자막",
	YOUR_EDITS: "수정 사항",
	YOUR_EDITS_DESC: "편집 한 자막",
	ABOUT_PAGE_TTL: "SubAsk에서 최고의 자막을 얻는 방법?",
	ABOUT_PAGE_DESC: "SubAsk를 사용하면 자막을 동기화하고 수정할 수 있습니다",
	ABOUT_PAGE_KEYWORDS: "SubAsk, 자막 수정, 자막 편집, 자막 동기화",
	HOW_TO_FIND_SUBS: "자막을 빨리 찾는 방법",
	BY_MOVIE_NAME_TTL: "영화 이름 사용",
	BY_MOVIE_FILE_TTL: "영화 파일 사용",
	BY_MOVIE_URL_TTL: "영화 URL 사용",
	BY_MOVIE_URL_DESC: "영화의 스트림 URL을 상자에 복사하고 제안 된 자막 중 하나를 선택하십시오.",
	QUOTES_LISTS_TTL: "SubAsk-영화 따옴표 목록",
	QUOTES_LISTS_DESC: "영화의 인용구 목록",
	QUOTES_LISTS_KEYWORDS: "영화 따옴표",
	MOVIE_QUOTES_TTL: "_MOV_ 따옴표",
	MOVIE_QUOTES_DESC: "_MOV_의 따옴표리스트",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, 따옴표, 좋아하는 따옴표",
	MOVIE_QUOTES_H1: "_MOV_ 영화 시세",
	SEARCH_QUOTES: "따옴표로 검색",
	LIKED_QUOTES_RECENTLY: "따옴표가 최근에 좋아되었습니다",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "따옴표 첫 번째 좋아요",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "영화 시세주의",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "인기 인용구",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "좋아하는 인용문",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "영어",
	farsi: "파시",
	hindi: "힌디 어",
	indonesian: "인도네시아 인",
	turkish: "터키어",
	malayalam: "말라 얄 람어",
	arabic: "아라비아 말",
	vietnamese: "베트남어",
	thai: "타이",
	malay: "말레이 사람",
	chinese: "중국말",
	japanese: "일본어",
	hebrew: "헤브라이 사람",
	bengali: "벵골 사람",
	croatian: "크로아티아",
	portuguese: "포르투갈 인",
	danish: "덴마크 말",
	german: "독일 사람",
	dutch: "네덜란드 사람",
	korean: "한국어",
	spanish: "스페인의",
	french: "프랑스 국민",
	greek: "그리스 어",
	swedish: "스웨덴어",
	norwegian: "노르웨이 인",
	icelandic: "아이슬란드 어",
	italian: "이탈리아 사람",
	urdu: "우르두어",
	russian: "러시아인",
	romanian: "루마니아 사람",
	pashto: "파슈토어"
}