module.exports = {
	DONATE:"Sumbang",
	DONATE_DESC:"Kami bergantung pada sumbangan untuk melaksanakan misi kami.",
	MESSAGE:"Mesej",
	YOUR_HELPS:"Cara menolong",
	YOUR_HELPS_DESC:"Kami bergantung pada bantuan anda untuk meningkatkan sari kata untuk semua bahasa, anda boleh membantu kami dengan cara berikut",
	SUBASK_I18N_DESC:"Sekiranya anda menemui masalah dalam bahasa anda, anda boleh membantu kami memperbaikinya di pautan berikut",
	SUBASK_I18N:"Subask di malaysia",
	CONTRIBUTE:"Edit sari kata, Sahkan suntingan dan Nilai sari kata yang dimuat turun.",
	SEND_FEEDBACKS:"Hantarkan maklum balas anda kepada kami.",
	ALWAYS_RATE:"Semakin banyak maklum balas yang anda berikan, semakin banyak keistimewaan yang anda dapat di Subask,",
	SEE_PROFILE:"Lihat profil dan keistimewaan anda",
	AUTO_TRANS_MSG:"Ini ditambahkan ke barisan untuk diterjemahkan secara automatik, maka anda dapat menyelesaikan masalah yang telah dibuat oleh terjemahan otomatis.",
	UPLOAD_MSG:"Terima kasih, Ini ditambahkan ke barisan untuk menyiasat bagaimana kita dapat menggunakannya.",
	NEEDS_LOGIN:"Anda perlu log masuk",
	CHECK_EDIT:"Sila klik di sini untuk memeriksa pengeditan",
	USER_PRIVILEGES: "Keistimewaan Pengguna",
	RATED_SUBTITLES: "Sarikata Dinilai",
	APPROVED_EDITS: "Pengeditan yang Diluluskan",
	LIKED_QUOTES: "Petikan Suka",
	REPUTATION: "Reputasi",
	SCORE: "Markah",
	PRIVILEGES: "Keistimewaan",
	BADGES: "Lencana",
	MOVIES: "Wayang",
	QUOTES: "Petikan",
	LANGUAGES: "Bahasa",
	EDIT_REQ: "Memerlukan 7 Muat turun dan Nilai Subtil",
	QUOTES_REQ: "Memerlukan 15 Muat Turun dan Nilaikan Subtil",
	UPLOAD_REQ: "Memerlukan 35 Muat turun dan Nilai Subtil",
	APPROVE_REQ: "Memerlukan 25 Muat turun dan Nilai Subtil, 5 Edit",
	AUTOTRAN_REQ: "Perlu 5 Luluskan Edit, 10 Edit",
	NEWMOVIE_REQ: "Memerlukan 20 Meluluskan Edit",
	TYPE_MOVIE: "Masukkan Nama Filem, Url atau Fail",
	SUB_MISSED: "Sari kata tidak tersedia",
	ADD_UR_SUB: "Tambahkan sari kata anda untuk filem ini",
	CLICK_NXT_BTN: "Atau klik pada butang berikut untuk membuat",
	AUTO_TRANS: "Terjemahan baru secara automatik",
	NOTIFS: "Pemberitahuan",
	USR_ACTS: "Aktiviti Pengguna",
	LOADING: "Memuatkan",
	ADD_TXT: "Tambah Teks",
	DIALOGS: "Dialog",
	H_I: "Kecacatan pendengaran",
	NO_H_I: "Teks pekak belum dibuat, klik edit untuk membuat",
	SUB_LISTS_DESC: "Senarai beberapa sub judul yang tersedia dalam SubAsk untuk sumbangan pengguna",
	INCLUDE_H_I: "Adakah anda mengalami masalah pendengaran?",
	NOT_INCLUDED: "belum Menambah",
	INCLUDED: "telah menambah",
	NO_MATCH: "Tidak ada padanan dengan teks carian",
	YOUR_SUB: "Jatuhkan atau pilih fail sari kata di sini",
	TOP: "Atas",
	BOTTOM: "Bawah",
	EDIT_TEXTS: "Edit Teks",
	EDIT_BTN_TTL: "Untuk menukar teks sari kata",
	SYNC: "Penyegerakan",
	SYNC_TTL: "Untuk menukar masa sari kata",
	H_I_TTL: "Ditujukan untuk orang yang cacat pendengaran",
	DUALITY: "Sari Kata Ganda",
	DUALITY_TTL: "Tonton filem dengan dua set sari kata menggunakan sari kata dwibahasa",
	QUOTES_LIST_TTL: "Menyenaraikan beberapa petikan filem",
	MOVIE_LIST_TTL: "Menyenaraikan beberapa sari kata filem",
	FEEDBACK_MSG: "Kami ingin mendengar fikiran, kebimbangan atau masalah anda dengan apa-apa!",
	ASK_NEW_MOVIE: "Minta untuk menambah filem baru",
	ASK_MOVIE_DESC: "Sila cari filem di imdb dan salin alamat pautan ke dalam kotak teks berikut",
	SUBMIT: "Hantar",
	NOT_VALID_IMDB_URL: "url imdb yang dimasukkan tidak sah mestilah seperti https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Klik untuk menambah fail filem di sini dan menjadikannya mudah untuk mencari sari kata yang paling sesuai",
	SYNC_BY_RT: "Pilih sarikata berdasarkan kualiti filem",
	SYNC_BY_RT_DESC: "Untuk mendapatkan sarikata yang dikehendaki, kami mencadangkan satu daripada penyelesaian di atas. Jika tidak, anda boleh menyegerakkan sarikata dengan memilih jenis pelepasan filem.",
	NEW_SYNC: "Buat masa yang baru untuk sarikata",
	NEW_SYNC_DESC: "Jika anda tidak dapat mencari masa yang dikehendaki dalam senarai jenis pelepasan, anda boleh membuat masa sari kata baharu sebagai imej berikut",
	EDIT_ONLINE: "Edit sarikata dalam talian",
	EDIT_ONLINE_DESC: "Anda mesti menghadapi sari kata yang tidak profesional yang penuh dengan kesilapan; laman web ini menyediakan pengeditan mudah setiap ayat dalam subtitle dan anda boleh membantu untuk memperbaiki subtitle.",
	EDITING: "Bantu menyunting sari kata",
	EDITING_DESC: "Pengeditan dilakukan oleh pengguna atau secara automatik, tetapi memerlukan kelulusan pengguna. Anda boleh mencari senarai sarikata yang telah diedit dan memerlukan kelulusan pada pautan berikut.",
	HOW_TO_FIND_SUBS_DESC: "Mencari sarikata kanan untuk filem berkualiti berbeza mungkin mengambil masa anda atau anda mungkin mempunyai versi terjemahan buruk (buruk). Berikut adalah beberapa cara untuk mengakses sarikata profesional.",
	FIND_SUBS_WAYS: "Tiga cara untuk mencari sarikata:",
	BY_MOVIE_NAME_DESC: "Taipkan nama filem sebagai imej berikut dalam kotak kemudian Pilih filem untuk bergerak ke halaman muat turun sarikata.",
	BY_MOVIE_FILE_DESC: "Anda melihat beberapa subtitle filem yang dicadangkan dengan menggunakan butang + atau dengan menyeret fail filem ke kotak.",
	HOME_H1: "Cari dan selaraskan sarikata",
	BRING_YOUR_SUB: "Sarikata ini belum ditambah lagi oleh pengguna, jika anda mempunyai sarikata yang baik untuk filem ini, seret di sini untuk mengedit dan menyegerakkan dan biarkan pengguna lain mengaksesnya",
	HOME_TTL: "SubAsk - Carian Subtitle",
	HOME_KEYWORDS: "Sarikata, Segerak, Edit, Muat Turun",
	HOME_DESC: "Cari sari kata yang betul dan segerak dalam filem anda, dan editnya dalam talian",
	TypeMovieQualities: "Tambah atau seret fail filem di sini atau taipkan jenis siaran filem",
	SEARCH_SUBTITLES: "Carian Sarikata",
	SUB_LISTS: "Senarai Sarikata",
	SUBTITLE_LANGS: "_MOV_ Translations",
	SUBTITLE_LANGS_DESC: "Senarai semua bahasa terjemahan dari subtitle _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "terjemahan, _MOV_, bahasa",
	DEFAULT_LANGS: "Bahasa lalai anda",
	AVAILABLE_LANGUAGES: "Bahasa Sarikata yang tersedia",
	AVAILABLE_LANGUAGES_DESC: "Sarikata filem _MOV_ dalam bahasa _LANG_",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ sari kata _MOV_",
	MISSED_LANGUAGES: "Bahasa yang tidak tersedia",
	MISSED_LANGUAGES_DESC: "Buat sarikata baru untuk _MOV_ dalam bahasa",
	FEEDBACK: "Maklumbalas",
	MOVIE_LANG_SUB: "_MOV_ Sarikata Bahasa _LANG_",
	DNLOAD_PAGE_DESC: "Sinkronkan, Edit dan Muat turun Sarikata Bahasa _LANG_ _MOV_",
	MOVIE_QUOTES: "Petikan Terkenal _MOV_",
	DNLOAD_BTN: "Muat turun subtitle _LANG_",
	DOWNLOAD_PAGE_TTL: "Sarikata bahasa _LANG_ untuk _MOV_ dalam _YEAR_",
	DIALOG_HINT: "Tukar dialog ini",
	OTHER_LANGS: "Bahasa lain",
	RELEASE_DATE: "Tarikh",
	MOVIE_SCORE: "Kadar",
	SEARCH_HINT: "Carian",
	THANKS: "Terima kasih",
	RE_ADJUST: "Pilih kelajuan Masa Lagi",
	NEED_RE_ADJUST: "Cuba subtitle yang dimuat turun kemudian jika ia tidak disegerakkan atau mendapat unsync selepas beberapa minit,",
	RATE_SUB: "Sila beri maklum balas anda selepas menonton filem",
	NOT_ADDED: "Perlu menambah sarikata",
	NAME: "Nama",
	OR: "ATAU",
	SIGN_IN: "Masuk",
	SIGN_IN_DESC: "Untuk log masuk dan buat perubahan pada subtitle",
	SIGN_UP: "Daftar",
	SIGN_UP_DESC: "Untuk membuat akaun di SubAsk, Sila log masuk",
	SIGN_IN_KEYWORDS: "SubAsk masuk",
	SIGN_UP_KEYWORDS: "Pendaftaran SubAsk",
	USERNAME_HAS_TAKEN: "Nama pengguna telah diambil sebelum ini",
	WRONG_PASS: "Nama pengguna atau kata laluan tidak betul",
	EMAIL: "E-mel",
	PASSWORD: "Kata laluan",
	SIGN_OUT: "Keluar",
	ABOUT: "mengenai",
	NAV_QUOTES: "Petikan",
	NAV_SUBTITLES: "Sarikata",
	FIND_SUBTITLES: "Cari Sarikata",
	FOOTER_DESC: "Tempat untuk membuat dan mengedit sarikata",
	CONTACT_US: "Hubungi Kami",
	CONTACT_US_DESC: "Anda boleh menggunakan pautan di bawah untuk berkongsi ulasan anda dan mengikuti kami di media sosial",
	SUB_LISTS_TTL: "Senarai Sari kata SubAsk",
	SUB_LISTS_KEYWORDS: "Sarikata, Senarai, Sumbang",
	EDITED_SUBS: "Sarikata yang telah diedit",
	EDITED_SUBS_DESC: "Sarikata ini perlu disahkan atau diedit",
	NOT_TRANSLATED_SUBS: "Terjemahan sarikata",
	NOT_TRANSLATED_SUBS_DESC: "Sarikata ini harus diterjemahkan dalam bahasa anda",
	NOT_ADDED_MOVIES: "Filem tidak tersedia",
	NOT_ADDED_MOVIES_DESC: "senarai wayang tanpa sebarang sarikata",
	DEFECTED_SUBS: "Sarikata yang rosak",
	DEFECTED_SUBS_DESC: "Sarikata yang perlu diperiksa dan semak",
	NEW_MOVIE_SUBS: "Sarikata Filem Baharu",
	NEW_SUBS: "Sarikata baharu",
	NEW_SUBS_DESC: "Sarikata ini memerlukan anda untuk melihat dan menyemaknya",
	NEW_MOVIES: "Filem baru",
	NEW_MOVIES_DESC: "Filem baru ini telah ditambahkan baru-baru ini",
	YOUR_DOWNLOADS: "Muat Turun anda",
	YOUR_DOWNLOADS_DESC: "Sarikata yang telah anda muat turun",
	YOUR_EDITS: "Pengeditan anda",
	YOUR_EDITS_DESC: "Sari kata yang telah anda edit",
	ABOUT_PAGE_TTL: "Bagaimana untuk mendapatkan sarikata terbaik dari SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk membolehkan pengguna menyegerakkan dan menetapkan subtitle",
	ABOUT_PAGE_KEYWORDS: "SubAsk, menetapkan sarikata, edit sarikata, sari kata penyegerakan",
	HOW_TO_FIND_SUBS: "Bagaimana untuk mencari subtitle dengan cepat",
	BY_MOVIE_NAME_TTL: "Menggunakan nama filem",
	BY_MOVIE_FILE_TTL: "Menggunakan fail filem",
	BY_MOVIE_URL_TTL: "Menggunakan url filem",
	BY_MOVIE_URL_DESC: "Salin urus strim filem ke kotak dan pilih salah satu sarikata yang dicadangkan",
	QUOTES_LISTS_TTL: "SubAsk - Senarai petikan filem",
	QUOTES_LISTS_DESC: "Senarai petikan dalam filem",
	QUOTES_LISTS_KEYWORDS: "petikan filem",
	MOVIE_QUOTES_TTL: "Petikan _MOV_",
	MOVIE_QUOTES_DESC: "Senarai petikan dalam _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, petikan, petikan kegemaran",
	MOVIE_QUOTES_H1: "Petikan Filem _MOV_",
	SEARCH_QUOTES: "Cari Dalam Petikan",
	LIKED_QUOTES_RECENTLY: "Petikan telah disukai baru-baru ini",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Petikan Got the Like pertama",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Petikan Filem Perlu Perhatian",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Petikan Popular",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Petikan Kegemaran anda",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "bahasa inggeris",
	farsi: "farsi",
	hindi: "tidak",
	indonesian: "indonesian",
	turkish: "Turki",
	malayalam: "malayalam",
	arabic: "arabic",
	vietnamese: "vietnamese",
	thai: "thai",
	malay: "malay",
	chinese: "cina",
	japanese: "jepun",
	hebrew: "hebrew",
	bengali: "bengali",
	croatian: "croatian",
	portuguese: "Portugis",
	danish: "danish",
	german: "jerman",
	dutch: "Belanda",
	korean: "korean",
	spanish: "Sepanyol",
	french: "Perancis",
	greek: "greek",
	swedish: "swedish",
	norwegian: "norwegian",
	icelandic: "icelandic",
	italian: "itali",
	urdu: "urdu",
	russian: "orang rusia",
	romanian: "orang Romania",
	pashto: "pashto"
}