module.exports = {
	DONATE:"Doneer",
	DONATE_DESC:"We zijn afhankelijk van donaties om onze missie uit te voeren.",
	MESSAGE:"Bericht",
	YOUR_HELPS:"Hoe te helpen",
	YOUR_HELPS_DESC:"We vertrouwen op uw hulp om de ondertitels voor alle talen te verbeteren, u kunt ons op de volgende manieren helpen",
	SUBASK_I18N_DESC:"Als u een probleem in uw taal heeft gevonden, kunt u ons helpen dit op te lossen via de volgende link",
	SUBASK_I18N:"Subask in het nederlands",
	CONTRIBUTE:"Bewerk ondertitels, bevestig bewerkingen en beoordeel gedownloade ondertitels.",
	SEND_FEEDBACKS:"Stuur ons uw feedback.",
	ALWAYS_RATE:"Hoe meer feedback je geeft, hoe meer privileges je zou hebben in Subask,",
	SEE_PROFILE:"Bekijk uw profiel en privileges",
	AUTO_TRANS_MSG:"Het wordt toegevoegd aan een wachtrij om automatisch te worden vertaald, waarna u de problemen kunt oplossen die zijn gemaakt door automatisch vertalen.",
	UPLOAD_MSG:"Bedankt, het is toegevoegd aan een wachtrij om te onderzoeken hoe we het kunnen gebruiken.",
	NEEDS_LOGIN:"U moet inloggen",
	CHECK_EDIT:"Klik hier om een bewerking te bekijken",
	USER_PRIVILEGES: "Gebruikersrechten",
	RATED_SUBTITLES: "Gewaardeerde ondertitels",
	APPROVED_EDITS: "Goedgekeurde bewerkingen",
	LIKED_QUOTES: "Geachte citaten",
	REPUTATION: "Reputatie",
	SCORE: "SCORE",
	PRIVILEGES: "PRIVILEGES",
	BADGES: "BADGES",
	MOVIES: "Films",
	QUOTES: "Citaten",
	LANGUAGES: "Talen",
	EDIT_REQ: "Heeft 7 download nodig en beoordeel de subtiles",
	QUOTES_REQ: "Heeft 15 download nodig en beoordeel de subtiles",
	UPLOAD_REQ: "Heeft 35 download nodig en beoordeel de subtiles",
	APPROVE_REQ: "Vereist 25 download en beoordeel de subtiles, 5 bewerken",
	AUTOTRAN_REQ: "Vereist 5 Goedkeuren Bewerken, 10 Bewerken",
	NEWMOVIE_REQ: "Heeft 20 goedkeuring nodig Bewerken",
	TYPE_MOVIE: "Voer de filmnaam, URL of bestand in",
	SUB_MISSED: "De ondertitel is niet beschikbaar",
	ADD_UR_SUB: "Voeg je ondertitel toe voor deze film",
	CLICK_NXT_BTN: "Of klik op de volgende knop om te creëren",
	AUTO_TRANS: "Automatisch een nieuwe vertaling",
	NOTIFS: "Meldingen",
	USR_ACTS: "Gebruikersactiviteiten",
	LOADING: "Bezig met laden",
	ADD_TXT: "Voeg tekst toe",
	DIALOGS: "Dialogen",
	H_I: "Slechthorend",
	NO_H_I: "Dove teksten zijn niet gemaakt, klik op bewerken om te maken",
	SUB_LISTS_DESC: "Lijsten van enkele beschikbare ondertitels in SubAsk voor gebruikersbijdrage",
	INCLUDE_H_I: "Ben je slechthorend?",
	NOT_INCLUDED: "is niet toegevoegd",
	INCLUDED: "heeft toegevoegd",
	NO_MATCH: "Er is geen overeenkomst met de zoektekst",
	YOUR_SUB: "Zet hier een ondertitelbestand neer of selecteer het",
	TOP: "Top",
	BOTTOM: "Bodem",
	EDIT_TEXTS: "Bewerk teksten",
	EDIT_BTN_TTL: "Om de ondertitelteksten te wijzigen",
	SYNC: "Synchronisatie",
	SYNC_TTL: "Om de ondertitelingstijd te wijzigen",
	H_I_TTL: "Zijn bedoeld voor mensen die slechthorend zijn",
	DUALITY: "Dubbele ondertitels",
	DUALITY_TTL: "Bekijk films met twee ondertitelsets in tweetalige ondertitels",
	QUOTES_LIST_TTL: "Een lijst met enkele filmcitaten",
	MOVIE_LIST_TTL: "Enkele ondertitels van films weergeven",
	FEEDBACK_MSG: "We horen graag uw mening, zorgen of problemen met iets!",
	ASK_NEW_MOVIE: "Vraag om een ​​nieuwe film toe te voegen",
	ASK_MOVIE_DESC: "Zoek de film in imdb en kopieer het linkadres naar het volgende tekstvak",
	SUBMIT: "Verzenden",
	NOT_VALID_IMDB_URL: "de ingevoerde imdb url is niet geldig, het zou moeten zijn zoals https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Klik hier om een ​​filmbestand toe te voegen en maak het gemakkelijk om de juiste ondertitel te vinden",
	SYNC_BY_RT: "Selecteer ondertitels op basis van filmkwaliteit",
	SYNC_BY_RT_DESC: "Om de gewenste ondertitel te krijgen, raden we een van de bovenstaande oplossingen aan. Anders kunt u de ondertitel synchroniseren door het type filmrelease te selecteren.",
	NEW_SYNC: "Maak een nieuwe timing voor ondertitels",
	NEW_SYNC_DESC: "Als u de gewenste timing niet kunt vinden in de lijst met releasetypes, kunt u een nieuwe ondertiteltiming maken als de volgende afbeelding",
	EDIT_ONLINE: "Bewerk ondertitels online",
	EDIT_ONLINE_DESC: "Je moet onprofessionele ondertitels zijn tegengekomen die vol fouten zitten; deze site biedt gemakkelijke bewerking van elke zin in ondertitels en u kunt helpen om ondertitels te verbeteren.",
	EDITING: "Help ondertitels te bewerken",
	EDITING_DESC: "Bewerkingen worden gedaan door gebruikers of automatisch, maar het heeft goedkeuring van de gebruiker nodig. U kunt een lijst met ondertitels vinden die zijn bewerkt en goedkeuring vereisen via de volgende link.",
	HOW_TO_FIND_SUBS_DESC: "Het vinden van de juiste ondertitel voor films van verschillende kwaliteit kan even duren of je hebt een slechte (slechte vertaling) versie. Hier zijn enkele manieren om toegang te krijgen tot professionele ondertitels.",
	FIND_SUBS_WAYS: "Drie manieren om een ​​ondertitel te vinden:",
	BY_MOVIE_NAME_DESC: "Typ de filmnaam als de volgende afbeelding in het vak en selecteer vervolgens de film om naar de downloadpagina voor ondertitels te gaan.",
	BY_MOVIE_FILE_DESC: "Je ziet een aantal ondertitels voor films door de knop + te gebruiken of door het filmbestand naar het vak te slepen.",
	HOME_H1: "Zoek en synchroniseer ondertitels",
	BRING_YOUR_SUB: "Deze ondertitel is nog niet door gebruikers toegevoegd. Als je een goede ondertitel voor deze film hebt, sleep je deze hierheen om te bewerken en te synchroniseren en geef je andere gebruikers er toegang toe",
	HOME_TTL: "SubAsk - Ondertitels zoeken",
	HOME_KEYWORDS: "Ondertitels, Synchroniseren, Bewerken, Downloaden",
	HOME_DESC: "Zoek de juiste en gesynchroniseerde ondertitels in uw film en bewerk ze online",
	TypeMovieQualities: "Voeg hier een filmbestand toe of sleep het of typ het filmrelease-type",
	SEARCH_SUBTITLES: "Zoek ondertitel",
	SUB_LISTS: "Lijst met ondertitels",
	SUBTITLE_LANGS: "_MOV_ Vertalingen",
	SUBTITLE_LANGS_DESC: "Lijst van alle vertaalde talen van _MOV_-ondertiteling",
	SUBTITLE_LANGS_KEYWORDS: "vertalingen, _MOV_, talen",
	DEFAULT_LANGS: "Uw standaardtaal",
	AVAILABLE_LANGUAGES: "Beschikbare ondertiteltalen",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ ondertiteling van films in taal",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ ondertitel van _MOV_",
	MISSED_LANGUAGES: "Niet-beschikbare talen",
	MISSED_LANGUAGES_DESC: "Maak een nieuwe ondertitel voor _MOV_ in de taal",
	FEEDBACK: "terugkoppeling",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ ondertitel",
	DNLOAD_PAGE_DESC: "Synchroniseer, bewerk en download _MOV_ _LANG_ ondertiteling",
	MOVIE_QUOTES: "Beroemde citaten van _MOV_",
	DNLOAD_BTN: "Download _LANG_ ondertiteling",
	DOWNLOAD_PAGE_TTL: "_LANG_ ondertitel voor _MOV_ in _YEAR_",
	DIALOG_HINT: "Wijzig dit dialoogvenster",
	OTHER_LANGS: "Andere talen",
	RELEASE_DATE: "Datum",
	MOVIE_SCORE: "tarief",
	SEARCH_HINT: "Zoeken",
	THANKS: "Dank je",
	RE_ADJUST: "Selecteer een andere tijdsnelheid",
	NEED_RE_ADJUST: "Probeer de gedownloade ondertiteling en als deze niet is gesynchroniseerd of na een paar minuten niet meer wordt gesynchroniseerd,",
	RATE_SUB: "Geef ons je feedback na het bekijken van de film",
	NOT_ADDED: "Moet een ondertiteling toevoegen",
	NAME: "Naam",
	OR: "OF",
	SIGN_IN: "Aanmelden",
	SIGN_IN_DESC: "Aanmelden en wijzigingen aanbrengen in ondertitels",
	SIGN_UP: "Aanmelden",
	SIGN_UP_DESC: "Meld u aan als u een account wilt maken op SubAsk",
	SIGN_IN_KEYWORDS: "SubAsk login",
	SIGN_UP_KEYWORDS: "SubAsk aanmelden",
	USERNAME_HAS_TAKEN: "Gebruikersnaam is eerder gebruikt",
	WRONG_PASS: "Gebruikersnaam of wachtwoord is onjuist",
	EMAIL: "E-mail",
	PASSWORD: "Wachtwoord",
	SIGN_OUT: "Afmelden",
	ABOUT: "over",
	NAV_QUOTES: "Citaten",
	NAV_SUBTITLES: "Ondertitels",
	FIND_SUBTITLES: "Ondertitels zoeken",
	FOOTER_DESC: "Een plek om ondertitels te maken en te bewerken",
	CONTACT_US: "Neem contact op",
	CONTACT_US_DESC: "U kunt de onderstaande links gebruiken om uw opmerkingen te delen en ons te volgen op sociale media",
	SUB_LISTS_TTL: "SubAsk ondertitels Lijsten",
	SUB_LISTS_KEYWORDS: "Ondertitels, Lijst, Bijdragen",
	EDITED_SUBS: "Bewerkte ondertitels",
	EDITED_SUBS_DESC: "Deze ondertitels moeten worden geverifieerd of bewerkt",
	NOT_TRANSLATED_SUBS: "Ondertitels vertalen",
	NOT_TRANSLATED_SUBS_DESC: "Deze ondertitels moeten in uw taal worden vertaald",
	NOT_ADDED_MOVIES: "Niet-beschikbare films",
	NOT_ADDED_MOVIES_DESC: "lijst met films zonder ondertitels",
	DEFECTED_SUBS: "Defecte ondertitels",
	DEFECTED_SUBS_DESC: "Ondertitels die moeten worden gecontroleerd en beoordeeld",
	NEW_MOVIE_SUBS: "Nieuwe ondertitels van films",
	NEW_SUBS: "Nieuwe ondertitels",
	NEW_SUBS_DESC: "Voor deze ondertitels moet je een kijkje nemen en ze controleren",
	NEW_MOVIES: "Nieuwe films",
	NEW_MOVIES_DESC: "Deze nieuwe films zijn recent toegevoegd",
	YOUR_DOWNLOADS: "Uw downloads",
	YOUR_DOWNLOADS_DESC: "Ondertitels die u hebt gedownload",
	YOUR_EDITS: "Uw bewerkingen",
	YOUR_EDITS_DESC: "Ondertitels die u hebt bewerkt",
	ABOUT_PAGE_TTL: "Hoe haal je de beste ondertitels van SubAsk?",
	ABOUT_PAGE_DESC: "Met SubAsk kunnen gebruikers ondertitels synchroniseren en repareren",
	ABOUT_PAGE_KEYWORDS: "SubAsk, ondertiteling corrigeren, ondertiteling bewerken, ondertiteling synchroniseren",
	HOW_TO_FIND_SUBS: "Snel ondertitels vinden",
	BY_MOVIE_NAME_TTL: "De filmnaam gebruiken",
	BY_MOVIE_FILE_TTL: "Het filmbestand gebruiken",
	BY_MOVIE_URL_TTL: "De film-URL gebruiken",
	BY_MOVIE_URL_DESC: "Kopieer de stream-URL van de film naar het vak en selecteer een van de voorgestelde ondertitels",
	QUOTES_LISTS_TTL: "SubAsk - lijsten met filmcitaten",
	QUOTES_LISTS_DESC: "Lijst met citaten in films",
	QUOTES_LISTS_KEYWORDS: "filmcitaten",
	MOVIE_QUOTES_TTL: "_MOV_ aanhalingstekens",
	MOVIE_QUOTES_DESC: "Lijst met offertes in _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, quotes, favoriete quotes",
	MOVIE_QUOTES_H1: "_MOV_ Movie Quotes",
	SEARCH_QUOTES: "Zoeken in citaten",
	LIKED_QUOTES_RECENTLY: "Citaten zijn onlangs geliket",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Quotes Got the first Like",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Filmscitaten hebben aandacht nodig",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Populaire Citaten",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Je favoriete citaten",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Engels",
	farsi: "farsi",
	hindi: "Hindi",
	indonesian: "Indonesisch",
	turkish: "Turks",
	malayalam: "malayalam",
	arabic: "Arabisch",
	vietnamese: "Vietnamees",
	thai: "Thais",
	malay: "Maleis",
	chinese: "Chinese",
	japanese: "Japans",
	hebrew: "Hebreeuws",
	bengali: "Bengalees",
	croatian: "Kroatisch",
	portuguese: "Portugees",
	danish: "Deens",
	german: "Duitse",
	dutch: "Nederlands",
	korean: "Koreaans",
	spanish: "Spaans",
	french: "Frans",
	greek: "Grieks",
	swedish: "Zweeds",
	norwegian: "Noors",
	icelandic: "IJslands",
	italian: "Italiaans",
	urdu: "Urdu",
	russian: "Russisch",
	romanian: "Roemeense",
	pashto: "pashto"
}