module.exports = {
	DONATE:"Donere",
	DONATE_DESC:"Vi stoler på donasjoner for å utføre oppdraget vårt.",
	MESSAGE:"Beskjed",
	YOUR_HELPS:"Hvordan hjelpe",
	YOUR_HELPS_DESC:"Vi stoler på at du hjelper deg med å forbedre undertekstene for alle språk. Du kan hjelpe oss på følgende måter",
	SUBASK_I18N_DESC:"Hvis du fant noe problem på språket ditt, kan du hjelpe oss med å fikse det i følgende lenke",
	SUBASK_I18N:"SUBASK på norsk",
	CONTRIBUTE:"Rediger undertekster, Bekreft endringer og Ranger nedlastede undertekster.",
	SEND_FEEDBACKS:"Send oss tilbakemeldingene.",
	ALWAYS_RATE:"Jo flere tilbakemeldinger du gir, jo flere privilegier vil du ha i Subask,",
	SEE_PROFILE:"Se profilen din og privilegiene",
	AUTO_TRANS_MSG:"Det er lagt til i en kø for å bli oversatt automatisk, så kan du fikse problemene som er gjort med automatisk oversettelse.",
	UPLOAD_MSG:"Takk, det er lagt til i en kø for å undersøke hvordan vi kan bruke den.",
	NEEDS_LOGIN:"Du må logge inn",
	CHECK_EDIT:"Klikk her for å sjekke en redigering",
	USER_PRIVILEGES: "Brukerrettigheter",
	RATED_SUBTITLES: "Klassifiserte undertekster",
	APPROVED_EDITS: "Godkjente redigeringer",
	LIKED_QUOTES: "Likte sitater",
	REPUTATION: "Rykte",
	SCORE: "Resultat",
	PRIVILEGES: "Privilegier",
	BADGES: "Merker",
	MOVIES: "Filmer",
	QUOTES: "Sitater",
	LANGUAGES: "Språk",
	EDIT_REQ: "Trenger 7 nedlasting og rangering av subtiles",
	QUOTES_REQ: "Trenger 15 nedlasting og rangering av subtiles",
	UPLOAD_REQ: "Trenger 35 nedlasting og rangering av subtiles",
	APPROVE_REQ: "Trenger 25 nedlasting og rangering av subtiles, 5 rediger",
	AUTOTRAN_REQ: "Behov 5 Godkjenn Rediger, 10 Rediger",
	NEWMOVIE_REQ: "Behov 20 Godkjenn Rediger",
	TYPE_MOVIE: "Skriv inn filmnavn, url eller fil",
	SUB_MISSED: "Undertittelen er ikke tilgjengelig",
	ADD_UR_SUB: "Legg til undertekst for denne filmen",
	CLICK_NXT_BTN: "Eller klikk på følgende knapp for å opprette",
	AUTO_TRANS: "Automatisk en ny oversettelse",
	NOTIFS: "Varsler",
	USR_ACTS: "Brukeraktiviteter",
	LOADING: "Laster inn",
	ADD_TXT: "Legg til tekst",
	DIALOGS: "Dialoger",
	H_I: "Hørselshemmet",
	NO_H_I: "Døve tekster har ikke opprettet, klikk på rediger for å opprette",
	SUB_LISTS_DESC: "Lister over noen tilgjengelige undertekster i SubAsk for brukerens bidrag",
	INCLUDE_H_I: "Er du hørselshemmet?",
	NOT_INCLUDED: "har ikke lagt til",
	INCLUDED: "har lagt til",
	NO_MATCH: "Det er ikke noe samsvar med søketeksten",
	YOUR_SUB: "Slipp eller velg en undertittelfil her",
	TOP: "Topp",
	BOTTOM: "Bunn",
	EDIT_TEXTS: "Rediger tekster",
	EDIT_BTN_TTL: "For å endre tekstetekster",
	SYNC: "synkronisering",
	SYNC_TTL: "Slik endrer du undertittels tid",
	H_I_TTL: "Er beregnet på mennesker med nedsatt hørsel",
	DUALITY: "Dual undertekster",
	DUALITY_TTL: "Se filmer med to sett med undertekster ved hjelp av tospråklige undertekster",
	QUOTES_LIST_TTL: "Viser noen sitater på film",
	MOVIE_LIST_TTL: "Viser noen filmtekster",
	FEEDBACK_MSG: "Vi vil gjerne høre dine tanker, bekymringer eller problemer med noe!",
	ASK_NEW_MOVIE: "Be om å legge til en ny film",
	ASK_MOVIE_DESC: "Finn filmen i imdb og kopier linkadressen til følgende tekstboks",
	SUBMIT: "Sende inn",
	NOT_VALID_IMDB_URL: "den angitte imdb-url er ikke gyldig, den skal være https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Klikk for å legge til filmfil her og gjøre det enkelt å finne den rette undertittelen",
	SYNC_BY_RT: "Velg teksting basert på filmkvalitet",
	SYNC_BY_RT_DESC: "For å få ønsket undertittel, foreslår vi en av løsningene ovenfor. Ellers kan du synkronisere undertittelen ved å velge filmutgivelsestype.",
	NEW_SYNC: "Lag en ny timing for undertittel",
	NEW_SYNC_DESC: "Hvis du ikke finner ønsket timing i utgivelsestypelisten, kan du opprette en ny underteksttiming som følgende bilde",
	EDIT_ONLINE: "Rediger teksting på nettet",
	EDIT_ONLINE_DESC: "Du må ha støtt på uprofesjonelle undertekster som er fulle av feil; Dette nettstedet gir enkel redigering av hver setning i undertekster, og du kan bidra til å forbedre underteksten.",
	EDITING: "Hjelp til med å redigere undertekster",
	EDITING_DESC: "Redigeringer utføres av brukere eller automatisk, men det trenger brukernes godkjenning. Du kan finne en liste med undertekster som er redigert og trenger godkjenning ved følgende lenke.",
	HOW_TO_FIND_SUBS_DESC: "Det kan ta tid å finne riktig undertittel for forskjellige kvalitetsfilmer, eller du kan ha en dårlig (dårlig oversettelse) versjon. Her er noen måter du får tilgang til profesjonelle undertekster.",
	FIND_SUBS_WAYS: "Tre måter å finne en undertittel på:",
	BY_MOVIE_NAME_DESC: "Skriv inn filmnavnet som følgende bilde i boksen, og velg deretter filmen som skal flyttes til nedlastingssiden for undertittelen.",
	BY_MOVIE_FILE_DESC: "Du ser noen foreslåtte filmundertittel ved å bruke + -knappen eller ved å dra filmfilen til boksen.",
	HOME_H1: "Finn og synkroniser undertekster",
	BRING_YOUR_SUB: "Denne undertittelen er ikke lagt til av brukere ennå, hvis du har en god undertittel for denne filmen, drar den hit for å redigere og synkronisere og la andre brukere få tilgang til den",
	HOME_TTL: "SubAsk - Søk i undertekster",
	HOME_KEYWORDS: "Undertekster, synkroniser, rediger, last ned",
	HOME_DESC: "Finn riktig og synkronisert undertittel i filmen din, og rediger dem på nettet",
	TypeMovieQualities: "Legg til eller dra filmfil hit eller skriv inn filmutgivelsestype",
	SEARCH_SUBTITLES: "Søk undertittel",
	SUB_LISTS: "Liste over undertekster",
	SUBTITLE_LANGS: "_MOV_ Oversettelser",
	SUBTITLE_LANGS_DESC: "Liste over alle oversatte språk for _MOV_ undertittel",
	SUBTITLE_LANGS_KEYWORDS: "oversettelser, _MOV_, språk",
	DEFAULT_LANGS: "Standardspråket ditt",
	AVAILABLE_LANGUAGES: "Tilgjengelige undertekstspråk",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ filmtittel på språk",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ undertittel av _MOV_",
	MISSED_LANGUAGES: "Ikke-tilgjengelige språk",
	MISSED_LANGUAGES_DESC: "Lag ny undertittel for _MOV_ på språk",
	FEEDBACK: "Tilbakemelding",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ undertittel",
	DNLOAD_PAGE_DESC: "Synkroniser, rediger og last ned _MOV_ _LANG_ undertittel",
	MOVIE_QUOTES: "_MOV_s berømte sitater",
	DNLOAD_BTN: "Last ned _LANG_ undertittel",
	DOWNLOAD_PAGE_TTL: "_LANG_ undertittel for _MOV_ i _YEAR_",
	DIALOG_HINT: "Endre denne dialogboksen",
	OTHER_LANGS: "Andre språk",
	RELEASE_DATE: "Dato",
	MOVIE_SCORE: "Sats",
	SEARCH_HINT: "Søk",
	THANKS: "Takk skal du ha",
	RE_ADJUST: "Velg en annen tidshastighet",
	NEED_RE_ADJUST: "Prøv den nedlastede undertittelen, så hvis den ikke er synkronisert eller den blir synkronisert etter noen minutter,",
	RATE_SUB: "Gi oss tilbakemeldingene dine etter å ha sett filmen",
	NOT_ADDED: "Trenger å legge til en undertittel",
	NAME: "Navn",
	OR: "ELLER",
	SIGN_IN: "Logg inn",
	SIGN_IN_DESC: "For å logge inn og gjøre endringer på undertekster",
	SIGN_UP: "Melde deg på",
	SIGN_UP_DESC: "Hvis du vil opprette en konto på SubAsk, må du registrere deg",
	SIGN_IN_KEYWORDS: "SubAsk pålogging",
	SIGN_UP_KEYWORDS: "SubAsk påmelding",
	USERNAME_HAS_TAKEN: "Brukernavn har blitt tatt før",
	WRONG_PASS: "Brukernavn eller passord er feil",
	EMAIL: "e-post",
	PASSWORD: "Passord",
	SIGN_OUT: "Logg ut",
	ABOUT: "Om",
	NAV_QUOTES: "Quotes",
	NAV_SUBTITLES: "teksting",
	FIND_SUBTITLES: "Finn undertekster",
	FOOTER_DESC: "Et sted å opprette og redigere undertekster",
	CONTACT_US: "Kontakt oss",
	CONTACT_US_DESC: "Du kan bruke lenkene nedenfor for å dele dine kommentarer og følge oss på sosiale medier",
	SUB_LISTS_TTL: "SubAsk Lister over undertekster",
	SUB_LISTS_KEYWORDS: "Undertekst, liste, bidra",
	EDITED_SUBS: "Redigerte undertekster",
	EDITED_SUBS_DESC: "Disse undertekstene må bekreftes eller redigeres",
	NOT_TRANSLATED_SUBS: "Oversett undertekster",
	NOT_TRANSLATED_SUBS_DESC: "Disse undertekstene skal oversettes til ditt språk",
	NOT_ADDED_MOVIES: "Ikke tilgjengelige filmer",
	NOT_ADDED_MOVIES_DESC: "liste over filmer uten undertekster",
	DEFECTED_SUBS: "Defekte undertekster",
	DEFECTED_SUBS_DESC: "Undertekster som må sjekkes og gjennomgås",
	NEW_MOVIE_SUBS: "Nye filmtekster",
	NEW_SUBS: "Nye undertekster",
	NEW_SUBS_DESC: "Disse undertekstene trenger at du tar en titt og sjekker dem",
	NEW_MOVIES: "Nye filmer",
	NEW_MOVIES_DESC: "Disse nye filmene er lagt til i det siste",
	YOUR_DOWNLOADS: "Nedlastinger",
	YOUR_DOWNLOADS_DESC: "Undertekster som du har lastet ned",
	YOUR_EDITS: "Dine redigeringer",
	YOUR_EDITS_DESC: "Undertekster som du har redigert",
	ABOUT_PAGE_TTL: "Hvordan få den beste undertittelen fra SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk lar brukere synkronisere og fikse undertekster",
	ABOUT_PAGE_KEYWORDS: "SubAsk, fikse undertittel, rediger undertittel, synkroniser undertittel",
	HOW_TO_FIND_SUBS: "Hvordan finne undertekster raskt",
	BY_MOVIE_NAME_TTL: "Bruker filmnavnet",
	BY_MOVIE_FILE_TTL: "Bruker filmfilen",
	BY_MOVIE_URL_TTL: "Bruker filmen url",
	BY_MOVIE_URL_DESC: "Kopier filmens strømadresse til boksen og velg en av foreslåtte undertekster",
	QUOTES_LISTS_TTL: "SubAsk - Film sitater lister",
	QUOTES_LISTS_DESC: "Liste over sitater i filmer",
	QUOTES_LISTS_KEYWORDS: "film sitater",
	MOVIE_QUOTES_TTL: "_MOV_ sitater",
	MOVIE_QUOTES_DESC: "Sitatliste i _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, sitater, favoritt sitater",
	MOVIE_QUOTES_H1: "_MOV_ Film sitater",
	SEARCH_QUOTES: "Søk i sitater",
	LIKED_QUOTES_RECENTLY: "Sitater har blitt likt den siste tiden",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Sitater Fikk den første Like",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Film sitater trenger oppmerksomhet",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Populære sitater",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Dine favoritt sitater",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Engelsk",
	farsi: "farsi",
	hindi: "hindi",
	indonesian: "indonesisk",
	turkish: "tyrkisk",
	malayalam: "malayalam",
	arabic: "arabisk",
	vietnamese: "vietnamesisk",
	thai: "thai",
	malay: "malay",
	chinese: "kinesisk",
	japanese: "japansk",
	hebrew: "hebraisk",
	bengali: "bengali",
	croatian: "kroa~~POS=TRUNC",
	portuguese: "portugisisk",
	danish: "dansk",
	german: "tysk",
	dutch: "nederlandsk",
	korean: "koreansk",
	spanish: "spansk",
	french: "fransk",
	greek: "gresk",
	swedish: "svensk",
	norwegian: "norsk",
	icelandic: "islandsk",
	italian: "italiensk",
	urdu: "urdu",
	russian: "russisk",
	romanian: "rumensk",
	pashto: "pashto"
}