module.exports = {
	DONATE:"Doar",
	DONATE_DESC:"Contamos com doações para cumprir nossa missão.",
	MESSAGE:"mensagem",
	YOUR_HELPS:"Como ajudar",
	YOUR_HELPS_DESC:"Contamos com a sua ajuda para melhorar as legendas para todos os idiomas, você pode nos ajudar das seguintes maneiras",
	SUBASK_I18N_DESC:"Se você encontrou algum problema no seu idioma, pode nos ajudar a corrigi-lo no seguinte link",
	SUBASK_I18N:"Subask em portugues",
	CONTRIBUTE:"Edite as legendas, confirme as edições e avalie as legendas baixadas.",
	SEND_FEEDBACKS:"Envie-nos seus feedbacks.",
	ALWAYS_RATE:"Quanto mais feedback você der, mais privilégios você teria no Subask,",
	SEE_PROFILE:"Veja seu perfil e privilégios",
	AUTO_TRANS_MSG:"É adicionado a uma fila para ser traduzido automaticamente, então você pode corrigir os problemas que foram feitos pela tradução automática.",
	UPLOAD_MSG:"Obrigado, foi adicionado a uma fila para investigar como podemos usá-lo.",
	NEEDS_LOGIN:"Você precisa fazer o login",
	CHECK_EDIT:"Clique aqui para verificar uma edição",
	USER_PRIVILEGES: "Privilégios do usuário",
	RATED_SUBTITLES: "Legendas avaliadas",
	APPROVED_EDITS: "Edições aprovadas",
	LIKED_QUOTES: "Citações de que gostou",
	REPUTATION: "Reputação",
	SCORE: "Ponto",
	PRIVILEGES: "Privilégios",
	BADGES: "Distintivos",
	MOVIES: "Filmes",
	QUOTES: "citações",
	LANGUAGES: "línguas",
	EDIT_REQ: "Necessita 7 de download e avalie os subtis",
	QUOTES_REQ: "Necessita 15 de download e avalie os subtis",
	UPLOAD_REQ: "Precisa de 35 para baixar e avaliar os subtis",
	APPROVE_REQ: "Precisa de 25 para baixar e avaliar os subtéis, 5 para editar",
	AUTOTRAN_REQ: "Necessita 5 de aprovação para edição, 10 de edição",
	NEWMOVIE_REQ: "Necessita 20 de aprovação para editar",
	TYPE_MOVIE: "Digite o nome do filme, url ou arquivo",
	SUB_MISSED: "A legenda não está disponível",
	ADD_UR_SUB: "Adicione sua legenda para este filme",
	CLICK_NXT_BTN: "Ou clique no botão a seguir para criar",
	AUTO_TRANS: "Automaticamente uma nova tradução",
	NOTIFS: "Notificações",
	USR_ACTS: "Atividades do usuário",
	LOADING: "Carregando",
	ADD_TXT: "Adicione texto",
	DIALOGS: "Diálogos",
	H_I: "Audição deficiente",
	NO_H_I: "Textos surdos não foram criados, clique em editar para criar",
	SUB_LISTS_DESC: "Lista de algumas legendas disponíveis em SubAsk para contribuição dos usuários",
	INCLUDE_H_I: "Você está com deficiência auditiva?",
	NOT_INCLUDED: "não foi adicionado",
	INCLUDED: "adicionou",
	NO_MATCH: "Não há correspondência com o texto da pesquisa",
	YOUR_SUB: "Solte ou selecione um arquivo de legenda aqui",
	TOP: "Topo",
	BOTTOM: "Inferior",
	EDIT_TEXTS: "Editar textos",
	EDIT_BTN_TTL: "Para alterar os textos das legendas",
	SYNC: "Sincronização",
	SYNC_TTL: "Para alterar o tempo das legendas",
	H_I_TTL: "Destina-se a pessoas com deficiência auditiva",
	DUALITY: "Legendas duplas",
	DUALITY_TTL: "Assista a filmes com dois conjuntos de legendas usando legendas bilíngues",
	QUOTES_LIST_TTL: "Listando algumas citações de filmes",
	MOVIE_LIST_TTL: "Listando algumas legendas de filmes",
	FEEDBACK_MSG: "Gostaríamos muito de ouvir seus pensamentos, preocupações ou problemas com qualquer coisa!",
	ASK_NEW_MOVIE: "Peça para adicionar um novo filme",
	ASK_MOVIE_DESC: "Encontre o filme no imdb e copie o endereço do link na seguinte caixa de texto",
	SUBMIT: "Enviar",
	NOT_VALID_IMDB_URL: "o URL do imdb inserido não é válido, deve ser como https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Clique para adicionar o arquivo do filme aqui e facilitar a localização da legenda mais correta",
	SYNC_BY_RT: "Selecionar legendas com base na qualidade do filme",
	SYNC_BY_RT_DESC: "Para obter a legenda desejada, sugerimos uma das soluções acima. Caso contrário, você pode sincronizar a legenda selecionando o tipo de lançamento do filme.",
	NEW_SYNC: "Crie um novo horário para legendas",
	NEW_SYNC_DESC: "Se você não conseguir encontrar o tempo desejado na lista de tipos de versão, poderá criar um novo tempo de legenda como a imagem a seguir",
	EDIT_ONLINE: "Editar legendas online",
	EDIT_ONLINE_DESC: "Você deve ter encontrado legendas não profissionais cheias de erros; este site facilita a edição de cada sentença nas legendas e você pode ajudar a melhorar as legendas.",
	EDITING: "Ajuda para editar legendas",
	EDITING_DESC: "As edições são feitas pelos usuários ou automaticamente, mas precisam da aprovação dos usuários. Você pode encontrar uma lista de legendas que foram editadas e precisam de aprovação no link a seguir.",
	HOW_TO_FIND_SUBS_DESC: "Encontrar a legenda certa para filmes de qualidade diferente pode demorar um pouco ou você pode ter uma versão ruim (má tradução). Aqui estão algumas maneiras de acessar legendas profissionais.",
	FIND_SUBS_WAYS: "Três maneiras de encontrar uma legenda:",
	BY_MOVIE_NAME_DESC: "Digite o nome do filme como a imagem a seguir na caixa e selecione o filme para ir para a página de download de legendas.",
	BY_MOVIE_FILE_DESC: "Você vê algumas legendas de filmes sugeridas usando o botão + ou arrastando o arquivo de filme para a caixa.",
	HOME_H1: "Localizar e sincronizar legendas",
	BRING_YOUR_SUB: "Esta legenda ainda não foi adicionada pelos usuários. Se você possui uma boa legenda para este filme, arraste-o aqui para editar e sincronizar e permitir que outros usuários acessem.",
	HOME_TTL: "SubAsk - Pesquisar legendas",
	HOME_KEYWORDS: "Legendas, Sincronização, Edição, Download",
	HOME_DESC: "Encontre a legenda certa e sincronizada para seu filme, e edite-a on-line",
	TypeMovieQualities: "Adicione ou arraste o arquivo de filme aqui, ou digite o gênero do filme",
	SEARCH_SUBTITLES: "Pesquisar Legenda",
	SUB_LISTS: "Lista de legendas",
	SUBTITLE_LANGS: "Traduções _MOV_",
	SUBTITLE_LANGS_DESC: "Lista de todos os idiomas traduzidos para _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "traduções, _MOV_, idiomas",
	DEFAULT_LANGS: "Seu idioma padrão",
	AVAILABLE_LANGUAGES: "Idiomas de legendas disponíveis",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ legenda do filme no idioma",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ legenda de _MOV_",
	MISSED_LANGUAGES: "Idiomas não disponíveis",
	MISSED_LANGUAGES_DESC: "Criar nova legenda para _MOV_ no idioma",
	FEEDBACK: "Comentários",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ Legenda",
	DNLOAD_PAGE_DESC: "Sincronizar, editar e fazer download de legendas em _LANG_ _MOV_",
	MOVIE_QUOTES: "Citações famosas de _MOV_",
	DNLOAD_BTN: "Baixar legenda em _LANG_",
	DOWNLOAD_PAGE_TTL: "Legendas em _LANG_ para _MOV_ em _YEAR_",
	DIALOG_HINT: "Alterar esta caixa de diálogo",
	OTHER_LANGS: "Outras línguas",
	RELEASE_DATE: "Data",
	MOVIE_SCORE: "Classificação",
	SEARCH_HINT: "Procurar",
	THANKS: "Obrigado",
	RE_ADJUST: "Selecione outra velocidade de tempo",
	NEED_RE_ADJUST: "Experimente a legenda baixada e, se não estiver sincronizada ou se não for sincronizada após alguns minutos,",
	RATE_SUB: "Por favor, nos dê seu feedback depois de assistir ao filme",
	NOT_ADDED: "Precisa adicionar uma legenda",
	NAME: "Nome",
	OR: "OU",
	SIGN_IN: "Log-in",
	SIGN_IN_DESC: "Para fazer login e fazer alterações nas legendas",
	SIGN_UP: "Inscrever-se",
	SIGN_UP_DESC: "Para criar uma conta no SubAsk, inscreva-se",
	SIGN_IN_KEYWORDS: "SubAsk login",
	SIGN_UP_KEYWORDS: "SubAsk inscrição",
	USERNAME_HAS_TAKEN: "O nome de usuário está tomado",
	WRONG_PASS: "O nome de usuário ou senha está incorreta",
	EMAIL: "EMAIL",
	PASSWORD: "Senha",
	SIGN_OUT: "Sair",
	ABOUT: "Sobre",
	NAV_QUOTES: "citações",
	NAV_SUBTITLES: "Legendas",
	FIND_SUBTITLES: "Localizar legendas",
	FOOTER_DESC: "Um lugar para criar e editar legendas",
	CONTACT_US: "Contate-Nos",
	CONTACT_US_DESC: "Você pode usar os links abaixo para compartilhar seus comentários e nos seguir nas redes sociais",
	SUB_LISTS_TTL: "SubAsk Lista de legendas",
	SUB_LISTS_KEYWORDS: "Legendas, Lista, Contribuir",
	EDITED_SUBS: "Legendas Editadas",
	EDITED_SUBS_DESC: "Essas legendas precisam ser verificadas ou editadas",
	NOT_TRANSLATED_SUBS: "Traduzir legendas",
	NOT_TRANSLATED_SUBS_DESC: "Essas legendas precisam ser traduzidas no seu idioma",
	NOT_ADDED_MOVIES: "Filmes não disponíveis",
	NOT_ADDED_MOVIES_DESC: "lista de filmes sem legendas",
	DEFECTED_SUBS: "Legendas defeituosas",
	DEFECTED_SUBS_DESC: "Legendas que precisam ser verificadas e revisadas",
	NEW_MOVIE_SUBS: "Novas legendas de filmes",
	NEW_SUBS: "Novas legendas",
	NEW_SUBS_DESC: "Essas legendas precisam que você dê uma olhada",
	NEW_MOVIES: "Novos filmes",
	NEW_MOVIES_DESC: "Estes novos filmes foram adicionados recentemente",
	YOUR_DOWNLOADS: "Seus downloads",
	YOUR_DOWNLOADS_DESC: "Legendas que você baixou",
	YOUR_EDITS: "Suas edições",
	YOUR_EDITS_DESC: "Legendas que você editou",
	ABOUT_PAGE_TTL: "Como obter a melhor legenda de SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk permite aos usuários sincronizar e corrigir legendas",
	ABOUT_PAGE_KEYWORDS: "SubAsk, corrija legendas, edite legendas, sincronize legendas",
	HOW_TO_FIND_SUBS: "Como encontrar legendas rapidamente",
	BY_MOVIE_NAME_TTL: "Usando o nome do filme",
	BY_MOVIE_FILE_TTL: "Usando o arquivo de filme",
	BY_MOVIE_URL_TTL: "Usando o URL do filme",
	BY_MOVIE_URL_DESC: "Copie o URL do stream do filme para a caixa e selecione uma das legendas sugeridas",
	QUOTES_LISTS_TTL: "SubAsk - Listas de citações de filmes",
	QUOTES_LISTS_DESC: "Lista de citações em filmes",
	QUOTES_LISTS_KEYWORDS: "citações do filme",
	MOVIE_QUOTES_TTL: "_MOV_ aspas",
	MOVIE_QUOTES_DESC: "Lista de cotações em _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, citações, citações favoritas",
	MOVIE_QUOTES_H1: "_MOV_ Movie Quotes",
	SEARCH_QUOTES: "Pesquisa entre aspas",
	LIKED_QUOTES_RECENTLY: "As cotações foram curtidas recentemente",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Cotações Obteve o primeiro Curtir",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Citações de filmes precisam de atenção",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Citações populares",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Suas citações favoritas",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Inglês",
	farsi: "farsi",
	hindi: "hindi",
	indonesian: "indonésio",
	turkish: "turco",
	malayalam: "malayalam",
	arabic: "árabe",
	vietnamese: "vietnamita",
	thai: "tailandês",
	malay: "malaio",
	chinese: "chinês",
	japanese: "japonês",
	hebrew: "hebraico",
	bengali: "bengali",
	croatian: "croata",
	portuguese: "Português",
	danish: "dinamarquês",
	german: "alemão",
	dutch: "holandês",
	korean: "coreano",
	spanish: "espanhol",
	french: "francês",
	greek: "grego",
	swedish: "sueco",
	norwegian: "norueguês",
	icelandic: "islandês",
	italian: "italiano",
	urdu: "urdu",
	russian: "russo",
	romanian: "romena",
	pashto: "pashto"
}