module.exports = {
	DONATE:"Donează",
	DONATE_DESC:"Ne bazăm pe donații pentru a ne îndeplini misiunea.",
	MESSAGE:"Mesaj",
	YOUR_HELPS:"Cum să ajute",
	YOUR_HELPS_DESC:"Ne bazăm pe ajutorul dvs. pentru a îmbunătăți subtitrările pentru toate limbile, ne puteți ajuta prin următoarele moduri",
	SUBASK_I18N_DESC:"Dacă ați găsit vreo problemă în limba dvs., ne puteți ajuta să o rezolvăm în următorul link",
	SUBASK_I18N:"Subask în română",
	CONTRIBUTE:"Editați subtitrările, confirmați modificările și evaluați subtitrările descărcate.",
	SEND_FEEDBACKS:"Trimite-ne feedback-ul tău.",
	ALWAYS_RATE: "Cu cât oferiți mai multe feedback-uri, cu atât veți avea mai multe privilegii în Subask,",
	SEE_PROFILE: "Vedeți profilul și privilegiile dvs.",
	AUTO_TRANS_MSG: "Se adaugă la o coadă pentru a fi tradus automat, apoi puteți rezolva problemele care au fost produse de traducerea automată.",
	UPLOAD_MSG: "Mulțumesc, sa adăugat la o coadă pentru a investiga modul în care îl putem folosi.",
	NEEDS_LOGIN: "Mai întâi trebuie să vă autentificați",
	USER_PRIVILEGES: "Privilegiile utilizatorului",
	RATED_SUBTITLES: "Subtitrări evaluate",
	APPROVED_EDITS: "Editări aprobate",
	LIKED_QUOTES: "Citate apreciate",
	REPUTATION: "Reputatie",
	SCORE: "Scor",
	PRIVILEGES: "Privilegiile",
	BADGES: "Insigne",
	Movies: "Filme",
	QUOTES: "Citate",
	LANGUAGES: "Limbi",
	EDIT_REQ: "Needs 7 Descărcați și evaluați subtitrările",
	QUOTES_REQ: "Necesită 15 Descărcați și evaluați subtitrările",
	UPLOAD_REQ: "Needs 35 Descărcați și evaluați subtitrările",
	APPROVE_REQ: "Necesită 25 Descărcați și evaluați subtitrările, 5 Editați",
	AUTOTRAN_REQ: "Necesită 5 Aprobare editare, 10 Editare",
	NEWMOVIE_REQ: "Necesită 20 Aprobă editare",
	TYPE_MOVIE: "Introduceți numele filmului, adresa URL sau fișierul",
	SUB_MISSED: "Subtitrarea nu este disponibilă",
	ADD_UR_SUB: "Adăugați subtitrarea pentru acest film",
	CLICK_NXT_BTN: "Sau faceți clic pe următorul buton pentru a crea",
	AUTO_TRANS: "O traducere nouă automat",
	NOTIFS: "Notificări",
	USR_ACTS: "Activități ale utilizatorilor",
	LOADING: "Se încarcă",
	ADD_TXT: "Adaugă text",
	DIALOGS: "Dialoguri",
	H_I: "Deficiențe de auz",
	NO_H_I: "Textele surde nu au fost create, faceți clic pe editare pentru a crea",
	SUB_LISTS_DESC: "Editate, adăugată recent, tradusă și alte liste de subtitrări",
	INCLUDE_H_I: "Sunteți cu deficiențe de auz?",
	NOT_INCLUDED: "Nu a adăugat",
	INCLUDED: "A adăugat",
	NO_MATCH: "Nu există nicio potrivire cu textul căutării",
	YOUR_SUB: "Aruncați sau selectați aici un fișier de subtitrare",
	TOP: "Top",
	BOTTOM: "Partea de jos",
	EDIT_TEXTS: "Editați textele",
	EDIT_BTN_TTL: "Pentru a schimba textele subtitrării",
	SYNC: "Sincronizare",
	SYNC_TTL: "Pentru a modifica sincronizarea subtitrării",
	H_I_TTL: "Sunt destinate persoanelor cu deficiențe de auz",
	DUALITY: "Subtitrări duale",
	DUALITY_TTL: "Urmăriți filme cu două seturi de subtitrări folosind subtitrări bilingve",
	QUOTES_LIST_TTL: "Listele de citate ale filmelor",
	MOVIE_LIST_TTL: "Liste de subtitrări de filme",
	CHECK_EDIT: "Există o ediție nouă pentru acest subtitlu, doriți să îl verificați?",
	FEEDBACK_MSG: "Ne-ar plăcea să vă auzim gândurile, îngrijorările sau problemele cu orice",
	ASK_NEW_MOVIE: "Solicitați să adăugați un film nou",
	ASK_MOVIE_DESC: "Găsiți filmul în imdb și copiați adresa linkului în următoarea casetă text",
	SUBMIT: "Trimite",
	NOT_VALID_IMDB_URL: "adresa URL imdb introdusă nu este validă, ar trebui să fie ca https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Faceți clic pentru a adăuga fișierul de film aici și pentru a facilita găsirea celui mai potrivit subtitrare",
	SYNC_BY_RT: "Selectați subtitrări pe baza calității filmului",
	SYNC_BY_RT_DESC: "Pentru a obține subtitrarea dorită, vă sugerăm una dintre soluțiile de mai sus. În caz contrar, puteți sincroniza subtitrarea selectând tipul de lansare a filmului.",
	NEW_SYNC: "Creați o nouă sincronizare pentru subtitrare",
	NEW_SYNC_DESC: "Dacă nu puteți găsi sincronizarea dorită în lista de tipuri de lansare, puteți crea o nouă sincronizare a subtitrării ca imagine următoare",
	EDIT_ONLINE: "Editați subtitrări online",
	EDIT_ONLINE_DESC: "Trebuie să fi întâlnit subtitrări neprofesionale, pline de erori; acest site oferă editare ușoară a fiecărei propoziții în subtitrări și puteți ajuta la îmbunătățirea subtitrărilor.",
	EDITING: "Ajutați la editarea subtitrărilor",
	EDITING_DESC: "Modificările sunt efectuate de utilizatori sau automat, dar necesită aprobarea utilizatorilor. Puteți găsi o listă a subtitrărilor care au fost editate și care necesită aprobare la următorul link.",
	HOW_TO_FIND_SUBS_DESC: "Găsirea subtitrării potrivite pentru filme de calitate diferită vă poate lua timp sau este posibil să aveți o versiune proastă (traducere slabă). Iată câteva modalități de a accesa subtitrările profesionale.",
	FIND_SUBS_WAYS: "Trei moduri de a găsi un subtitlu:",
	BY_MOVIE_NAME_DESC: "Tastați numele filmului ca imagine următoare în casetă, apoi Selectați filmul pentru a trece la pagina de descărcare a subtitrării.",
	BY_MOVIE_FILE_DESC: "Vedeți unele subtitrări de filme sugerate folosind butonul + sau glisând fișierul film în casetă.",
	HOME_H1: "Găsiți și sincronizați subtitrări",
	BRING_YOUR_SUB: "Acest subtitlu nu a fost adăugat încă de către utilizatori, dacă aveți un subtitlu bun pentru acest film, trageți-l aici pentru a edita și sincroniza și permite altor utilizatori să îl acceseze",
	HOME_TTL: "SubAsk - Căutați subtitrări",
	HOME_KEYWORDS: "Subtitrări, Sincronizare, Editare, Descărcare",
	HOME_DESC: "Găsește subtitrarea potrivită și sincronizată pentru filmul dvs. și vă permite să le editați și să le îmbunătățiți online",
	TypeMovieQualities: "Adăugați sau trageți fișierul de film aici sau tastați tipul de lansare a filmului",
	SEARCH_SUBTITLES: "Căutare subtitrare",
	SUB_LISTS: "Lista subtitrărilor",
	SUBTITLE_LANGS: "_MOV_ Traduceri",
	SUBTITLE_LANGS_DESC: "Lista tuturor limbilor traduse ale subtitrării _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "traduceri, _MOV_, limbi",
	DEFAULT_LANGS: "Limba dvs. implicită",
	AVAILABLE_LANGUAGES: "Limbi disponibile pentru subtitrări",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ subtitrare film în limba",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ subtitlu al _MOV_",
	MISSED_LANGUAGES: "Limbi indisponibile",
	MISSED_LANGUAGES_DESC: "Creați un nou subtitrare pentru _MOV_ în limba",
	FEEDBACK: "Părere",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ Subtitrare",
	DNLOAD_PAGE_DESC: "Sincronizați, editați și descărcați subtitrarea _MOV_ _LANG_",
	MOVIE_QUOTES: "Citate celebre ale lui _MOV_",
	DNLOAD_BTN: "Descărcați subtitrarea _LANG_",
	DOWNLOAD_PAGE_TTL: "_LANG_ subtitrare pentru _MOV_ în _YEAR_",
	DIALOG_HINT: "Schimbați acest dialog",
	OTHER_LANGS: "Alte limbi",
	RELEASE_DATE: "Data",
	MOVIE_SCORE: "Rată",
	SEARCH_HINT: "Căutare",
	THANKS: "Mulțumesc",
	RE_ADJUST: "Selectați viteza Another Time",
	NEED_RE_ADJUST: "Încercați subtitrarea descărcată atunci dacă nu este sincronizată sau se dezincronizează după câteva minute,",
	RATE_SUB: "Vă rugăm să evaluați subtitrarea după vizionarea filmului",
	NOT_ADDED: "Trebuie să adăugați un subtitlu",
	NAME: "Nume",
	OR: "SAU",
	SIGN_IN: "Conectare",
	SIGN_IN_DESC: "Pentru a vă conecta și a face modificări la subtitrări",
	SIGN_UP: "Inscrie-te",
	SIGN_UP_DESC: "Pentru a crea un cont pe SubAsk, vă rugăm să vă înscrieți",
	SIGN_IN_KEYWORDS: "SubAsk conectare",
	SIGN_UP_KEYWORDS: "Înscriere SubAsk",
	USERNAME_HAS_TAKEN: "Numele de utilizator a fost luat anterior",
	WRONG_PASS: "Numele de utilizator sau Parola sunt incorecte",
	EMAIL: "E-mail",
	PASSWORD: "Parola",
	SIGN_OUT: "Sign out",
	ABOUT: "Despre",
	NAV_QUOTES: "Citate",
	NAV_SUBTITLES: "Subtitrări",
	FIND_SUBTITLES: "Găsiți subtitrări",
	FOOTER_DESC: "Un loc pentru a crea, sincroniza și edita subtitrări",
	CONTACT_US: "Contactează-ne",
	CONTACT_US_DESC: "Puteți utiliza linkurile de mai jos pentru a partaja comentariile dvs. și pentru a ne urmări pe social media",
	SUB_LISTS_TTL: "SubAsk Liste de subtitrări",
	SUB_LISTS_KEYWORDS: "Subtitrări, Listă, Contribuie",
	EDITED_SUBS: "Subtitrări editate",
	EDITED_SUBS_DESC: "Aceste subtitrări trebuie verificate sau editate",
	NOT_TRANSLATED_SUBS: "Traduceți subtitrări",
	NOT_TRANSLATED_SUBS_DESC: "Aceste subtitrări ar trebui să fie traduse în limba dvs.",
	NOT_ADDED_MOVIES: "Filme nedisponibile",
	NOT_ADDED_MOVIES_DESC: "lista de filme fără subtitrări",
	DEFECTED_SUBS: "Subtitrări dezertate",
	DEFECTED_SUBS_DESC: "Subtitrări care trebuie verificate și revizuite",
	NEW_MOVIE_SUBS: "Subtitrări de filme noi",
	NEW_SUBS: "Subtitrări noi",
	NEW_SUBS_DESC: "Aceste subtitrări au nevoie să aruncați o privire și să le verificați",
	NEW_MOVIES: "Filme noi",
	NEW_MOVIES_DESC: "Aceste filme noi au fost adăugate recent",
	YOUR_DOWNLOADS: "Descărcările dvs.",
	YOUR_DOWNLOADS_DESC: "Subtitrări pe care le-ați descărcat",
	YOUR_EDITS: "Editările dvs.",
	YOUR_EDITS_DESC: "Subtitrări pe care le-ați editat",
	ABOUT_PAGE_TTL: "Cum să obțineți cel mai bun subtitrare de la SubAsk?",
	ABOUT_PAGE_DESC: "În această pagină vă vom arăta cum să sincronizați subtitrarea cu filmul dvs. și să le editați.",
	ABOUT_PAGE_KEYWORDS: "SubAsk, remediați subtitrarea, editați subtitrarea, sincronizați subtitrarea",
	HOW_TO_FIND_SUBS: "Cum să găsiți subtitrări rapid",
	BY_MOVIE_NAME_TTL: "Folosind numele filmului",
	BY_MOVIE_FILE_TTL: "Folosind fișierul film",
	BY_MOVIE_URL_TTL: "Folosind adresa URL a filmului",
	BY_MOVIE_URL_DESC: "Copiați adresa URL a fluxului filmului în casetă și selectați unul dintre subtitrările sugerate",
	QUOTES_LISTS_TTL: "SubAsk - Listele de citate ale filmelor",
	QUOTES_LISTS_DESC: "Lista citatelor din filme",
	QUOTES_LISTS_KEYWORDS: "citate de film",
	MOVIE_QUOTES_TTL: "_MOV_ citate",
	MOVIE_QUOTES_DESC: "Lista de cotații în _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, citate, citate preferate",
	MOVIE_QUOTES_H1: "_MOV_ Citate film",
	SEARCH_QUOTES: "Căutați în cotații",
	LIKED_QUOTES_RECENTLY: "Citatele au fost apreciate recent",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Citatele au primit primul Like",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Citatele filmelor au nevoie de atenție",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Citate populare",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Citatele tale preferate",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Engleză",
	farsi: "farsi",
	hindi: "hindi",
	indonesian: "indoneziană",
	turkish: "turc",
	malayalam: "malayalam",
	arabic: "arabic",
	vietnamese: "vietnamez",
	thai: "thailandez",
	malay: "malay",
	chinese: "chinez",
	japanese: "japonez",
	hebrew: "ebraică",
	bengali: "bengali",
	croatian: "croat",
	portuguese: "portugheză",
	danish: "danez",
	german: "limba germana",
	dutch: "olandeză",
	korean: "coreeană",
	spanish: "Spaniolă",
	french: "limba franceza",
	greek: "grecesc",
	swedish: "suedez",
	norwegian: "norvegian",
	icelandic: "islandez",
	italian: "Italiană",
	urdu: "urdu",
	russian: "Rusă",
	romanian: "Română",
	pashto: "pashto"
}
