module.exports = {
	DONATE:"Donera",
	DONATE_DESC:"Vi litar på donationer för att utföra vårt uppdrag.",
	MESSAGE:"Meddelande",
	YOUR_HELPS:"Hur man hjälper",
	YOUR_HELPS_DESC:"Vi litar på dina hjälpmedel för att förbättra undertexterna för alla språk, du kan hjälpa oss på följande sätt",
	SUBASK_I18N_DESC:"Om du hittade några problem på ditt språk kan du hjälpa oss att åtgärda det i följande länk",
	SUBASK_I18N:"Subask på svenska",
	CONTRIBUTE:"Redigera undertexter, bekräfta ändringar och betygsätta nedladdade undertexter.",
	SEND_FEEDBACKS:"Skicka oss dina feedback.",
	ALWAYS_RATE:"Ju mer feedback du ger desto fler privilegier skulle du ha i Subask,",
	SEE_PROFILE:"Se din profil och dina privilegier",
	AUTO_TRANS_MSG:"Det läggs till i en kö för att översättas automatiskt, då kan du åtgärda problemen som har gjorts med automatisk översättning.",
	UPLOAD_MSG:"Tack, det har lagts till i en kö för att undersöka hur vi kan använda den.",
	NEEDS_LOGIN:"Du måste logga in",
	CHECK_EDIT:"Klicka här för att kontrollera en redigering",
	USER_PRIVILEGES: "Användarrättigheter",
	RATED_SUBTITLES: "Klassificerade undertexter",
	APPROVED_EDITS: "Godkända ändringar",
	LIKED_QUOTES: "Gillade citat",
	REPUTATION: "Rykte",
	SCORE: "Göra",
	PRIVILEGES: "Privilegier",
	BADGES: "Märken",
	MOVIES: "Filmer",
	QUOTES: "Citat",
	LANGUAGES: "språk",
	EDIT_REQ: "Behöver 7 nedladdning och betygsätta subtiles",
	QUOTES_REQ: "Behöver 15 nedladdning och betygsätta subtiles",
	UPLOAD_REQ: "Behöver 35 Ladda ner och betygsätta subtilerna",
	APPROVE_REQ: "Behöver 25 nedladdning och betygsätta subtilerna, 5 redigera",
	AUTOTRAN_REQ: "Behov 5 Godkänn redigering, 10 redigera",
	NEWMOVIE_REQ: "Behöver 20 Godkänn redigering",
	TYPE_MOVIE: "Ange filmnamn, webbadress eller fil",
	SUB_MISSED: "Undertexten är inte tillgänglig",
	ADD_UR_SUB: "Lägg till undertexter för den här filmen",
	CLICK_NXT_BTN: "Eller klicka på följande knapp för att skapa",
	AUTO_TRANS: "Automatiskt en ny översättning",
	NOTIFS: "Meddelanden",
	USR_ACTS: "Användaraktiviteter",
	LOADING: "Läser in",
	ADD_TXT: "Lägg till text",
	DIALOGS: "Dialoger",
	H_I: "Hörselskadad",
	NO_H_I: "Döva texter har inte skapats, klicka på redigera för att skapa",
	SUB_LISTS_DESC: "Listor över några tillgängliga undertexter i SubAsk för användarnas bidrag",
	INCLUDE_H_I: "Är du hörselskadad?",
	NOT_INCLUDED: "har inte lagt till",
	INCLUDED: "har lagt till",
	NO_MATCH: "Det finns inte någon matchning med sökteksten",
	YOUR_SUB: "Släpp eller välj en undertextfil här",
	TOP: "Topp",
	BOTTOM: "Botten",
	EDIT_TEXTS: "Redigera texter",
	EDIT_BTN_TTL: "För att ändra textningstexter",
	SYNC: "Synkronisering",
	SYNC_TTL: "För att ändra undertexts timing",
	H_I_TTL: "Är avsedda för personer med hörselskadade",
	DUALITY: "Dubbla undertexter",
	DUALITY_TTL: "Se filmer med två uppsättningar undertexter med tvåspråkiga undertexter",
	QUOTES_LIST_TTL: "Visar några filmcitationstecken",
	MOVIE_LIST_TTL: "Visar några filmundertexter",
	FEEDBACK_MSG: "Vi skulle gärna höra dina tankar, problem eller problem med vad som helst!",
	ASK_NEW_MOVIE: "Be om att lägga till en ny film",
	ASK_MOVIE_DESC: "Vänligen hitta filmen i imdb och kopiera länkadressen till följande textruta",
	SUBMIT: "Skicka in",
	NOT_VALID_IMDB_URL: "den angivna imdb-url är inte giltig, den ska vara https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Klicka för att lägga till filmfil här och gör det enkelt att hitta rätt textning",
	SYNC_BY_RT: "Välj undertexter baserade på filmkvalitet",
	SYNC_BY_RT_DESC: "För att få önskad undertext föreslår vi en av ovanstående lösningar. Annars kan du synkronisera undertexten genom att välja filmsläpptyp.",
	NEW_SYNC: "Skapa en ny timing för undertexten",
	NEW_SYNC_DESC: "Om du inte hittar den önskade tidpunkten i listan med släpptypen kan du skapa en ny undertexttidning som följande bild",
	EDIT_ONLINE: "Redigera undertexter online",
	EDIT_ONLINE_DESC: "Du måste ha stött på oprofessionella undertexter som är fulla av fel; denna webbplats ger enkel redigering av varje meningar i undertexter och du kan hjälpa till att förbättra undertexter.",
	EDITING: "Hjälp med att redigera undertexter",
	EDITING_DESC: "Redigeringar görs av användare eller automatiskt, men det behöver användarnas godkännande. Du kan hitta en lista med undertexter som har redigerats och behöver godkännas på följande länk.",
	HOW_TO_FIND_SUBS_DESC: "Att hitta rätt undertext för olika kvalitetsfilmer kan ta din tid eller så kan du ha en dålig (dålig översättning) version. Här är några sätt att få tillgång till professionella undertexter.",
	FIND_SUBS_WAYS: "Tre sätt att hitta en undertext:",
	BY_MOVIE_NAME_DESC: "Skriv filmnamnet som följande bild i rutan och välj sedan filmen för att flytta till nedladdningssidan för undertexter.",
	BY_MOVIE_FILE_DESC: "Du ser några föreslagna filmundertexter genom att använda + -knappen eller genom att dra filmfilen till rutan.",
	HOME_H1: "Hitta och synkronisera undertexter",
	BRING_YOUR_SUB: "Den här undertexten har inte lagts till ännu av användare. Om du har en bra undertext för den här filmen, dra den hit för att redigera och synkronisera och låta andra användare komma åt den",
	HOME_TTL: "SubAsk - Sök undertexter",
	HOME_KEYWORDS: "Undertexter, synkronisera, redigera, ladda ner",
	HOME_DESC: "Hitta rätt och synkroniserad undertext i din film och redigera dem online",
	TypeMovieQualities: "Lägg till eller dra filmfil här eller skriv filmutgivningstypen",
	SEARCH_SUBTITLES: "Sök undertext",
	SUB_LISTS: "Undertextslista",
	SUBTITLE_LANGS: "_MOV_ Översättningar",
	SUBTITLE_LANGS_DESC: "Lista över alla översatta språk för _MOV_ undertext",
	SUBTITLE_LANGS_KEYWORDS: "översättningar, _MOV_, språk",
	DEFAULT_LANGS: "Ditt standardspråk",
	AVAILABLE_LANGUAGES: "Tillgängliga undertextspråk",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ filmundertexter på språk",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ undertext av _MOV_",
	MISSED_LANGUAGES: "Ej tillgängliga språk",
	MISSED_LANGUAGES_DESC: "Skapa ny undertext för _MOV_ på språket",
	FEEDBACK: "Återkoppling",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ undertext",
	DNLOAD_PAGE_DESC: "Synkronisera, redigera och ladda ner _MOV_ _LANG_ undertext",
	MOVIE_QUOTES: "_MOV_s berömda citat",
	DNLOAD_BTN: "Ladda ner _LANG_ undertext",
	DOWNLOAD_PAGE_TTL: "_LANG_ undertexter för _MOV_ i _YEAR_",
	DIALOG_HINT: "Ändra den här dialogrutan",
	OTHER_LANGS: "Andra språk",
	RELEASE_DATE: "Datum",
	MOVIE_SCORE: "Betygsätta",
	SEARCH_HINT: "Sök",
	THANKS: "Tack",
	RE_ADJUST: "Välj en annan tidshastighet",
	NEED_RE_ADJUST: "Prova den nedladdade undertexten, om den inte är synkroniserad eller om den blir osynkroniserad efter några minuter,",
	RATE_SUB: "Ge oss din feedback när du tittat på film",
	NOT_ADDED: "Behöver lägga till en undertext",
	NAME: "namn",
	OR: "ELLER",
	SIGN_IN: "Logga in",
	SIGN_IN_DESC: "För att logga in och göra ändringar i undertexter",
	SIGN_UP: "Bli Medlem",
	SIGN_UP_DESC: "För att skapa ett konto på SubAsk, vänligen registrera dig",
	SIGN_IN_KEYWORDS: "SubAsk inloggning",
	SIGN_UP_KEYWORDS: "SubAsk-registrering",
	USERNAME_HAS_TAKEN: "Användarnamn har tagits tidigare",
	WRONG_PASS: "Användarnamn eller lösenord är felaktigt",
	EMAIL: "E-post",
	PASSWORD: "Lösenord",
	SIGN_OUT: "Logga ut",
	ABOUT: "Handla om",
	NAV_QUOTES: "Citat",
	NAV_SUBTITLES: "undertexter",
	FIND_SUBTITLES: "Hitta undertexter",
	FOOTER_DESC: "En plats att skapa och redigera undertexter",
	CONTACT_US: "Kontakta oss",
	CONTACT_US_DESC: "Du kan använda länkarna nedan för att dela dina kommentarer och följa oss på sociala medier",
	SUB_LISTS_TTL: "SubAsk Listor över undertexter",
	SUB_LISTS_KEYWORDS: "Undertexter, Lista, Bidra",
	EDITED_SUBS: "Redigerade undertexter",
	EDITED_SUBS_DESC: "Dessa undertexter måste verifieras eller redigeras",
	NOT_TRANSLATED_SUBS: "Översätt undertexter",
	NOT_TRANSLATED_SUBS_DESC: "Dessa undertexter bör översättas till ditt språk",
	NOT_ADDED_MOVIES: "Icke tillgängliga filmer",
	NOT_ADDED_MOVIES_DESC: "lista över filmer utan undertexter",
	DEFECTED_SUBS: "Defekterade undertexter",
	DEFECTED_SUBS_DESC: "Undertexter som måste kontrolleras och granskas",
	NEW_MOVIE_SUBS: "Nya filmundertexter",
	NEW_SUBS: "Nya undertexter",
	NEW_SUBS_DESC: "Dessa undertexter behöver du ta en titt och kolla dem",
	NEW_MOVIES: "Nya filmer",
	NEW_MOVIES_DESC: "Dessa nya filmer har lagts till nyligen",
	YOUR_DOWNLOADS: "Dina nedladdningar",
	YOUR_DOWNLOADS_DESC: "Undertexter som du har laddat ner",
	YOUR_EDITS: "Dina redigeringar",
	YOUR_EDITS_DESC: "Undertexter som du har redigerat",
	ABOUT_PAGE_TTL: "Hur får man den bästa undertexten från SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk låter användare synkronisera och fixa undertexter",
	ABOUT_PAGE_KEYWORDS: "SubAsk, fixa undertexter, redigera undertexter, synkronisera undertext",
	HOW_TO_FIND_SUBS: "Hur man hittar undertexter snabbt",
	BY_MOVIE_NAME_TTL: "Använda filmnamnet",
	BY_MOVIE_FILE_TTL: "Använda filmfilen",
	BY_MOVIE_URL_TTL: "Med filmen url",
	BY_MOVIE_URL_DESC: "Kopiera filmens URL-adress till rutan och välj en av de föreslagna undertexterna",
	QUOTES_LISTS_TTL: "SubAsk - Filmcitatlistor",
	QUOTES_LISTS_DESC: "Lista med citat i filmer",
	QUOTES_LISTS_KEYWORDS: "filmcitationstecken",
	MOVIE_QUOTES_TTL: "_MOV_ citat",
	MOVIE_QUOTES_DESC: "Offertlista i _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, citat, favoritcitat",
	MOVIE_QUOTES_H1: "_MOV_ Filmcitat",
	SEARCH_QUOTES: "Sök i offert",
	LIKED_QUOTES_RECENTLY: "Citat har gillats nyligen",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Citat Fick den första gilla",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Filmcitat behöver uppmärksamhet",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Populära citat",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Dina favoritcitat",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "engelsk",
	farsi: "Persiska",
	hindi: "hindi",
	indonesian: "indonesiska",
	turkish: "turkiska",
	malayalam: "malayalam",
	arabic: "arabicum",
	vietnamese: "vietnamese",
	thai: "thai",
	malay: "malajiska",
	chinese: "kinesisk",
	japanese: "japansk",
	hebrew: "hebré",
	bengali: "bengali",
	croatian: "kroatisk",
	portuguese: "portugisiska",
	danish: "dansk",
	german: "tysk",
	dutch: "dutch",
	korean: "koreanska",
	spanish: "spanska",
	french: "franska",
	greek: "grekisk",
	swedish: "svenska",
	norwegian: "norska",
	icelandic: "isländsk",
	italian: "italienska",
	urdu: "urdu",
	russian: "ryska",
	romanian: "rumänska",
	pashto: "pashto"
}