module.exports = {
	DONATE:"Bağış yap",
	DONATE_DESC:"Misyonumuzu gerçekleştirmek için bağışlara güveniyoruz.",
	MESSAGE:"İleti",
	YOUR_HELPS:"Nasıl yardım edilir",
	YOUR_HELPS_DESC:"Tüm diller için altyazıları geliştirmek için yardımlarınıza güveniyoruz, aşağıdaki yollarla bize yardımcı olabilirsiniz",
	SUBASK_I18N_DESC:"Kendi dilinizde herhangi bir sorun bulursanız, aşağıdaki bağlantıdan düzeltmemize yardımcı olabilirsiniz.",
	SUBASK_I18N:"Subask Türkçe",
	CONTRIBUTE:"Altyazıları düzenleyin, Düzenlemeleri onaylayın ve İndirilen altyazıları değerlendirin.",
	SEND_FEEDBACKS:"Bize geri bildirimlerinizi gönderin.",
	ALWAYS_RATE:"Ne kadar çok geri bildirim verirseniz, Subask'ta o kadar fazla ayrıcalık elde edersiniz,",
	SEE_PROFILE:"Profilinizi ve ayrıcalıklarınızı görün",
	AUTO_TRANS_MSG:"Otomatik olarak çevrilmek üzere bir kuyruğa eklenir, daha sonra otomatik çeviri ile yapılan sorunları çözebilirsiniz.",
	UPLOAD_MSG:"Teşekkürler, nasıl kullanabileceğimizi araştırmak için kuyruğa eklendi.",
	NEEDS_LOGIN:"Giriş yapmanız gerekiyor",
	CHECK_EDIT:"Bir düzenlemeyi kontrol etmek için lütfen buraya tıklayın",
	USER_PRIVILEGES: "Kullanıcı Ayrıcalıkları",
	RATED_SUBTITLES: "Derecelendirilmiş Altyazılar",
	APPROVED_EDITS: "Onaylanmış Düzenlemeler",
	LIKED_QUOTES: "Beğenilen Alıntılar",
	REPUTATION: "İtibar",
	SCORE: "Puan",
	PRIVILEGES: "Ayrıcalıklar",
	BADGES: "Rozetler",
	MOVIES: "Filmler",
	QUOTES: "Alıntılar",
	LANGUAGES: "Diller",
	EDIT_REQ: "Altyazıları 7 İndirmeniz ve Değerlendirmeniz Gerekiyor",
	QUOTES_REQ: "Altyazıların 15 İndirilmesi ve Değerlendirilmesi Gerekiyor",
	UPLOAD_REQ: "Altyazıların 35 İndirilmesi ve Değerlendirilmesi Gerekiyor",
	APPROVE_REQ: "25 İndirmeye ve Altyazıları Derecelendirmeye İhtiyaç Duyar, 5 Düzenleme",
	AUTOTRAN_REQ: "5 Onaylı Düzenleme, 10 Düzenleme Gerekiyor",
	NEWMOVIE_REQ: "20 Düzenleme Düzenlemesi Gerekiyor",
	TYPE_MOVIE: "Film Adı, URL veya Dosya Girin",
	SUB_MISSED: "Altyazı mevcut değil",
	ADD_UR_SUB: "Bu film için altyazınızı ekleyin",
	CLICK_NXT_BTN: "Veya oluşturmak için aşağıdaki düğmeyi tıklayın",
	AUTO_TRANS: "Otomatik olarak yeni bir çeviri",
	NOTIFS: "Bildirimler",
	USR_ACTS: "Kullanıcı Aktiviteleri",
	LOADING: "Yükleniyor",
	ADD_TXT: "Yazı ekle",
	DIALOGS: "Diyaloglar",
	H_I: "İşitme engelliler",
	NO_H_I: "Sağır metinler oluşturulmadı, oluşturmak için düzenle'ye tıklayın",
	SUB_LISTS_DESC: "Daftar beberapa subtitle yang tersedia di SubAsk untuk kontribusi pengguna",
	FEEDBACK_MSG: "Düşüncelerinizi, endişelerinizi veya herhangi bir şeyle ilgili sorunlarınızı duymak isteriz!",
	ASK_NEW_MOVIE: "Yeni bir film eklemeyi iste",
	ASK_MOVIE_DESC: "Lütfen filmi imdb'de bulun ve bağlantı adresini aşağıdaki metin kutusuna kopyalayın",
	SUBMIT: "Sunmak",
	NOT_VALID_IMDB_URL: "girilen imdb url'si geçerli değil https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt gibi olmalıdır",
	ADD_MOVIE_FILE: "Film dosyasını buraya eklemek ve en doğru altyazıyı bulmayı kolaylaştırmak için tıklayın",
	SYNC_BY_RT: "Film kalitesine göre altyazı seçme",
	SYNC_BY_RT_DESC: "İstenen altyazıyı elde etmek için yukarıdaki çözümlerden birini öneririz. Aksi takdirde, film yayınlama türünü seçerek altyazıyı senkronize edebilirsiniz.",
	NEW_SYNC: "Altyazı için yeni bir zamanlama oluşturma",
	NEW_SYNC_DESC: "İstediğiniz zamanlamayı yayın türü listesinde bulamazsanız, aşağıdaki resim gibi yeni bir altyazı zamanlaması oluşturabilirsiniz",
	EDIT_ONLINE: "Altyazıları çevrimiçi düzenleme",
	EDIT_ONLINE_DESC: "Hatalarla dolu profesyonel olmayan altyazılarla karşılaşmış olmanız gerekir; bu site, her cümleyi altyazılarda kolayca düzenlemenizi sağlar ve altyazıları geliştirmenize yardımcı olabilir.",
	EDITING: "Altyazıların düzenlenmesine yardımcı olun",
	EDITING_DESC: "Düzenlemeler kullanıcılar tarafından veya otomatik olarak yapılır, ancak kullanıcıların onaylanması gerekir. Düzenlenmiş ve onaylanması gereken altyazıların listesini aşağıdaki bağlantıda bulabilirsiniz.",
	HOW_TO_FIND_SUBS_DESC: "Farklı kaliteli filmler için doğru altyazıyı bulmak zaman alabilir veya kötü (kötü çeviri) sürümünüz olabilir. İşte profesyonel altyazılara erişmenin bazı yolları.",
	FIND_SUBS_WAYS: "Altyazı bulmanın üç yolu:",
	BY_MOVIE_NAME_DESC: "Film adını kutuya aşağıdaki görüntü olarak yazın ve ardından altyazı indirme sayfasına taşınacak filmi seçin.",
	BY_MOVIE_FILE_DESC: "+ Düğmesini kullanarak veya film dosyasını kutuya sürükleyerek önerilen bazı film altyazılarını görebilirsiniz.",
	HOME_H1: "Altyazıları bulma ve senkronize etme",
	BRING_YOUR_SUB: "Bu altyazı henüz kullanıcılar tarafından eklenmedi, eğer bu film için iyi bir altyazınız varsa, düzenlemek ve senkronize etmek ve diğer kullanıcıların erişmesine izin vermek için buraya sürükleyin",
	HOME_TTL: "SubAsk - Cari Teks",
	HOME_KEYWORDS: "Teks, Sinkronisasi, Edit, Unduh",
	HOME_DESC: "Temukan subtitle yang tepat dan tersinkron dalam film Anda, dan edit secara online",
	TypeMovieQualities: "Tambahkan atau seret file film di sini atau ketik jenis rilis film",
	SEARCH_SUBTITLES: "Cari Subtitle",
	SUB_LISTS: "Daftar Teks",
	SUBTITLE_LANGS: "_MOV_ Terjemahan",
	SUBTITLE_LANGS_DESC: "Daftar semua bahasa terjemahan subtitle _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "terjemahan, _MOV_, bahasa",
	DEFAULT_LANGS: "Bahasa default Anda",
	AVAILABLE_LANGUAGES: "Bahasa Terjemahan yang Tersedia",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ dilde film altyazısı",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ altyazısı _MOV_",
	MISSED_LANGUAGES: "Bahasa tidak tersedia",
	MISSED_LANGUAGES_DESC: "_MOV_ için yeni altyazı dili oluştur",
	FEEDBACK: "Umpan balik",
	MOVIE_LANG_SUB: "_MOV_ _LANG_ Altyazı",
	DNLOAD_PAGE_DESC: "Senkronizasyon, Düzenleme ve İndirme _MOV_ _LANG_ Altyazı",
	EDIT_TEXTS: "Edit subtitle",
	SYNC: "Sinkronisasi",
	MOVIE_QUOTES: "Kutipan Terkenal _MOV_",
	DNLOAD_BTN: "_LANG_ altyazı indir",
	DOWNLOAD_PAGE_TTL: "_MOV_ için _LANG_ altyazı _YEAR_",
	DIALOG_HINT: "Ubah dialog ini",
	OTHER_LANGS: "Bahasa lainnya",
	RELEASE_DATE: "Tanggal",
	MOVIE_SCORE: "Menilai",
	SEARCH_HINT: "Cari",
	THANKS: "Terima kasih",
	RE_ADJUST: "Pilih kecepatan Waktu Lain",
	NEED_RE_ADJUST: "Coba subtitle yang diunduh lalu jika tidak disinkronkan atau tidak disinkronkan setelah beberapa menit,",
	RATE_SUB: "Tolong beri kami tanggapan Anda setelah menonton film",
	NOT_ADDED: "Perlu menambahkan subtitle",
	CHECK_EDIT: "Ada edisi baru untuk subtitle ini yang ingin Anda periksa?",
	NAME: "Nama",
	OR: "ATAU",
	SIGN_IN: "Masuk",
	SIGN_IN_DESC: "Untuk masuk dan membuat perubahan pada subtitle",
	SIGN_UP: "Daftar",
	SIGN_UP_DESC: "Untuk membuat akun di SubAsk, Silakan daftar",
	SIGN_IN_KEYWORDS: "Login SubAsk",
	SIGN_UP_KEYWORDS: "Pendaftaran SubAsk",
	USERNAME_HAS_TAKEN: "Nama pengguna telah diambil sebelumnya",
	WRONG_PASS: "Nama pengguna atau kata sandi salah",
	EMAIL: "Surel",
	PASSWORD: "Kata sandi",
	SIGN_OUT: "Keluar",
	ABOUT: "hakkında",
	NAV_QUOTES: "Tanda kutip",
	NAV_SUBTITLES: "Teks",
	FIND_SUBTITLES: "Temukan Teks",
	FOOTER_DESC: "Tempat untuk membuat dan mengedit subtitle",
	CONTACT_US: "Hubungi kami",
	CONTACT_US_DESC: "Anda dapat menggunakan tautan di bawah untuk membagikan komentar Anda dan mengikuti kami di media sosial",
	SUB_LISTS_TTL: "Daftar Subtitle SubAsk",
	SUB_LISTS_KEYWORDS: "Teks, Daftar, Berkontribusi",
	EDITED_SUBS: "Teks yang diedit",
	EDITED_SUBS_DESC: "Subtitle ini perlu diverifikasi atau diedit",
	NOT_TRANSLATED_SUBS: "Terjemahkan subtitle",
	NOT_TRANSLATED_SUBS_DESC: "Subtitle ini harus diterjemahkan dalam bahasa Anda",
	NOT_ADDED_MOVIES: "Film tidak tersedia",
	NOT_ADDED_MOVIES_DESC: "daftar Film tanpa subtitle",
	DEFECTED_SUBS: "Teks Terjemahan",
	DEFECTED_SUBS_DESC: "Teks yang perlu diperiksa dan ditinjau",
	NEW_MOVIE_SUBS: "Teks Film Baru",
	NEW_SUBS: "Teks Baru",
	NEW_SUBS_DESC: "Subtitle ini membutuhkan Anda untuk melihatnya dan memeriksanya",
	NEW_MOVIES: "Film-film baru",
	NEW_MOVIES_DESC: "Film-film baru ini telah ditambahkan baru-baru ini",
	YOUR_DOWNLOADS: "Unduhan Anda",
	YOUR_DOWNLOADS_DESC: "Terjemahan yang telah Anda unduh",
	YOUR_EDITS: "Suntingan Anda",
	YOUR_EDITS_DESC: "Teks terjemahan yang telah Anda edit",
	ABOUT_PAGE_TTL: "Bagaimana cara mendapatkan subtitle terbaik dari SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk memungkinkan pengguna untuk menyinkronkan dan memperbaiki subtitle",
	ABOUT_PAGE_KEYWORDS: "SubAsk, perbaiki subtitle, edit subtitle, sinkronisasi subtitle",
	HOW_TO_FIND_SUBS: "Cara menemukan subtitle dengan cepat",
	BY_MOVIE_NAME_TTL: "Menggunakan nama film",
	BY_MOVIE_FILE_TTL: "Menggunakan file film",
	BY_MOVIE_URL_TTL: "Menggunakan url film",
	BY_MOVIE_URL_DESC: "Salin url aliran film ke kotak dan pilih salah satu subtitle yang disarankan",
	QUOTES_LISTS_TTL: "SubAsk - Film tırnak listeleri",
	QUOTES_LISTS_DESC: "Filmlerde alıntı listesi",
	QUOTES_LISTS_KEYWORDS: "film alıntıları",
	MOVIE_QUOTES_TTL: "_MOV_ tırnak",
	MOVIE_QUOTES_DESC: "_MOV_ içindeki alıntılar listesi",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, tırnak, favori tırnak",
	MOVIE_QUOTES_H1: "_MOV_ Film Alıntıları",
	SEARCH_QUOTES: "Tırnaklarda Ara",
	LIKED_QUOTES_RECENTLY: "Alıntılar son zamanlarda beğenildi",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Tırnaklar İlk Beğeniyi Aldı",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Filmlerden Alınması Gerekenler",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Popüler Alıntılar",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "En Sevdiğiniz Sözler",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "ingilizce",
	farsi: "Farsça",
	hindi: "Hintçe",
	indonesian: "Endonezya",
	turkish: "Türk",
	malayalam: "malayalam",
	arabic: "Arapça",
	vietnamese: "Vietnam",
	thai: "Tayland",
	malay: "Malaya",
	chinese: "Çince",
	japanese: "Japonca",
	hebrew: "İbranice",
	bengali: "Bengal",
	croatian: "Hırvat",
	portuguese: "Portekizce",
	danish: "Danimarkalı",
	german: "Almanca",
	dutch: "Flemenkçe",
	korean: "Koreli",
	spanish: "İspanyol",
	french: "Fransızca",
	greek: "Yunan",
	swedish: "İsveççe",
	norwegian: "Norveççe",
	icelandic: "İzlandaca",
	italian: "İtalyan",
	urdu: "Urduca",
	russian: "Rusça",
	romanian: "Romanyalı",
	pashto: "Peştuca"
}