module.exports = {
	DONATE:"Quyên góp",
	DONATE_DESC:"Chúng tôi dựa vào sự đóng góp để thực hiện sứ mệnh của mình.",
	MESSAGE:"Thông điệp",
	YOUR_HELPS:"Làm thế nào để giúp đỡ",
	YOUR_HELPS_DESC:"Chúng tôi dựa vào sự giúp đỡ của bạn để cải thiện phụ đề cho tất cả các ngôn ngữ, bạn có thể giúp chúng tôi bằng những cách sau",
	SUBASK_I18N_DESC:"Nếu bạn tìm thấy bất kỳ vấn đề nào trong ngôn ngữ của mình, bạn có thể giúp chúng tôi khắc phục sự cố đó trong liên kết sau",
	SUBASK_I18N:"subask bằng tiếng việt",
	CONTRIBUTE:"Chỉnh sửa phụ đề, Xác nhận chỉnh sửa và Xếp hạng phụ đề đã tải xuống.",
	SEND_FEEDBACKS:"Gửi cho chúng tôi phản hồi của bạn.",
	ALWAYS_RATE:"Bạn càng cung cấp nhiều phản hồi thì bạn càng có nhiều đặc quyền trong Subask,",
	SEE_PROFILE:"Xem hồ sơ và đặc quyền của bạn",
	AUTO_TRANS_MSG:"Nó được thêm vào hàng đợi để được dịch tự động, sau đó bạn có thể khắc phục các sự cố đã xảy ra bằng cách dịch tự động.",
	UPLOAD_MSG:"Cảm ơn bạn, Nó đã được thêm vào một hàng đợi để điều tra cách chúng tôi có thể sử dụng nó.",
	NEEDS_LOGIN:"Bạn cân đăng nhập",
	CHECK_EDIT:"Vui lòng bấm vào đây để kiểm tra một bản chỉnh sửa",
	USER_PRIVILEGES: "Người dùng tư vấn",
	RATED_SUBTITLES: "Phụ đề được xếp hạng",
	APPROVED_EDITS: "Chỉnh sửa được chấp thuận",
	LIKED_QUOTES: "Trích dẫn thích",
	REPUTATION: "Uy tín",
	SCORE: "Ghi bàn",
	PRIVILEGES: "Đặc quyền",
	BADGES: "danh hiệu",
	MOVIES: "Phim",
	QUOTES: "Báo giá",
	LANGUAGES: "Ngôn ngữ",
	EDIT_REQ: "7 Cần tải xuống và xếp hạng các mục con",
	QUOTES_REQ: "Cần 15 Tải xuống và Xếp hạng Các tệp con",
	UPLOAD_REQ: "Cần 35 tải xuống và xếp hạng các mục con",
	APPROVE_REQ: "Cần 25 Tải xuống và Xếp hạng Các Mục con, 5 Chỉnh sửa",
	AUTOTRAN_REQ: "Cần 5 Phê duyệt Chỉnh sửa, 10 Chỉnh sửa",
	NEWMOVIE_REQ: "Cần 20 Phê duyệt Chỉnh sửa",
	TYPE_MOVIE: "Nhập Tên phim, Url hoặc Tệp",
	SUB_MISSED: "Phụ đề không có sẵn",
	ADD_UR_SUB: "Thêm phụ đề của bạn cho phim này",
	CLICK_NXT_BTN: "Hoặc bấm vào nút sau để tạo",
	AUTO_TRANS: "Tự động một bản dịch mới",
	NOTIFS: "Thông báo",
	USR_ACTS: "Hoạt động của Người dùng",
	LOADING: "Đang tải",
	ADD_TXT: "Nhập kí tự",
	DIALOGS: "Hộp thoại",
	H_I: "Khiếm thính",
	NO_H_I: "Văn bản điếc chưa tạo, bấm vào chỉnh sửa để tạo",
	SUB_LISTS_DESC: "Danh sách một số phụ đề có sẵn trong SubAsk cho đóng góp của người dùng",
	FEEDBACK_MSG: "Chúng tôi rất thích nghe suy nghĩ, mối quan tâm hoặc vấn đề của bạn với bất cứ điều gì!",
	ASK_NEW_MOVIE: "Yêu cầu thêm một bộ phim mới",
	ASK_MOVIE_DESC: "Vui lòng tìm phim trong imdb và sao chép địa chỉ liên kết vào hộp văn bản sau",
	SUBMIT: "Gửi đi",
	NOT_VALID_IMDB_URL: "url imdb đã nhập không hợp lệ, nó phải giống như https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "Nhấn vào đây để thêm tập tin phim ở đây và giúp bạn dễ dàng tìm thấy phụ đề phù hợp nhất",
	SYNC_BY_RT: "Chọn phụ đề dựa trên chất lượng phim",
	SYNC_BY_RT_DESC: "Để có được phụ đề mong muốn, chúng tôi đề xuất một trong những giải pháp trên. Nếu không, bạn có thể đồng bộ phụ đề bằng cách chọn loại phát hành phim.",
	NEW_SYNC: "Tạo thời gian mới cho phụ đề",
	NEW_SYNC_DESC: "Nếu bạn không thể tìm thấy thời gian mong muốn trong danh sách loại phát hành, bạn có thể tạo thời gian phụ đề mới như hình ảnh sau đây",
	EDIT_ONLINE: "Chỉnh sửa phụ đề trực tuyến",
	EDIT_ONLINE_DESC: "Bạn phải gặp phụ đề không chuyên nghiệp đầy lỗi; trang web này cung cấp dễ dàng chỉnh sửa từng câu trong phụ đề và bạn có thể giúp cải thiện phụ đề.",
	EDITING: "Giúp chỉnh sửa phụ đề",
	EDITING_DESC: "Chỉnh sửa được thực hiện bởi người dùng hoặc tự động, nhưng nó cần sự chấp thuận của người dùng. Bạn có thể tìm thấy một danh sách các phụ đề đã được chỉnh sửa và cần phê duyệt tại liên kết sau.",
	HOW_TO_FIND_SUBS_DESC: "Tìm phụ đề phù hợp cho các bộ phim chất lượng khác nhau có thể làm bạn mất thời gian hoặc bạn có thể có phiên bản (bản dịch kém). Dưới đây là một số cách để truy cập phụ đề chuyên nghiệp.",
	FIND_SUBS_WAYS: "Ba cách để tìm phụ đề:",
	BY_MOVIE_NAME_DESC: "Nhập tên phim dưới dạng hình ảnh sau vào hộp sau đó Chọn phim để di chuyển đến trang tải xuống phụ đề.",
	BY_MOVIE_FILE_DESC: "Bạn thấy một số phụ đề phim được đề xuất bằng cách sử dụng nút + hoặc bằng cách kéo tệp phim vào hộp.",
	HOME_H1: "Tìm và đồng bộ phụ đề",
	BRING_YOUR_SUB: "Phụ đề này chưa được người dùng thêm vào, nếu bạn có phụ đề hay cho phim này, hãy kéo nó vào đây để chỉnh sửa và đồng bộ hóa và cho phép người dùng khác truy cập nó.",
	HOME_TTL: "SubAsk - Tìm kiếm phụ đề",
	HOME_KEYWORDS: "Phụ đề, Đồng bộ hóa, Chỉnh sửa, Tải xuống",
	HOME_DESC: "Tìm phụ đề đúng và được đồng bộ hóa trong phim của bạn và chỉnh sửa chúng trực tuyến",
	TypeMovieQualities: "Thêm hoặc kéo tệp phim tại đây hoặc nhập loại phát hành phim",
	SEARCH_SUBTITLES: "Tìm kiếm phụ đề",
	SUB_LISTS: "Danh sách phụ đề",
	SUBTITLE_LANGS: "_MOV_ Dịch",
	SUBTITLE_LANGS_DESC: "Danh sách tất cả các ngôn ngữ được dịch của phụ đề _MOV_",
	SUBTITLE_LANGS_KEYWORDS: "bản dịch, _MOV_, ngôn ngữ",
	DEFAULT_LANGS: "Ngôn ngữ mặc định của bạn",
	AVAILABLE_LANGUAGES: "Ngôn ngữ phụ đề có sẵn",
	AVAILABLE_LANGUAGES_DESC: "_MOV_ phụ đề phim bằng ngôn ngữ",
	AVAILABLE_LANGUAGE_TTL: "_LANG_ phụ đề của _MOV_",
	MISSED_LANGUAGES: "Ngôn ngữ không có sẵn",
	MISSED_LANGUAGES_DESC: "Tạo phụ đề mới cho _MOV_ bằng ngôn ngữ",
	FEEDBACK: "Phản hồi",
	MOVIE_LANG_SUB: "_MOV_ Phụ đề tiếng _LANG_",
	DNLOAD_PAGE_DESC: "Đồng bộ hóa, chỉnh sửa và tải xuống _MOV_ phụ đề tiếng _LANG_",
	EDIT_TEXTS: "Chỉnh sửa phụ đề",
	SYNC: "Đồng bộ hóa",
	MOVIE_QUOTES: "Câu nói nổi tiếng của _MOV_",
	DNLOAD_BTN: "Tải phụ đề tiếng _LANG_",
	DOWNLOAD_PAGE_TTL: "phụ đề tiếng _LANG_ cho _MOV_ trong _YEAR_",
	DIALOG_HINT: "Thay đổi hộp thoại này",
	OTHER_LANGS: "Những ngôn ngữ khác",
	RELEASE_DATE: "Ngày",
	MOVIE_SCORE: "Tỷ lệ",
	SEARCH_HINT: "Tìm kiếm",
	THANKS: "Cảm ơn bạn",
	RE_ADJUST: "Chọn tốc độ thời gian khác",
	NEED_RE_ADJUST: "Hãy thử phụ đề được tải xuống sau đó nếu nó không được đồng bộ hóa hoặc nó không được đồng bộ hóa sau vài phút,",
	RATE_SUB: "Vui lòng cho chúng tôi thông tin phản hồi của bạn sau khi xem phim",
	NOT_ADDED: "Cần thêm phụ đề",
	NAME: "Tên",
	OR: "HOẶC LÀ",
	SIGN_IN: "Đăng nhập",
	SIGN_IN_DESC: "Để đăng nhập và thay đổi phụ đề",
	SIGN_UP: "Đăng ký",
	SIGN_UP_DESC: "Để tạo tài khoản trên SubAsk, vui lòng đăng ký",
	SIGN_IN_KEYWORDS: "SubAsk đăng nhập",
	SIGN_UP_KEYWORDS: "SubAsk đăng ký",
	USERNAME_HAS_TAKEN: "Tên người dùng đã được sử dụng trước đó",
	WRONG_PASS: "Tên đăng nhập hoặc tài khoản của bạn không chính xác",
	EMAIL: "E-mail",
	PASSWORD: "Mật khẩu",
	SIGN_OUT: "Đăng xuất",
	ABOUT: "Trong khoảng",
	NAV_QUOTES: "Báo giá",
	NAV_SUBTITLES: "Phụ đề",
	FIND_SUBTITLES: "Tìm phụ đề",
	FOOTER_DESC: "Một nơi để tạo và chỉnh sửa phụ đề",
	CONTACT_US: "Liên hệ chúng tôi",
	CONTACT_US_DESC: "Bạn có thể sử dụng các liên kết dưới đây để chia sẻ ý kiến ​​của bạn và theo dõi chúng tôi trên phương tiện truyền thông xã hội",
	SUB_LISTS_TTL: "SubAsk Danh sách phụ đề",
	SUB_LISTS_KEYWORDS: "Phụ đề, danh sách, đóng góp",
	EDITED_SUBS: "Đã chỉnh sửa phụ đề",
	EDITED_SUBS_DESC: "Những phụ đề cần phải được xác minh hoặc chỉnh sửa",
	NOT_TRANSLATED_SUBS: "Dịch phụ đề",
	NOT_TRANSLATED_SUBS_DESC: "Những phụ đề nên được dịch bằng ngôn ngữ của bạn",
	NOT_ADDED_MOVIES: "Phim không có sẵn",
	NOT_ADDED_MOVIES_DESC: "danh sách phim mà không có phụ đề",
	DEFECTED_SUBS: "Phụ đề bị lỗi",
	DEFECTED_SUBS_DESC: "Phụ đề cần được kiểm tra và xem xét",
	NEW_MOVIE_SUBS: "Phụ đề phim mới",
	NEW_SUBS: "Phụ đề mới",
	NEW_SUBS_DESC: "Những phụ đề này cần bạn xem và kiểm tra chúng",
	NEW_MOVIES: "Phim mới",
	NEW_MOVIES_DESC: "Những bộ phim mới này đã được thêm vào gần đây",
	YOUR_DOWNLOADS: "Tải xuống của bạn",
	YOUR_DOWNLOADS_DESC: "Phụ đề mà bạn đã tải xuống",
	YOUR_EDITS: "Chỉnh sửa của bạn",
	YOUR_EDITS_DESC: "Phụ đề mà bạn đã chỉnh sửa",
	ABOUT_PAGE_TTL: "Làm cách nào để có được phụ đề tốt nhất từ ​​SubAsk?",
	ABOUT_PAGE_DESC: "SubAsk cho phép người dùng đồng bộ hóa và sửa phụ đề",
	ABOUT_PAGE_KEYWORDS: "SubAsk, sửa phụ đề, chỉnh sửa phụ đề, đồng bộ phụ đề",
	HOW_TO_FIND_SUBS: "Cách tìm phụ đề nhanh chóng",
	BY_MOVIE_NAME_TTL: "Sử dụng tên phim",
	BY_MOVIE_FILE_TTL: "Sử dụng tập tin phim",
	BY_MOVIE_URL_TTL: "Sử dụng url phim",
	BY_MOVIE_URL_DESC: "Sao chép url luồng của phim vào hộp và chọn một trong những phụ đề được đề xuất",
	QUOTES_LISTS_TTL: "SubAsk - Danh sách trích dẫn phim",
	QUOTES_LISTS_DESC: "Danh sách trích dẫn trong phim",
	QUOTES_LISTS_KEYWORDS: "trích dẫn phim",
	MOVIE_QUOTES_TTL: "_MOV_ trích dẫn",
	MOVIE_QUOTES_DESC: "Danh sách báo giá trong _MOV_",
	MOVIE_QUOTES_KEYWORDS: "_MOV_, trích dẫn, trích dẫn yêu thích",
	MOVIE_QUOTES_H1: "_MOV_ Trích dẫn phim",
	SEARCH_QUOTES: "Tìm kiếm trong ngoặc kép",
	LIKED_QUOTES_RECENTLY: "Báo giá đã được thích gần đây",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "Trích dẫn Có lượt thích đầu tiên",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "Phim trích dẫn cần chú ý",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "Báo giá phổ biến",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "Trích dẫn yêu thích của bạn",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "Anh",
	farsi: "farsi",
	hindi: "tiếng Hin-ddi",
	indonesian: "Indonesia",
	turkish: "thổ nhĩ kỳ",
	malayalam: "Mã Lai",
	arabic: "tiếng Ả Rập",
	vietnamese: "Tiếng Việt",
	thai: "thái lan",
	malay: "Mã Lai",
	chinese: "người Trung Quốc",
	japanese: "tiếng Nhật",
	hebrew: "hebrew",
	bengali: "bengali",
	croatian: "Tiếng Anh",
	portuguese: "Bồ Đào Nha",
	danish: "người Đan Mạch",
	german: "tiếng Đức",
	dutch: "Hà Lan",
	korean: "Hàn Quốc",
	spanish: "người Tây Ban Nha",
	french: "người Pháp, tiếng Pháp",
	greek: "người Hy Lạp",
	swedish: "Thụy Điển",
	norwegian: "Tiếng Na Uy",
	icelandic: "Quan",
	italian: "người Ý",
	urdu: "urdu",
	russian: "tiếng Nga",
	romanian: "người Rumani",
	pashto: "pashto"
}