module.exports = {
	DONATE:"捐",
	DONATE_DESC:"我们依靠捐款来执行我们的使命。",
	MESSAGE:"信息",
	YOUR_HELPS:"如何帮助",
	YOUR_HELPS_DESC:"我们依靠您的帮助来改善所有语言的字幕，您可以通过以下方式为我们提供帮助",
	SUBASK_I18N_DESC:"如果您发现自己的语言有任何问题，可以通过以下链接帮助我们修复问题",
	SUBASK_I18N:"Subask中文",
	CONTRIBUTE:"编辑字幕，确认编辑并为下载的字幕评分。",
	SEND_FEEDBACKS:"向我们发送您的反馈。",
	ALWAYS_RATE:"您提供的反馈越多，您在Subask中所享有的特权就越多，",
	SEE_PROFILE:"查看您的个人资料和特权",
	AUTO_TRANS_MSG:"它已添加到队列中以自动翻译，然后您可以解决自动翻译带来的问题。",
	UPLOAD_MSG:"谢谢，将它添加到队列中以研究如何使用它。",
	NEEDS_LOGIN:"您需要登录",
	CHECK_EDIT:"请单击此处检查修改",
	USER_PRIVILEGES: "用户权限",
	RATED_SUBTITLES: "额定字幕",
	APPROVED_EDITS: "批准的编辑",
	LIKED_QUOTES: "喜欢的报价",
	REPUTATION: "声誉",
	SCORE: "得分了",
	PRIVILEGES: "礼遇",
	BADGES: "徽章",
	MOVIES: "电影",
	QUOTES: "行情",
	LANGUAGES: "语言能力",
	EDIT_REQ: "需要7下载和评价字幕",
	QUOTES_REQ: "需要15下载并评价Subtiles",
	UPLOAD_REQ: "需要35个下载和评价Subtiles",
	APPROVE_REQ: "需要25个下载和评价Subtiles，5个编辑",
	AUTOTRAN_REQ: "需要5个批准编辑，10个编辑",
	NEWMOVIE_REQ: "需要20个批准编辑",
	TYPE_MOVIE: "输入电影名称，网址或文件",
	SUB_MISSED: "字幕不可用",
	ADD_UR_SUB: "为这部电影添加字幕",
	CLICK_NXT_BTN: "或点击以下按钮创建",
	AUTO_TRANS: "自动进行新翻译",
	NOTIFS: "通知事项",
	USR_ACTS: "用户活动",
	LOADING: "载入中",
	ADD_TXT: "添加文字",
	DIALOGS: "对话方块",
	H_I: "听力障碍",
	NO_H_I: "聋哑文字尚未创建，请点击编辑以创建",
	SUB_LISTS_DESC: "SubAsk中一些可用字幕的列表，以供用户贡献",
	FEEDBACK_MSG: "我们很想听听您的想法，疑虑或任何问题！",
	ASK_NEW_MOVIE: "要求添加新电影",
	ASK_MOVIE_DESC: "请在imdb中找到电影，然后将链接地址复制到以下文本框中",
	SUBMIT: "提交",
	NOT_VALID_IMDB_URL: "输入的imdb网址无效，应类似于https://www.imdb.com/title/tt2106476/?ref_=tt_sims_tt",
	ADD_MOVIE_FILE: "单击此处添加电影文件，并轻松找到最合适的字幕",
	SYNC_BY_RT: "根据电影质量选择字幕",
	SYNC_BY_RT_DESC: "为了获得所需的字幕，我们建议上述解决方案之一。否则，您可以通过选择电影发行类型来同步字幕。",
	NEW_SYNC: "为字幕创建新的时间安排",
	NEW_SYNC_DESC: "如果在发行类型列表中找不到所需的时间，则可以创建一个新的字幕时间，如下图所示",
	EDIT_ONLINE: "在线编辑字幕",
	EDIT_ONLINE_DESC: "您肯定遇到了充满错误的非专业字幕；该站点可轻松编辑字幕中的每个句子，您可以帮助改进字幕。",
	EDITING: "帮助编辑字幕",
	EDITING_DESC: "编辑是由用户完成的，还是自动完成的，但需要用户的批准。您可以在以下链接中找到已编辑且需要批准的字幕列表。",
	HOW_TO_FIND_SUBS_DESC: "为不同质量的电影找到合适的字幕可能会花费您一些时间，或者您的翻译版本不正确。以下是访问专业字幕的一些方法。",
	FIND_SUBS_WAYS: "查找字幕的三种方法：",
	BY_MOVIE_NAME_DESC: "在框中输入电影名称作为下图，然后选择电影以移至字幕下载页面。",
	BY_MOVIE_FILE_DESC: "通过使用+按钮或将电影文件拖动到框中，可以看到一些建议的电影字幕。",
	HOME_H1: "查找和同步字幕",
	BRING_YOUR_SUB: "用户尚未添加此字幕，如果您对此电影有很好的字幕，请将其拖到此处进行编辑和同步，并让其他用户访问",
	HOME_TTL: "SubAsk-搜索字幕",
	HOME_KEYWORDS: "字幕，同步，编辑，下载",
	HOME_DESC: "在电影中找到正确且已同步的字幕，然后在线进行编辑",
	TypeMovieQualities: "在此处添加或拖动电影文件，或键入电影发行类型",
	SEARCH_SUBTITLES: "搜索字幕",
	SUB_LISTS: "字幕清单",
	SUBTITLE_LANGS: "_MOV_翻译",
	SUBTITLE_LANGS_DESC: "_MOV_字幕的所有翻译语言列表",
	SUBTITLE_LANGS_KEYWORDS: "翻译_MOV_语言",
	DEFAULT_LANGS: "您的默认语言",
	AVAILABLE_LANGUAGES: "可用的字幕语言",
	AVAILABLE_LANGUAGES_DESC: "_MOV_语言字幕",
	AVAILABLE_LANGUAGE_TTL: "_MOV_的_LANG_字幕",
	MISSED_LANGUAGES: "不可用的语言",
	MISSED_LANGUAGES_DESC: "为_MOV_语言创建新的字幕",
	FEEDBACK: "反馈",
	MOVIE_LANG_SUB: "_MOV_中文字幕",
	DNLOAD_PAGE_DESC: "同步，编辑和下载_MOV_中文字幕",
	EDIT_TEXTS: "编辑字幕",
	SYNC: "同步化",
	MOVIE_QUOTES: "_MOV_的名言",
	DNLOAD_BTN: "下载中文字幕",
	DOWNLOAD_PAGE_TTL: "_YEAR_中_MOV_的中文字幕",
	DIALOG_HINT: "更改此对话框",
	OTHER_LANGS: "其他语言",
	RELEASE_DATE: "日期",
	MOVIE_SCORE: "率",
	SEARCH_HINT: "搜索",
	THANKS: "谢谢",
	RE_ADJUST: "选择其他时间速度",
	NEED_RE_ADJUST: "请尝试下载的字幕，如果它没有同步或几分钟后变得不同步，",
	RATE_SUB: "看完电影后请给我们您的反馈",
	NOT_ADDED: "需要添加字幕",
	NAME: "名称",
	OR: "要么",
	SIGN_IN: "登入",
	SIGN_IN_DESC: "登录并更改字幕",
	SIGN_UP: "注册",
	SIGN_UP_DESC: "要在SubAsk上创建一个帐户，请注册",
	SIGN_IN_KEYWORDS: "SubAsk登录",
	SIGN_UP_KEYWORDS: "SubAsk注册",
	USERNAME_HAS_TAKEN: "用户名已被使用",
	WRONG_PASS: "用户名或密码不正确",
	EMAIL: "电子邮件",
	PASSWORD: "密码",
	SIGN_OUT: "登出",
	ABOUT: "关于",
	NAV_QUOTES: "行情",
	NAV_SUBTITLES: "字幕",
	FIND_SUBTITLES: "查找字幕",
	FOOTER_DESC: "创建和编辑字幕的地方",
	CONTACT_US: "联系我们",
	CONTACT_US_DESC: "您可以使用下面的链接分享您的评论并在社交媒体上关注我们",
	SUB_LISTS_TTL: "SubAsk字幕列表",
	SUB_LISTS_KEYWORDS: "字幕，列表，贡献",
	EDITED_SUBS: "编辑字幕",
	EDITED_SUBS_DESC: "这些字幕需要验证或编辑",
	NOT_TRANSLATED_SUBS: "翻译字幕",
	NOT_TRANSLATED_SUBS_DESC: "这些字幕应以您的语言翻译",
	NOT_ADDED_MOVIES: "不可用的电影",
	NOT_ADDED_MOVIES_DESC: "没有任何字幕的电影列表",
	DEFECTED_SUBS: "字幕错误",
	DEFECTED_SUBS_DESC: "字幕需要检查和审查",
	NEW_MOVIE_SUBS: "新电影字幕",
	NEW_SUBS: "新字幕",
	NEW_SUBS_DESC: "这些字幕需要您查看并检查",
	NEW_MOVIES: "新电影",
	NEW_MOVIES_DESC: "这些新电影是最近添加的",
	YOUR_DOWNLOADS: "您的下载",
	YOUR_DOWNLOADS_DESC: "您已下载的字幕",
	YOUR_EDITS: "您的编辑",
	YOUR_EDITS_DESC: "您已编辑的字幕",
	ABOUT_PAGE_TTL: "如何从SubAsk获得最佳字幕？",
	ABOUT_PAGE_DESC: "SubAsk允许用户同步和修复字幕",
	ABOUT_PAGE_KEYWORDS: "SubAsk，修复字幕，编辑字幕，同步字幕",
	HOW_TO_FIND_SUBS: "如何快速找到字幕",
	BY_MOVIE_NAME_TTL: "使用电影名称",
	BY_MOVIE_FILE_TTL: "使用电影文件",
	BY_MOVIE_URL_TTL: "使用电影网址",
	BY_MOVIE_URL_DESC: "将电影的流URL复制到框中，然后选择建议的字幕之一",
	QUOTES_LISTS_TTL: "SubAsk-电影行情列表",
	QUOTES_LISTS_DESC: "电影中的报价单",
	QUOTES_LISTS_KEYWORDS: "电影名言",
	MOVIE_QUOTES_TTL: "_MOV_引号",
	MOVIE_QUOTES_DESC: "_MOV_中的报价单",
	MOVIE_QUOTES_KEYWORDS: "_MOV_，引号，收藏夹引号",
	MOVIE_QUOTES_H1: "_MOV_电影行情",
	SEARCH_QUOTES: "搜索报价",
	LIKED_QUOTES_RECENTLY: "行情最近被喜欢",
	LIKED_QUOTES_RECENTLY_DESC: " ",
	FIRST_LIKE_QUOTES: "行情第一个赞",
	FIRST_LIKE_QUOTES_DESC: " ",
	LIKED_MOVIE_QUOTES: "电影行情需要注意",
	LIKED_MOVIE_QUOTES_DESC: " ",
	POPULAR_QUOTES: "热门行情",
	POPULAR_QUOTES_DESC: " ",
	YOUR_FAV_QUOTES: "您最喜欢的报价",
	YOUR_FAV_QUOTES_DESC: " ",
	english: "英语",
	farsi: "波斯语",
	hindi: "印地语",
	indonesian: "印度尼西亚",
	turkish: "土耳其",
	malayalam: "马拉雅拉姆语",
	arabic: "阿拉伯",
	vietnamese: "越南语",
	thai: "泰国",
	malay: "马来语",
	chinese: "中文",
	japanese: "日本",
	hebrew: "希伯来语",
	bengali: "孟加拉",
	croatian: "克罗地亚语",
	portuguese: "葡萄牙语",
	danish: "丹麦语",
	german: "德语",
	dutch: "荷兰人",
	korean: "韩国人",
	spanish: "西班牙文",
	french: "法国人",
	greek: "希腊语",
	swedish: "瑞典",
	norwegian: "挪威",
	icelandic: "冰岛的",
	italian: "义大利文",
	urdu: "乌尔都语",
	russian: "俄语",
	romanian: "罗马尼亚语",
	pashto: "普什图语"
}